### ISSUE TITLE
Refills missing media mixin after update to leading version. 

### ISSUE THREAD

**Issue by mofmn** [thoughtbot/bourbon#1009]
### Expected behavior
I just updated rails 5 application to leading versions of bourbon and neat, looking to play around with new neat version. everything was working fine when i ran Bundle update. I have run both bourbon install and neat install, both report back with no errors
### Actual behavior
First bug to appear was no $helvetica variable, changed this to $font-stack-helvetica as per something i found. Now have undefined mixin media at every instance of @include media (), which appears a lot in bourbon refills, sass on refills page still uses the media include so it shouldnt be a deprecation issue
### Bourbon version
bourbon 5.0.0.beta.7

**Comment by tysongach** [comment]
Hi @mofmn!

Bourbon 5.0 and Neat 2.0 are _major_ version releases and introduce quite a few breaking changes. We follow the [Semantic Versioning](http://semver.org/) guidelines, which means:
 
> Given a version number MAJOR.MINOR.PATCH, increment the:
>
> 1. MAJOR version when you make incompatible API changes,
> 2. MINOR version when you add functionality in a backwards-compatible manner, and
> 3. PATCH version when you make backwards-compatible bug fixes.

One example of these breaking changes, which you mentioned, is the `$helvetica` now being `$font-stack-helvetica`. There are many others, and you can find them all with our change logs:

- Bourbon’s change log: https://github.com/thoughtbot/bourbon/blob/master/CHANGELOG.md
- Neat’s change log: https://github.com/thoughtbot/neat/blob/master/CHANGELOG.md

Depending on the size of your project, it might not be worth upgrading to the latest versions.

Finally, Refills is not currently compatible with Neat 2.0. We are actively working on that library as we speak.

**Comment by mofmn** [comment]
Thanks for the prompt reply. I thought bourbon and neat were independent from each other so i did not expect them to break each other. I was expecting to deal with breaking issues for neat but not so much bourbon as all the refills were still in place and as i say, they appear to be independent from each other.

What do you expect will be necessary to revert? just neat or both neat and bourbon?

**Comment by mofmn** [comment]
Ah i see, i didnt realise that refills used neat as well as bourbon, in my mind they were a bourbon asset, i don't know why, thinking about it its kind of obvious. I guess i just didnt think about it.

I upgraded both, expecting refills to remain compatible as i didn't see a suggestion that they had become incompatible with either version.

I will try to change neat back to 1.7.2 and hopefully this will fix the issue. if not i will backtrack bourbon too and so on until it works

**Comment by mofmn** [comment]
Also anywhere i can read when and what to expect from the new refills?

**Comment by tysongach** [comment]
> I will try to change neat back to 1.7.2 and hopefully this will fix the issue.

If I may recommend: lock it in at 1.8. That’s the latest stable release in the 1.x cycle and it doesn’t depend on Bourbon like 1.7 does.

> Also anywhere i can read when and what to expect from the new refills?

You can follow the project here: https://github.com/thoughtbot/refills/projects.

**Comment by mofmn** [comment]
You most certainly may. 

Unfortunately i have had limited success.

I appear to have 1.8 working but am now getting `0.15em 1.5em` is not a valid length for the `$height` argument in the `size` mixin.  

I have had a look through the changelog but cannot find the relevant change. 

Massively appreciate your time, you have been extremely helpful.

**Comment by mofmn** [comment]
I have fixed that error, i have a bunch more but ill give it a good go before bothering you more

Thanks again

**Comment by tysongach** [comment]
> `0.15em 1.5em` is not a valid length for the `$height` argument in the `size` mixin.

Okay! This is a Bourbon change. The `size` mixin in 5.0 now requires a comma between the two values, so you just need to do:

```diff
-@include size(0.15em 1.5em);
+@include size(0.15em, 1.5em);
```

Here’s the relevant entry into the change log: https://github.com/thoughtbot/bourbon/blob/master/CHANGELOG.md#changed-5

**Comment by tysongach** [comment]
Another option:

We released Bourbon v4.3 which only introduces deprecations _warnings_ for all of the removals in 5.0. So you can upgrade to that, watch you Sass compilation warnings and fix anything in there. During this process, no features will _break_ (not compile), they will just throw warnings in prep for 5.0.

**Comment by mofmn** [comment]
Excellent, i have gone with your suggestion.

I have now run into
"couldn't find file 'twitter-bootstrap-static/fontawesome' with type 'text/css'"
Which is frustrating because i dont really care/use fontawesome that much, but i cant seem to remove the include ( removing @include 'fontawesome'; from application.css doesnt seem to do anything ) and its only occurred at after these update issues. Any idea why this might have happened?

I should have listened to the voice in my head that tells me never to update anything.

**Comment by tysongach** [comment]
Hrm, unfortunately, I have no ideas.

**Comment by mofmn** [comment]
I thought as much, i am guessing that it has to do with me using Bundle update which then broke all the things as it updated them too, Argh

Anyway, thats not your problem, thanks for the help

**Comment by tysongach** [comment]
Of course!

Side note (and maybe you know this): if you run `bundle update <package>` (e.g. `bundle update bourbon`), Bundler will _only_ update that package, not _everything_.

**Comment by mofmn** [comment]
Yeah i did know that, i am just a reckless maverick

**Comment by tysongach** [comment]
@mofmn I’m going to close this; let me know if you have any other questions.
