### ISSUE TITLE
[Deprecation] Function strip-unit is not available in v4.3.3

### ISSUE THREAD

**Issue by stonio** [thoughtbot/bourbon#1013]
### Expected behavior
Include `strip-unit` function in Bourbon v4.3 because function `strip-units` function  is deprecated since v4.3.3 .
### Actual behavior
> WARNING: [Bourbon] [Deprecation] `strip-units` is deprecated and will be removed in 5.0.0. Use the renamed `strip-unit` function instead.

But I cannot found definition of `strip-unit` function…
### Steps to reproduce behavior
```sh
git clone https://github.com/thoughtbot/bourbon.git -b v4.3.3
cd bourbon
git grep '@function strip-units\b' -- *.scss # 1 result
git grep '@function strip-unit\b'  -- *.scss # no result!!!
```
### Bourbon version
v4.3.3

**Comment by tysongach** [comment]
Hi @stonio!

`strip-units` has been _deprecated_ in 4.3, but not removed. We deprecate features to indicate that they will be removed in a future version, in this case 5.0.

So, if you’re using 4.3, continue to use `strip-units` and if you upgrade to 5.0, you’ll need to use `strip-unit`.

**Comment by stonio** [comment]
I agree with you. However the WARNING is explicit:

> [...] Use the renamed strip-unit function instead.

It's a clear injunction to use `strip-unit` function "as is" right now. WARNING message should be:
> [...]Use the renamed strip-unit function **in future version**.

**Comment by gdenisov** [comment]
I was confused by this as well and had to search the repository to make sure strip-unit is indeed not included. Ended up including my own version to get rid of the warning.

**Comment by tysongach** [comment]
@stonio Would you like to submit a PR to improve that message by making it clear the developer should use `strip-unit` when they move to 5.0?

**Comment by tysongach** [comment]
Fixed in https://github.com/thoughtbot/bourbon/commit/04084194ec2c40f9c2e5a397d699b0bc3006ecf6.
