### ISSUE TITLE
What version should we use of Bourbon/Neat/Bitters and Refills?

### ISSUE THREAD

**Issue by bgarrant** [thoughtbot/bourbon#1017]
I am trying to get all of the Bourbon components setup but they don't seem to work together?  What versions should we be using now?  

Bourbon 4.3.3 or 5
Neat 1.8 or 2
Bitters ?
Refills ?

I am starting a couple new projects for clients and just want to get the best setup I can.  Please advise.

Thanks.

**Comment by bgarrant** [comment]
Does Bourbon 4.3.3 work with Neat 2.0?

**Comment by tysongach** [comment]
The only black sheep at the moment is Refills. [As mentioned](https://github.com/thoughtbot/refills/issues/434#issuecomment-289848289), it might not be wise to start new projects with Refills because it is about to shift towards a new/different focus than what you see today.

That being said, Bourbon and Neat are not dependent on each other. Bitters just needs Bourbon 5.

So you can use:

- Bourbon 5.0
- Neat 2.0
- Bitters 1.5

> Does Bourbon 4.3.3 work with Neat 2.0?

Yes.

**Comment by tysongach** [comment]
If you really want to use Refills, you can use:

- Bourbon 5.0
- Neat 1.8
- Bitters 1.5

**Comment by bgarrant** [comment]
Thanks so much. Any ETA on Bourbon 5 final release? Version 4.3.3 works fine but just curious.

**Comment by tysongach** [comment]
No official date, but should be soon.

**Comment by bgarrant** [comment]
On website Bourbon 4.3.3 has almost every item mark as depreciated. All of these functions should not be used any more?

**Comment by tysongach** [comment]
Correct, those are deprecated in 4.3 and removed in 5.0.

You can see the 5.0 docs here: http://bourbon.netlify.com/docs/5.0.0/

**Comment by bgarrant** [comment]
The Bourbon mixins that are not crossed out, are they compatible with 4.3.3 and 5?

http://bourbon.io/docs/

Buttons, Margins, Padding, etc..

**Comment by tysongach** [comment]
Not necessarily. v5 is a major version jump (4.x to 5.x), which means there are some breaking changes (we follow [Semantic Versioning](http://semver.org/)) and not all features are compatible between those versions.

Two documents might help you out:

1. The change log captures changes on a per-version basis: https://github.com/thoughtbot/bourbon/blob/master/CHANGELOG.md
2. Our guide for migrating from v4 to v5: http://bourbon.netlify.com/docs/migrating-from-v4-to-v5/

**Comment by bgarrant** [comment]
I will read it over. Hoping to just use version 5 if it is coming out soon. Thanks again.
