### ISSUE TITLE
Bourbon releases

### ISSUE THREAD

**Issue by weareREASON** [thoughtbot/bourbon#1021]
any chance we can let us know what versions work with other version of neat, bitters and refills
thanks

**Comment by tysongach** [comment]
@weareREASON Hello!

You can find requirements in each project’s readme:

- https://github.com/thoughtbot/bourbon#requirements
- https://github.com/thoughtbot/neat#requirements
- https://github.com/thoughtbot/bitters#requirements
- https://github.com/thoughtbot/refills#requirements
