### ISSUE TITLE
Undefined $font-stack variables

### ISSUE THREAD

**Issue by harberg** [thoughtbot/bourbon#1025]
Hello,

I am switching over to Bourbon 5.0 and making some adjustments to a boilerplate theme that I use to start projects from. Everything seems to be working except for the font-stack variables. Each one that I use I get the error.

`Error: Undefined variable: "$font-stack-helvetica".`

I haven't made any customizations to the _bourbon.scss file or any of the bourbon files for that matter.

What should I be doing to trouble shoot this?

Thanks

**Comment by tysongach** [comment]
Hi @harberg! That variable should work just fine in v5.0.

- How are you using Bourbon, through a package manager?
- Is your code open-source somewhere that I can look at it?

**Comment by tysongach** [comment]
@harberg Any update here?
