### ISSUE TITLE
Bourbon 4.3.4 does not play nice with Neat 2.0.0

### ISSUE THREAD

**Issue by sixtyfive** [thoughtbot/bourbon#1032]
### Expected behavior

The latest version of one should know about what the latest version of the other expects.

### Actual behavior

Bourbon 4.3.4 includes a reference to `_neat-helpers.scss` in its `_grid-settings.scss`, even though `neat-helpers` does not exist anymore.

### Steps to reproduce behavior

Install both Bourbon and Neat as gems, run "neat install", run "bourbon install", look at files.

### Bourbon version

4.3.4

### Environment info

Neat 2.0.0

**Comment by sixtyfive** [comment]
(Side note, Neat documentation documents `neat install --path /blah/blah`, but `neat install` fails if given any further arguments)

**Comment by sixtyfive** [comment]
Apparently I'm so confused by Bourbon/Neat/Bitters that I just mistook Bitters for Bourbon or something. In any case, trying to use the trio has become so confusing that I'm going to be taking a shower now. Also, in all your online documentation, images are horribly broken. Makes everything look as though it was unmaintained. Shame.

**Comment by sixtyfive** [comment]
Okay, it seems all is fine when I use Bourbon/Neat/Bitters directly from Github. Sorry for the hullabaloo.

**Comment by tysongach** [comment]
To clear a couple things up:

> Bourbon 4.3.4 includes a reference to _neat-helpers.scss in its _grid-settings.scss, even though neat-helpers does not exist anymore.

Yep, I think you mean Bitters, specifically Bitters before v1.3 (`grid-settings` and the Neat dependency was removed in v1.3). 

> (Side note, Neat documentation documents neat install --path /blah/blah, but neat install fails if given any further arguments)

This is fixed in the next release; due out any day.

> Also, in all your online documentation, images are horribly broken. Makes everything look as though it was unmaintained. Shame.

Can you post a screenshot or let us what specific pages have broken images? I just visited each of our websites and all images are showing for me.
