### ISSUE TITLE
[Idea] Adding a media query mixin

### ISSUE THREAD

**Issue by DougBeney** [thoughtbot/bourbon#1035]
Hi, everyone. 

Recently, I've been using the below mixin for quickly adding media queries to my sass projects:

```sass
@mixin media($query)
    @media screen and (#{$query})
        @content
```

**Usage**:

```sass
+media("max-width: 749px")
    background: skyblue 
```

What do you think about adding something similar to Bourbon?

**Comment by tysongach** [comment]
Hi @DougBeney!

Thanks for opening this issue and for the suggestion. While a mixin of that nature provides a slightly shorter syntax than the CSS standard, I’m not sure it provides much value. Given that this has been open for about a year now and we’ve received no input from the community of Bourbon, I’m going to close this to indicate that we don’t currently plan to add this feature.

Thanks again!
