### ISSUE TITLE
How i add sass syntax?

### ISSUE THREAD

**Issue by ardamutlu** [thoughtbot/bourbon#1036]
How i add sass syntax?

**Comment by tysongach** [comment]
Hi @ardamutlu, can you expand on the problem you’re having?

**Comment by tysongach** [comment]
I’m closing this because the problem or question being asked is not clear, so we can’t offer a solution.

**Comment by ardamutlu** [comment]
like;
compass create myproject --syntax sass

i am using sass, not scss

**Comment by tysongach** [comment]
Thanks for clarifying.

Bourbon is simply a library of Sass files (not a framework like Compass), and even though it is written in the SCSS syntax, you can still import it into your SASS-syntax project.
