### ISSUE TITLE
Gulp- Error: File to import not found or unreadable: bourbon.

### ISSUE THREAD

**Issue by ssosina** [thoughtbot/bourbon#1037]
I'm creating a starter project using latest versions of Neat and Bourbon. However, I'm having trouble importing bourbon to my stylesheet. Please see below or [feel free to download the project here](https://github.com/ssosina/starter-project)

**Package.json** 
I have no packages installed globally.
```
"devDependencies": {
    "bourbon": "^4.3.4",
    "bourbon-neat": "^2.1.0",
  }
```

**Gulpfile.js**

```
var bourbon 	= require('bourbon').includePaths;
var neat		= require('bourbon-neat').includePaths;

gulp.task('sass', function(){
	gulp.src('source/scss/*.scss')
       .pipe(sass({
        	includePaths: bourbon, 
        	includePaths: neat
      	}))
	.pipe(gulp.dest('public/css')) // save output in public css folder
	.pipe(browserSync.stream());
});
```

**SCSS file** 
```
@import "bourbon";
@import "neat";
@import "grid-settings";
```

**Error** 
```
Error: File to import not found or unreadable: bourbon.
>> @import "bourbon";
   ^
```

**Comment by ssosina** [comment]
Well, that's fixed it!. Thanks!

**Comment by whmii** [comment]
@ssosina check out https://github.com/thoughtbot/gulp-bourbon-neat-example

I put together an example repo for an upcoming blogpost that has everything set up.

**Comment by ssosina** [comment]
@whmii Gracias amigo!
