### ISSUE TITLE
cannot override default $_text-inputs-list variable

### ISSUE THREAD

**Issue by hikirsch** [thoughtbot/bourbon#1039]
## Description

the default value for $_text-inputs-list is not the desired setting, we would like to override this to enforce that this only be on input tags. 

we would expect to be able to override this variable. simply by adding ! default to this would solve our issue.

**Comment by tysongach** [comment]
> we would like to override this to enforce that this only be on input tags.

Is this to say that you’re looking to remove `textarea` from that list?

**Comment by hikirsch** [comment]
no - we want to actually make it stricter and only target input's with the [type]'s

**Comment by tysongach** [comment]
I see. I’m curious and want to learn more about the why…would you mind posting the the list that you would set it to?

To do make this change we’d have to revisit our approach. Currently, this is set as a private variable (indicated in the SassDoc, as well as by the `_` prefix), which indicates it should not be used publicly outside of the Bourbon library itself. It also raises the question of whether _all_ of our variables like this should have a `!default` flag, e.g. `$_buttons-list`.

**Comment by hikirsch** [comment]
sure - we literally just prepended input to everything.

$_text-inputs-list: (
  'input[type="color"]',
  'input[type="date"]',
  'input[type="datetime"]',
  'input[type="datetime-local"]',
  'input[type="email"]',
  'input[type="month"]',
  'input[type="number"]',
  'input[type="password"]',
  'input[type="search"]',
  'input[type="tel"]',
  'input[type="text"]',
  'input[type="time"]',
  'input[type="url"]',
  'input[type="week"]',
  'input:not([type])',
  'textarea',
);

**Comment by hikirsch** [comment]
we have custom input components for things like radio's, checkboxes, and textboxes. its mainly an issue for our textbox component.

although we default the type to "text", for other input types like tel and password it becomes more of a problem.

```
<app-textbox type="tel">
   Our Label
</app-textbox>

<app-textbox type="password">
    Password Label
</app-textbox>
```

**Comment by tysongach** [comment]
I wondered if that was the case 😉 

We purposely removed the type selectors in https://github.com/thoughtbot/bourbon/pull/692 to decrease specificity. 

> …it becomes more of a problem

What exactly is the problem?

**Comment by hikirsch** [comment]
our component use an <input /> inside the component, so the style gets applied twice, to the component and the input.

**Comment by tysongach** [comment]
I’m not necessarily opposed to the idea of having `!default` on our variables. Conceptually, though, I think it introduces a UX conundrum to the API. We have other global settings [defined in a `$bourbon` map](http://bourbon.netlify.com/docs/latest/#settings) that people can manipulate. Perhaps a better approach is to get these lists into that global settings object, similar to `global-font-file-formats`.

That being said, I feel like this specific issue is more of a conflict of interest between standardized HTML and custom elements. I’m not familiar with custom elements enough to speak at detail, but could/should the custom element not use the `type` attribute, since that’s already defined in HTML?

**Comment by tysongach** [comment]
Yes, feel free to submit a PR! It’s going to require a fair bit of refactoring, and we’ll want to port `$_buttons-list` at the same time, so to not create a disjointed experience.

**Comment by hikirsch** [comment]
can you let me know if the PR looks good or if there's anything extra i should do? thanks!

**Comment by hikirsch** [comment]
any chance this could get merged?

**Comment by tysongach** [comment]
@hikirsch Hi! Sorry, I haven’t had a chance to work through this yet. It will likely be captured in the 5.1 release.

**Comment by tysongach** [comment]
At this time, we haven’t had a lot of interest in this specific feature, so I’m going to close this along with #1041
