### ISSUE TITLE
I cannot get bourbon to work in my rails app

### ISSUE THREAD

**Issue by alexandratoo** [thoughtbot/bourbon#1044]
I am completely unable to get bourbon to work in my rails app and I have no idea what I am doing wrong. I am using rails 4.2.6, and ruby 2.3.0. My sass is 3.5.3. 
This is in my application.scss file:
`@import 'bourbon';
@import 'neat';
@import 'home_page';`

These are my gems:
`gem 'jquery-rails'

gem 'turbolinks'

gem 'jbuilder', '~> 2.0'

gem 'sdoc', '~> 0.4.0', group: :doc

gem 'bourbon'
gem 'neat'

group :development, :test do
    gem 'byebug'
end

group :development do

  gem 'web-console', '~> 2.0'

 
  gem 'spring'
end
`
This is my config/routes.rb:
`Rails.application.routes.draw do
  root 'home_page#index'
end`
I am getting this message : `Showing /Users/alexandratoo/zoberv1/app/views/layouts/application.html.erb where line #5 raised:

File to import not found or unreadable: bourbon.
Load paths:
  /Users/alexandratoo/zoberv1/app/assets/images
  /Users/alexandratoo/zoberv1/app/assets/javascripts
  /Users/alexandratoo/zoberv1/app/assets/stylesheets
  /Users/alexandratoo/zoberv1/vendor/assets/javascripts
  /Users/alexandratoo/zoberv1/vendor/assets/stylesheets
  /Users/alexandratoo/.rvm/gems/ruby-2.3.0/gems/jquery-rails-4.3.1/vendor/assets/javascripts
  /Users/alexandratoo/.rvm/gems/ruby-2.3.0/gems/coffee-rails-4.1.1/lib/assets/javascripts
  /Users/alexandratoo/.rvm/gems/ruby-2.3.0/gems/turbolinks-source-5.0.3/lib/assets/javascripts`

**Comment by tysongach** [comment]
Hi @alexandratoo!

What are the contents of your `Gemfile.lock`?
