### ISSUE TITLE
Latest gem installs older version of Bourbon

### ISSUE THREAD

**Issue by michaelfich** [thoughtbot/bourbon#1046]
## Description

I am setting up a non-rails project and wanted to use Bourbon (along with Neat and Bitters) however when using the latest version of the Bourbon gem, I expected to get the latest version of Bourbon with it.

The only issue this currently causes is that when I use Bitters, it expects certain variables to be set by Bourbon (ie. `$font-stack-system`) which are not present unless I am able to use the latest version of Bourbon.

For now, I've just set the variables manually to avoid these issues, however I would like to be able to use the latest version of Bourbon if possible.

## Steps to Reproduce

1. Install bourbon via `gem install bourbon`
2. Ensure that the installed gem version is `5.0.0.beta8`
3. Install bourbon stylesheets in a project using `bourbon install --path=path/to/stylesheets
4. Include bourbon in the root stylesheet with `@include 'bourbon/bourbon';`
5. Open `bourbon/_bourbon.scss` and it says in a comment at the top of the file:
```
// Bourbon 4.3.4
// http://bourbon.io
// Copyright 2011-2017 thoughtbot, inc.
// MIT License
```

## Development Environment

- Bourbon version: 5.0.0.beta8
- Platform: OSX
- Link to the code repository: https://github.com/michaelfich/maybenextyear-ember

**Comment by tysongach** [comment]
Hello!

`gem install bourbon` will install the latest stable release. Since 5.0 is still in beta, you'll need to pass a flag: `gem install bourbon --pre`

Hope that helps!
