### ISSUE TITLE
Error with Bourbon 5.0.0 and node-sass

### ISSUE THREAD

**Issue by sheelah** [thoughtbot/bourbon#1049]
## Description

I'm getting a `File to import not found or unreadable: bourbon` error when trying to compile my Sass using Bourbon and node-sass.

## Steps to Reproduce

1. Clone [this repo](https://github.com/sheelah/bourbon-v5-error)
2. Make sure you have node v9.4.0 installed
3. Run `npm i`
4. Run the following to compile Sass: `npm run build-css`
5. Check that you get a compilation error:
```bash
{
  "status": 1,
  "file": "/Users/sbrennan/src/experimental/bourbon-v5-error/src/scss/main.scss",
  "line": 1,
  "column": 1,
  "message": "File to import not found or unreadable: bourbon.\nParent style sheet: /Users/sbrennan/src/experimental/bourbon-v5-error/src/scss/main.scss",
  "formatted": "Error: File to import not found or unreadable: bourbon.\n       Parent style sheet: /Users/sbrennan/src/experimental/bourbon-v5-error/src/scss/main.scss\n        on line 1 of src/scss/main.scss\n>> @import 'bourbon';\n   ^\n"
}
```
6. Downgrade to bourbon v4.3.4 by running `npm install bourbon@4.3.4`
7. Run `npm run build-css` and verify your Sass is compiled successfully

## Development Environment

- Bourbon version: v5.0.0
- Platform: MacOS v10.12.6
- Link to the code repository:  https://github.com/sheelah/bourbon-v5-error

**Comment by Toddses** [comment]
The v5 main bourbon stylesheet is no longer at the same location, so `node_modules/bourbon/app/assets/stylesheets` is not going to find it.

Try `node_modules/bourbon/core`, which is where the `_bourbon.scss` file is located.

**Comment by sheelah** [comment]
![](https://media.giphy.com/media/10o3Um2U3wa4DK/giphy.gif)

Ah I missed that change!  Works now.  Thanks @Toddses 🙌
