### ISSUE TITLE
jekyll/SCSS conversion error: undefined variable 

### ISSUE THREAD

**Issue by caityp** [thoughtbot/bourbon#1050]
## Description

I am trying to build a site with the [centrarium](https://github.com/bencentra/centrarium) theme by running $ bundle exec jekyll serve and getting the following conversion error:

Conversion error: Jekyll::Converters::Scss encountered an error while converting 'css/main.scss':
Undefined variable: "$md-break-point". on line 65
jekyll 3.6.2 | Error: Undefined variable: "$md-break-point". on line 65

The problem is, I can't find the $md-break-point variable in any of my .scss files and don't know what line 65 is referring to.

The main.scss file looks like this:

@charset "utf-8";

// Import partials from sass_dir (defaults to _sass)
// Includes Bourbon, Neat, and Bitters (thanks, thoughtbot!)

@import
"bourbon/bourbon",
"base/base",
"neat/neat",
"layout"
;

## Development Environment

bourbon 5.0.0
bitters 1.8.0
neat 2.1.0

running jekyll 3.6.2 on Windows 10 and trying to keep compatible with GitHub Pages

I'm new to sass/css with jekyll - any thoughts would help! Thanks.
repo: https://github.com/caityp/caityp.github.io

**Comment by tysongach** [comment]
Hi @caityp!

This appears to be an issue with the theme, Jekyll, or tweaks to the theme (maybe a combo of these things!). `$md-break-point` is not a variable that's part of Bourbon, Neat or Bitters. Looks like you've already filed [an issue](https://github.com/bencentra/centrarium/issues/50) over on the theme's repo, which is probably a better suited place for getting the right answer!
