### ISSUE TITLE
Not working from within rails 5.2rc1 engine

### ISSUE THREAD

**Issue by pelted** [thoughtbot/bourbon#1051]
Been chasing this rabbit hole down for a couple of hours, but I've tried both the Rails install method (5.2rc1) and the regular install with `bourbon install` and can not get the bourbon compiling. Its in the asset pipeline, well it is when I had a style to the end of _bourbon.scss  the style shows up in the rendered application.scss but damn if none of the other imports work.

Look around there seems to be an issue that may be related over in the administrate repo. Anyway, not sure what's left t do to use this in a Rails engine.

**Comment by cruelmelody** [comment]
Same boat. Install via Ruby gems and for the life of me couldn't figure out what I was doing wrong... Even tested with some vanilla import files and they compiled ok, but could not get the Bourbon stack to compile via the '@import' method.

**Comment by aekazitt** [comment]
I'm using '~> 3.2.3' and it seems to work. Hope it helps!

**Comment by tysongach** [comment]
Hi! We just released Bourbon v5.0.1. Can you try this version and see if this issue persists?
