### ISSUE TITLE
 Error with font-face mixin using gulp-sass

### ISSUE THREAD

**Issue by sgu1** [thoughtbot/bourbon#1052]
Bourbon V5: Mixin "font-face" does not accept a content block.

I use gulp-sass, not sure if I did something wrong but using the font-face mixin threw me this error: 
events.js:136
      throw er; // Unhandled 'error' event
      ^
Error: ..\_resources\scss\base\_font.scss
Error: Mixin "font-face" does not accept a content block.

Backtrace:
../_resources/scss/base/_font.scss:4
on line 4 of ../_resources/scss/base/_font.scss
@include font-face(
---------^

I just followed the documentation and used this SCSS:

@include font-face(
  "Open Sans",
  "assets/fonts/open-sans/open-sans-v15-latin-regular",
  ("woff2", "woff")
) {
  font-style: normal;
  font-weight: 400;
}

**Comment by tysongach** [comment]
Hi @sgu1!

Here's the source for the `font-face` mixin, which takes a `@content` block on Line 63:

https://github.com/thoughtbot/bourbon/blob/47645b6e5176abe1dcadb130974aadba9d3ae059/core/bourbon/library/_font-face.scss#L49-L65

Can you confirm that you're using Bourbon v5 and not v4 via a package lockfile or some other means? Are you using any other Sass libraries alongside Bourbon, that also has a `font-face` mixin? Perhaps another mixin of the same name is imported later and being used instead, which doesn't support `@content`.

**Comment by sgu1** [comment]
Yes you are right, stupid mistake. Someone installed a older 4.3.4 ruby version on the machine and I forgot to check. Thanks!

**Comment by tysongach** [comment]
No worries! It happens. Glad we figured it out 😉
