### ISSUE TITLE
@size(100%, 10px) not works with percent values in the last version 5.0.0

### ISSUE THREAD

**Issue by yourchoice** [thoughtbot/bourbon#1054]
@size(100%, 10px) not works with percent values in the last version 5.0.0

```
@function _is-length($value) {
...
}
```

Maybe need and another condtion in this function like "`or (str-slice($value + "", -1) == "%")`"

**Comment by Toddses** [comment]
This is working fine for me in 5.0.0

**Comment by tysongach** [comment]
I'm also not able to re-create this issue. Here's a quick CodePen, which compiles fine: https://codepen.io/tysongach/pen/qoOWeN?editors=0100

@yourchoice Is this source code open-source somewhere that I could see? Or can you describe your development environment a bit more? How are you compiling your Sass; do you have other Sass tools/libraries/etc. in your pipeline?

**Comment by yourchoice** [comment]
Seems I resolved. 

Maybe was ruby version. I updated from 2.4 to 2.5.2 and installed again all npm and seems that works.


Thank You
