### ISSUE TITLE
Bourbon not installing from npm

### ISSUE THREAD

**Issue by Foxhoundn** [thoughtbot/bourbon#1056]
Hi,

I have noticed, by using the BlueprintJS library, that any version of Bourbon is not installing from NPM (npm install --save bourbon). NPM says node_modules/bourbon but the lib is nowhere to be found.

This is also the case for any submodules using Bourbon (their node_modules does not contain Bourbon).

Any idea whats up?

Thanks

**Comment by IlCallo** [comment]
Any news? Problem still persists

**Comment by tysongach** [comment]
Hi all,

I’m not able to re-create this, but I also don’t have a real BlueprintJS project to fully test within. That said, I’m able to use both npm and Yarn to install the Bourbon package.

Outside of BlueprintJS, are you both able to install Bourbon?

**Comment by IlCallo** [comment]
In my case it's in an Angular 6 project, even if the problem is the same

**Comment by Foxhoundn** [comment]
@tysongach the problem for me, as stated in the issue, appears when I try to install standalone bourbon

**Comment by tysongach** [comment]
@Foxhoundn You mentioned that the `bourbon` directory does exist in `node_modules` upon running the `install` command but that the “lib is nowhere to be found.” What is output in that `bourbon` directory, anything?

**Comment by Foxhoundn** [comment]
@tysongach there is no bourbon directory, NPM exits the `npm install bourbon` command with `node_modules/bourbon`.

**Comment by tysongach** [comment]
I’m still unable to re-create this, unfortunately, so we’ll have to keep digging. 

- What version of Node are you using?
- What version of npm are you using?
- Can you please paste here into this issue the contents of your terminal session upon running `npm install --save bourbon`?

**Comment by IlCallo** [comment]
I tried re-installing today and the folder now actually exists.
I didn't updated any tool (node or yarn) on my machine, so this seems pretty strange.
