### ISSUE TITLE
Usage on Angular 6

### ISSUE THREAD

**Issue by IlCallo** [thoughtbot/bourbon#1061]
## Description
I installed Bourbon with yarn, I'm trying to use it like written in the docs (`@import "bourbon"`) but this seems not possible.

On Angular 6 I managed to use bourbon with a direct import:

```scss
@import "~bourbon/core/bourbon";
```

I tried to configure the includePaths, which Angular 6 are managed via a JSON file named `angular.json`.
The option where to operate must be set at the project level like
```
angular.json:
projects->
    project-name->
        architect->
            build->
                options->
                    stylePreprocessorOptions->
                        includePaths
```

I tried with a variety of include paths but without success.
By angular documentation, it's not clear where is the 'current directory' when the includePaths option is resolved, I suppose it's either at the root directory of the repo or inside the project folder.

```json
"stylePreprocessorOptions": {
    "includePaths": [
        "node_modules/bourbon",
        "node_modules/bourbon/core",
        "node_modules/bourbon/core/bourbon",
        "../node_modules/bourbon",
        "../node_modules/bourbon/core",
        "../node_modules/bourbon/core/bourbon",
        "../../node_modules/bourbon",
        "../../node_modules/bourbon/core",
        "../../node_modules/bourbon/core/bourbon",
        "../../../node_modules/bourbon",
        "../../../node_modules/bourbon/core",
        "../../../node_modules/bourbon/core/bourbon",
        "../../../../node_modules/bourbon",
        "../../../../node_modules/bourbon/core",
        "../../../../node_modules/bourbon/core/bourbon"
    ]
},
```

When I try using `@import "bourbon"`, I get

```sh
ERROR in <path>/repo/libs/lib-name/src/lib/lib-name/lib-name.component.scss
Module build failed:
var path = require("path");

module.exports = {
  includePaths: [
    path.join(__dirname, "core")
  ]
};

^
      Invalid CSS after "v": expected 1 selector or at-rule, was "var path = require("
      in <path>\repo\node_modules\bourbon\index.js (line 1, column 1)
```

It's obvious that it checks the index.js file instead of directly resolving to the SCSS file and the problems lies there, but I can't use `require("bourbon").includePaths` anywhere because the configuration is done via a JSON file, not a JS one.

Any idea?

**Comment by IlCallo** [comment]
This can be caused by this https://github.com/angular/angular-cli/issues/10535 maybe.
I'll try to upgrade to Angular 6.1 which could resolve the problem and report back.

**Comment by tysongach** [comment]
@IlCallo Any update here?

**Comment by IlCallo** [comment]
Didn't had the chance to update it yet, I'll probably do it in the next weeks, sorry for the delay

**Comment by tysongach** [comment]
@IlCallo I’m going to close for now, but feel free to open the issue when you have more information.

**Comment by bs-thomas** [comment]
Btw, I'm not using Angular, but on React with ES6.  Just a standard webpack configuration, but I have exactly the same error and was able to get away with importing "~bourbon/core/bourbon"

This was rather odd because previously this was not required, and sudden failed after doing an "ncu -u" on my npm project

**Comment by elliottregan** [comment]
Same here. Adding `require("bourbon").includePaths` to `sass-loader`'s `includePaths` option doesn't work. `@import "bourbon/core/bourbon";` does work, though.

I'm using a simple Webpack config. Nothing Angular-related.

**Comment by IlCallo** [comment]
I updated to Angular 6.1 and tryed again.

I used
```json
"stylePreprocessorOptions": {
    "includePaths": [
        "node_modules/bourbon/core"
    ]
},
```
in `angular.json` and

`@import 'bourbon';`

now it works.

**Comment by IlCallo** [comment]
Updated to Angular 6.1.7 and broke again.
I guess I'll just stick to the direct reference...

**Comment by skfa** [comment]
I have webpack4 and sass-loader. It seems `@import 'bourbon'` and then 
 `{
					loader: 'sass-loader',
					options:{
						includePaths: require('bourbon').includePaths,
						sourceMap: true
					}
				}`
inside webpack.config.js doesn't work. It results in error as 
`Module build failed: 
var path = require('path');
^
  Invalid CSS after "v": expected 1 selector or at-rule, was "var path 
  = require("
     in 
  ...node_modules/bourbon/index.js`

However `@import "~bourbon/app/assets/stylesheets/bourbon";` seems to work. I am not entirely sure this is fail safe. What are the alternatives ?
