### ISSUE TITLE
Remove (Ruby) sass dependency and switch to sassc for Bourbon 6.0.0?

### ISSUE THREAD

**Issue by sikachu** [thoughtbot/bourbon#1064]
Hello. 👋 

I was upgrading my dependencies on my project today and noticed that I'm still installing `sass` gem despite I already have `sassc`. After further inspection, it seems like that Bourbon specifies `sass` as a runtime dependency.

Given that [Ruby sass is now deprecated](http://sass.logdown.com/posts/7081811) and they suggested every one to move to `sassc`, I think it's best for Bourbon to stop specifying `sass` as a runtime dependency. 

I think there're two ways we could approach this issue:

* Switch to specify `sassc` as a runtime dependency.
* Remove `sass` from a runtime dependency, and raise an error if neither `sass` nor `sassc` is found.

Please let me know what you preferred. I'd be happy to submit a patch as well.

Thank you.

**Comment by tysongach** [comment]
Hi @sikachu!

Thanks for raising this issue…

I’m leaning towards removing the runtime dependency, because that more closely mimics how we handle Sass on the npm side (we do not list Sass as a dependency in [`package.json`](https://github.com/thoughtbot/bourbon/blob/master/package.json)).

Would love a PR, if you’re up for that!

**Comment by sikachu** [comment]
Sounds good. I'll submit the PR next week.

**Comment by konklone** [comment]
Just noticed this as well, and hoping this gets resolved ahead of the March 26 deadline (where it's formally unmaintained). :+1:

**Comment by sikachu** [comment]
Just want to drop in the note that I should be able to tackle this this week Jan 15-18 (been a bit busy last week due to other priorities.) Sorry for the delay!

**Comment by tysongach** [comment]
Thanks @sikachu! This has been merged as https://github.com/thoughtbot/bourbon/commit/9bedac008832cb779ded2f9298f12a5ebae9e88a.
