### ISSUE TITLE
npm bower deprecation

### ISSUE THREAD

**Issue by Oliv4945** [thoughtbot/bourbon#1065]
On same topic than  #1064, it is said on the readme that npm bower can be used, but here is the warning from NPM:
```
npm WARN deprecated bower@1.8.4: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here:
https://bower.io/blog/2017/how-to-migrate-away-from-bower/
```

**Comment by tysongach** [comment]
👋 Hi!

[Bower](https://bower.io/) announced back in 2017 that they would keep maintaining it, but began recommending that folks use alternative package managers.

We don't have a dependency on Bower, so you won't see deprecation warnings when installing the Bourbon npm package. But it is probably a good time to remove the mention of Bower from our readme. We also have a [`bower.json`](https://github.com/thoughtbot/bourbon/blob/master/bower.json) config file, but I don't think we can remove that until we release 6.0, as it could break the dependency for people.

**Comment by tysongach** [comment]
I've opened two PRs to address this:

- https://github.com/thoughtbot/bourbon/pull/1066 removes the mention of using Bower from the readme
- https://github.com/thoughtbot/bourbon/pull/1067 removes the Bower config file; this PR can't be merged until we release the next major version, 6.0

**Comment by tysongach** [comment]
https://github.com/thoughtbot/bourbon/pull/1067 has been merged.
