### ISSUE TITLE
Sass::SyntaxError: Undefined variable: "$_buttons-list".

### ISSUE THREAD

**Issue by ahmadali7** [thoughtbot/bourbon#1068]
Sass::SyntaxError: Undefined variable: "$_buttons-list".
/home/dev/.rvm/gems/ruby-2.2.7/gems/bourbon-5.1.0/core/bourbon/library/_buttons.scss:27
/home/dev/.rvm/gems/ruby-2.2.7/gems/sass-3.4.25/lib/sass/script/tree/variable.rb:49:in `_perform'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sass-3.4.25/lib/sass/script/tree/node.rb:58:in `perform'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sass-3.4.25/lib/sass/script/tree/funcall.rb:173:in `perform_arg'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sass-3.4.25/lib/sass/script/tree/funcall.rb:124:in `block in _perform'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sass-3.4.25/lib/sass/script/tree/funcall.rb:124:in `each'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sass-3.4.25/lib/sass/script/tree/funcall.rb:124:in `each_with_index'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sass-3.4.25/lib/sass/script/tree/funcall.rb:124:in `each'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sass-3.4.25/lib/sass/script/tree/funcall.rb:124:in `map'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sass-3.4.25/lib/sass/script/tree/funcall.rb:124:in `_perform'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sass-3.4.25/lib/sass/script/tree/node.rb:58:in `perform'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:472:in `visit_variable'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sass-3.4.25/lib/sass/tree/visitors/base.rb:36:in `visit'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:162:in `block in visit'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sass-3.4.25/lib/sass/stack.rb:79:in `block in with_base'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sass-3.4.25/lib/sass/stack.rb:115:in `with_frame'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sass-3.4.25/lib/sass/stack.rb:79:in `with_base'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:162:in `visit'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sass-3.4.25/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sass-3.4.25/lib/sass/tree/visitors/base.rb:52:in `map'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sass-3.4.25/lib/sass/tree/visitors/base.rb:52:in `visit_children'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:171:in `block in visit_children'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:183:in `with_environment'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:170:in `visit_children'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sass-3.4.25/lib/sass/tree/visitors/base.rb:36:in `block in visit'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:190:in `visit_root'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sass-3.4.25/lib/sass/tree/visitors/base.rb:36:in `visit'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:161:in `visit'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:10:in `visit'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sass-3.4.25/lib/sass/tree/root_node.rb:36:in `css_tree'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sass-3.4.25/lib/sass/tree/root_node.rb:20:in `render'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sass-3.4.25/lib/sass/engine.rb:284:in `render'
/home/dev/.rvm/gems/ruby-2.2.7/gems/compass-rails-3.0.2/lib/compass-rails/patches/sass_importer.rb:48:in `evaluate'
/home/dev/.rvm/gems/ruby-2.2.7/gems/tilt-2.0.9/lib/tilt/template.rb:109:in `render'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/legacy_tilt_processor.rb:25:in `call'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `yield'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/bundle.rb:23:in `block in call'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/utils.rb:200:in `dfs'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/bundle.rb:24:in `call'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `yield'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/base.rb:66:in `find_asset'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:142:in `block in find'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `each'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `stat_directory'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:227:in `stat_tree'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:231:in `block in stat_tree'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `each'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `stat_directory'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:227:in `stat_tree'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:231:in `block in stat_tree'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `each'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `stat_directory'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:227:in `stat_tree'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:105:in `each'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:105:in `block in logical_paths'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:104:in `each'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:104:in `logical_paths'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:140:in `find'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:186:in `compile'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-3.7.2/lib/rake/sprocketstask.rb:147:in `with_logger'
/home/dev/.rvm/gems/ruby-2.2.7/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
Tasks: TOP => assets:precompile

**Comment by tysongach** [comment]
@ahmadali7 Can you please provide more context around this issue? Information like the platform you're working within, how you installed Bourbon, and how to re-create this issue will allow us to better help you. Thanks!

**Comment by RandieM** [comment]
For what it's worth, I had the same problem and had to remove ` *= require_tree .` from my application.scss. I suppose that this was messing with the order that the project's CSS partials were imported.
