### ISSUE TITLE
Suggestion: reset

### ISSUE THREAD

**Issue by FDiskas** [thoughtbot/bourbon#1077]
I know that this is related to #144 but since it's closed I would like to discuss more about that.
bourbon has allot nice mixins and couple of them already has like reset functionality.
Could we have another mixin with global reset like normalize?

**Comment by Toddses** [comment]
Why not just use normalize for your global reset? It integrates into projects pretty easily..

**Comment by FDiskas** [comment]
Would be nice to add only needed resets. Mixin could do that

**Comment by Toddses** [comment]
I see, that does make sense. I suppose the argument would be, even if you don't use buttons, keeping the normalization around isn't hurting all that much.. pretty minute impact on filesize and efficiency. But if you're into super efficient bundles I could see some value in it. Sounds like it could be a nice mixin library on its own..

**Comment by tysongach** [comment]
At this time, we’re interested in maintaining a reset as part of Bourbon.
