### ISSUE TITLE
can't resolve`bourbon`

### ISSUE THREAD

**Issue by FDiskas** [thoughtbot/bourbon#1078]
Some bundlers like `parcel` can't resolve`bourbon` when included in scss because of the `main` entry in `package.json` file. Please change the main entry point to same path as it is in `style` = `"core/_bourbon.scss",` :notes:

No result in scss looks like
```scss
@import 'normalize.css';
@import '~node_modules/bourbon/core/bourbon';
```
but could be like
```scss
@import 'normalize.css';
@import 'bourbon';
```

_Originally posted by @FDiskas in https://github.com/thoughtbot/bourbon/issues/802#issuecomment-510624302_
Reference: https://github.com/parcel-bundler/parcel/issues/3205

**Comment by tysongach** [comment]
I’ve not used [Parcel](https://parceljs.org/) extensively, but from what I gather it’s a bundler that wraps _other_ tools and Parcel itself is not responsible for the compiling of Sass. According to their [SCSS documentation](https://parceljs.org/scss.html), it appears that you can use Parcel with Dart Sass (the `sass` package on npm) or node-sass (the `node-sass` on package npm). Can you clarify which one you are using?

Also, have you tried using [eyeglass](https://github.com/linkedin/eyeglass) and following our instructions in the readme for [Installing with npm and using a Node-based asset pipeline](https://github.com/thoughtbot/bourbon#installing-with-npm-and-using-a-node-based-asset-pipeline)?

**Comment by FDiskas** [comment]
Demo repo https://github.com/FDiskas/parcel-bug

**Comment by enatario** [comment]
Closing this [as we're archiving the project](https://github.com/thoughtbot/bourbon/pull/1133).
