### ISSUE TITLE
Documentation menu issue

### ISSUE THREAD

**Issue by FDiskas** [thoughtbot/bourbon#1079]
https://www.bourbon.io/docs/latest/#stylelint-disable-order-properties-alphabetical-order-mixin-overflow-wrap-wrap-break-word

![StaticShot_11-07-2019_22-42-24](https://user-images.githubusercontent.com/468006/61080205-31f2f380-a42d-11e9-86e8-8dc6314a3036.png)

**Comment by tysongach** [comment]
Thanks for reporting this issue! All fixed.
