### ISSUE TITLE
_is-color validator fails on CSS Custom Properties

### ISSUE THREAD

**Issue by GoOz** [thoughtbot/bourbon#1103]
## Description

I would like to use the `triangle()` mixin with a CSS Custom Property as the color parameter but it obviously fails because the `_is-color` validator doesn't recognize the custom property as a color, which seems legit, but I think it should accept in some way CSS Custom Properties as they are more and more used, specially within a *themable* context.

## Steps to Reproduce

```scss
.element {
  @include triangle($arrow-direction, $arrow-width, $arrow-height, var(--my-triangle-color));
}
```

- Bourbon version: 7
- Platform: any

**Comment by enatario** [comment]
Closing this [as we're archiving the project](https://github.com/thoughtbot/bourbon/pull/1133).
