### ISSUE TITLE
Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

### ISSUE THREAD

**Issue by dkjensen** [thoughtbot/bourbon#1106]
## Description

Using SASS >= 1.33.0 produces the following warnings when compiling:

```
: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($v1, $ratio)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
113 │         $v1: ($v1 / $ratio);
    │               ^^^^^^^^^^^^
    ╵
    node_modules\bourbon\core\bourbon\library\_modular-scale.scss 113:15  modular-scale()
    resources\scss\settings\_typography.scss 48:24                        @import
    resources\scss\settings\__index.scss 13:9                             @import
    resources\scss\main.scss 16:9                                         root stylesheet

: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($value, $value * 0 + 1)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
16 │   @return ($value / ($value * 0 + 1));
   │            ^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules\bourbon\core\bourbon\library\_strip-unit.scss 16:12  strip-unit()
    resources\scss\elements\_typography.scss 20:33                    @content
    resources\scss\tools\_mixins.scss 71:3                            mq()
    resources\scss\elements\_typography.scss 19:2                     @import
    resources\scss\elements\__index.scss 13:9                         @import
    resources\scss\main.scss 19:9                                     root stylesheet

: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($width, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
70 │       border-width: $height ($width / 2) 0;
   │                              ^^^^^^^^^^
   ╵
    node_modules\bourbon\core\bourbon\library\_triangle.scss 70:30  triangle()
    resources\scss\components\_sub-menu.scss 92:4                   @import
    resources\scss\components\__index.scss 19:9                     @import
    resources\scss\main.scss 21:9                                   root stylesheet

: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($width, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
58 │       border-width: 0 ($width / 2) $height;
   │                        ^^^^^^^^^^
   ╵
    node_modules\bourbon\core\bourbon\library\_triangle.scss 58:24  triangle()
    resources\scss\components\_sub-menu.scss 99:5                   @import
    resources\scss\components\__index.scss 19:9                     @import
    resources\scss\main.scss 21:9                                   root stylesheet
```

## Development Environment

- Bourbon version: 7.0.0
- Webpack version: 5.38.1

**Comment by chamby** [comment]
A [migration tool](https://sass-lang.com/documentation/breaking-changes/slash-div#automatic-migration) is available

**Comment by Philip-Carneiro** [comment]
@cpjmcquillan @cpytel @dimanyc  @edwardloveall @FerPerales @jferris @joshuaclayton @mike-burns @nickcharlton @odlp @samkap @setphen @tjvc @vendelal 
Hi Guys, since appear no response via emails and no one in the main group give any response about this issue, I'm tagging everyone that have the name listed in @thoughtbot.
There is any chance of an minor release with the fixes merged in this change?
This repository is abandoned? 

Thank you guys

**Comment by jclusso** [comment]
Honestly, it's frustrating that this repo is totally ignored. I made a pull request to fix this super simple thing 5 months ago and it took months to even get someone to acknowledge it. 

If it's not going to be maintained that's fine, but since thoughtbot is a known company in this space, I think people (at least I did) will assume it's being maintained. Put a banner that says it's looking for maintainers so people know that this is not going to be updated at this time. You guys have 9k+ stars so I imagine there are a good number of people  using it. Additionally, your contributation guide specifically states this which is simply not true and mislead me to believe this was maintained as well.

> As a contributor, submitting a pull request or opening an issue, you can expect an initial response from a maintainer within two weeks. The maintainers cannot guarantee that we will accept all feature requests, and may fix bugs in ways other than how the contributor suggests. You are expected to abide by our [code of conduct](https://thoughtbot.com/open-source-code-of-conduct).

**Comment by nickcharlton** [comment]
Hello!

I'm not currently sure what the status of Bourbon is, but I've asked around to see if anyone is keen on picking this up and I'm sure we'll get back to you soon.

Unfortunately, such is the nature of maintaining a lot of different projects whilst running a consultancy that things occasionally fall through the cracks, especially as projects always begin as someone's personal endeavour at thoughtbot.

**Comment by enatario** [comment]
Yeah sorry. It's been a bit hectic over here. [Release is all set](https://github.com/thoughtbot/bourbon/releases/tag/v7.1.0).

**Comment by sKopheK** [comment]
hi, any update on this?

**Comment by joepagan** [comment]
Hi, what exactly was the reason for the revert? Do the changes not work for apps using node-sass?

These output messages appear to contribute to painfully slow build times where builds are done inside a node containers using dart sass. 

Anyone with an m1 macbook [cannot build with node-sass at the current time](https://github.com/sass/node-sass/issues/3033) either which makes this frustrating

Would be helpful if there was a reference to this in the readme so m1 users know they can use 7.1.

Would be nice to get a branch or an 8.0alpha release or something if there are future updates we could benefit from, but given how frequently this repo is updated make just point them people 7.1? 🤷

**Comment by enatario** [comment]
Closing this [as we're archiving the project](https://github.com/thoughtbot/bourbon/pull/1133).
