### ISSUE TITLE
Document compatibility with Ruby Sass/gh-pages

### ISSUE THREAD

**Issue by dabrahams** [thoughtbot/bourbon#1108]
If #1107 is going to be merged, presumably it means compatibility with Ruby Sass (and thus stock github pages) has been dropped? Which is the latest version that will work with Ruby Sass?  Can you please make that information prominently visible?

Thanks!

**Comment by enatario** [comment]
Closing this [as we're archiving the project](https://github.com/thoughtbot/bourbon/pull/1133).
