### ISSUE TITLE
Recommendation: math.div($width, 2) or calc($width / 2)

### ISSUE THREAD

**Issue by agragregra** [thoughtbot/bourbon#1120]
Recommendation: math.div($width, 2) or calc($width / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
58 │       border-width: 0 ($width / 2) $height;
   │                        ^^^^^^^^^^
   ╵
    node_modules/bourbon/core/bourbon/library/_triangle.scss 58:24  triangle()
    sass/main.sass 474:4

**Comment by enatario** [comment]
Closing this [as we're archiving the project](https://github.com/thoughtbot/bourbon/pull/1133).
