### ISSUE TITLE
N-US

### ISSUE THREAD

**Issue by ragavindia** [thoughtbot/bourbon#1122]
I created mixins for the new flex-box spec. They live in the new-flex-box branch: https://github.com/thoughtbot/bourbon/blob/new-flex-box/app/assets/stylesheets/css3/_flex-box.scss

Though, because the new spec is approaching Candidate Recommendation stage, browser vendors are encouraged to drop vendor prefixes at CR stage. Because of this, these mixins may never actually get introduced into Bourbon master.

As far as I can tell, these mixins only have effect on webkit right now. As of Aug 30th, when I tested mozilla nightly, new flexbox has yet to be implemented.

New flex box is worth playing around with though!

_Originally posted by @plapier in https://github.com/thoughtbot/bourbon/issues/115#issuecomment-8301763_

**Comment by ragavindia** [comment]
H

**Comment by ragavindia** [comment]
No Parts

**Comment by enatario** [comment]
Closing this [as we're archiving the project](https://github.com/thoughtbot/bourbon/pull/1133).
