### ISSUE TITLE
Changelog missing new versions and mixins that were removed

### ISSUE THREAD

**Issue by thestelz** [thoughtbot/bourbon#1132]
While updating a legacy app from [`4.3.4`](https://github.com/thoughtbot/bourbon/blob/master/CHANGELOG.md#434---2017-04-01) to `7.3.0`, I noticed a few things:

1. The mixins `flex-grow` and `flex-flow` were missing, but they aren't listed on the changelog anywhere nor the [release](https://github.com/thoughtbot/bourbon/releases/tag/v5.0.0.alpha.0). I would open up a PR, but not sure when those mixins where removed (I'm guessing `v5`).
2. The changelog is missing versions `7.1`, `7.2`, and `7.3` (I know they are listed via [releases](https://github.com/thoughtbot/bourbon/releases?page=1), but figured that the changelog should keep up with those. I would open a PR to fix that as well, but not sure how the descriptions should be listed (even if it is just a copy-paste of the release notes).

Not sure if this is the right channel for this kind of stuff. If not, please point me in the right direction. I can also put in PR(s) for the above issues, I'll just need some direction on what you guys want.

Thanks!

**Comment by tysongach** [comment]
> The mixins `flex-grow` and `flex-flow` were missing, but they aren't listed on the changelog anywhere nor the [release](https://github.com/thoughtbot/bourbon/releases/tag/v5.0.0.alpha.0). I would open up a PR, but not sure when those mixins where removed (I'm guessing `v5`).

`flex-grow` and `flex-flow` were mixins that added vendor prefixes and the `v5.0.0.alpha.0` release notes mention “All vendor prefixing mixins have been removed.“ Those two would be included in that list. Perhaps all of them should have been spelled out, but me nine years ago didn’t think to do that!

I believe you should be seeing deprecation warnings for those two mixins in your Sass output when running `v4.3.4`:

https://github.com/thoughtbot/bourbon/blob/8dd49b1015b52d7e39a85c046b6010f45179ac57/app/assets/stylesheets/css3/_flex-box.scss#L212-L213

https://github.com/thoughtbot/bourbon/blob/8dd49b1015b52d7e39a85c046b6010f45179ac57/app/assets/stylesheets/css3/_flex-box.scss#L189-L190

Try searching your logs for `[Bourbon] [Deprecation]`.

> The changelog is missing versions `7.1`, `7.2`, and `7.3` (I know they are listed via [releases](https://github.com/thoughtbot/bourbon/releases?page=1), but figured that the changelog should keep up with those. I would open a PR to fix that as well, but not sure how the descriptions should be listed (even if it is just a copy-paste of the release notes).

I see those entries here: https://github.com/thoughtbot/bourbon/blob/7f2ceb27756f668d99f3a678bc050a1af7d6b467/CHANGELOG.md

**Comment by thestelz** [comment]
@tysongach Thanks for the quick reply!

> `flex-grow` and `flex-flow` were mixins that added vendor prefixes and the `v5.0.0.alpha.0` release notes mention “All vendor prefixing mixins have been removed.“ Those two would be included in that list. Perhaps all of them should have been spelled out, but me nine years ago didn’t think to do that!

Ah, since I saw a list I was thinking that only those were removed an any others would give a warning. That is my fault for misunderstanding that. Haha ya, I didn't even realize how long ago it has been since that release. As you can tell we have a nice old legacy app on our hands.

> I believe you should be seeing deprecation warnings for those two mixins in your Sass output when running `v4.3.4`

I don't recall ever seeing deprecation warnings during the precompile process, but now I've got it using `7.3.0`. I was just wanting to bring it to your guys attention for others coming along, but it was my mistake.

> I see those entries here: https://github.com/thoughtbot/bourbon/blob/7f2ceb27756f668d99f3a678bc050a1af7d6b467/CHANGELOG.md

That's weird, I don't see them via `master` https://github.com/thoughtbot/bourbon/blob/master/CHANGELOG.md#change-log, but I'm just now seeing there is a `main` branch. Switching to the `main` branch showed everything.

It appears on your guys' main site, it links to `master` and not `main`:

[ruby gems](https://rubygems.org/gems/bourbon) -> [Homepage](https://www.bourbon.io/) -> [Change Log](https://github.com/thoughtbot/bourbon/blob/master/CHANGELOG.md).

**Comment by tysongach** [comment]
Yeah, it seems like `master` might have gotten re-created on accident around 2022: https://github.com/thoughtbot/bourbon/compare/master...main

The [website](https://github.com/thoughtbot/bourbon.io) should get updated to use `main`, but I also think deleting `master` here might automatically introduce a redirect on GitHub’s side…

I haven’t been associated with this project since 2020, but the thoughtbot team appears to still be accepting and merging some PRs, if you want to submit a fix.

**Comment by thestelz** [comment]
@tysongach Thanks for your help & feedback!
