### ISSUE TITLE
File to import not found or unreadable: bourbon.

### ISSUE THREAD

**Issue by pruett** [thoughtbot/bourbon#120]
Attempting to install neat framework in Rails application with `@import 'bourbon'` and `@import 'neat'` in `application.sass` produces

**File to import not found or unreadable: bourbon.**

Using the following gems:

`rails (3.2.8)`
`neat (0.4.2)`
`bourbon (2.1.1)`
`sass (3.2.1)`
`sass-rails (3.2.5)`

**Comment by ales82** [comment]
Bourbon must be on the same directory level with files wich you compile with sass:
Ex:  scss/index.scss 
then bourbone must be instaled in scss directory wich you compile with : $ sass ---watch scss:css

**Comment by mimoYmima** [comment]
thanks @ales82 I had my bourbon.scss file moved which was causing the problem!
