### ISSUE TITLE
Error on Line 65: Invalid US-ASCII character \xE2

### ISSUE THREAD

**Issue by geebru** [thoughtbot/bourbon#224]
Started a new project today and went through the install process for Bourbon/Neat with no errors but when I start 'sass --watch' I get the error mentioned. Any ideas?

I haven't touched any files yet, this is just straight out of the box.

**Comment by bhaskar0y0** [comment]
I added @charset "UTF-8";

And it worked for me.

Sass 3.4.13 (Selective Steve)

**Comment by daclubb** [comment]
@stringertheory It is in your root project folder.

**Comment by treki** [comment]
thanks

**Comment by lora-palmer** [comment]
blah blah blah 👎
