### ISSUE TITLE
Rails 4 with font-face

### ISSUE THREAD

**Issue by nybblr** [thoughtbot/bourbon#239]
Using Rails 4 and Bourbon, and some issues have reared their ugly heads. I'm using the font-face mixin:

``` sass
+font-face(OpenSans, opensans-regular, normal, normal, true)
```

However, the path generated in the stylesheet is /fonts/opensans-regular... but Rails 4 claims it doesn't exist. I have put all my font files under app/assets/fonts and added:

``` ruby
    config.assets.paths << Rails.root.join('app', 'assets', 'fonts')
```

to my application.rb. It seems the correct path in rails 4 is now /assets/opensans-regular. Is it possible to redirect fonts to assets, or should Bourbon be using asset-path in the font-face helper instead? Would this break Rails 3 compatibility?
~ Jonathan

**Comment by elizabrock** [comment]
@plapier Thanks for the excellent how-to!  It's remains super useful!

**Comment by lifeiscontent** [comment]
@plapier I think this issue still exists in Proteus for Middleman. Any ideas how to fix?

**Comment by akashdevaraju** [comment]
@plapier Thanks a bunch! This worked for me today.
