### ISSUE TITLE
hide-text doesn't hide text ? 

### ISSUE THREAD

**Issue by pyronaur** [thoughtbot/bourbon#412]
I'm not receiving any errors when using the Mixin, but it doesn't seem to work either. 

Sass 3.3.6 (Maptastic Maple)
Bourbon 4.0.1

I just upgraded from Bourbon 3.2.X  so I'm guessing that something has changed since ? Do I have to roll my own hiding mixin now ? 

It's compiling now to:

```
.belly-button {
  overflow: hidden; }
  .belly-button:before {
    content: "";
    display: block;
    width: 0;
    height: 100%; }
```
1. .selector:pseudo is obsolete CSS2. Please use CSS3 instead.
2. What the hack is that ? Where did the normal hide-text method go ?

**Comment by gosukiwi** [comment]
Looks like it doesn't work with the `a` element. Actually I had to wrap the element which uses the `hide-text` mixin inside an `a` tag.

**Comment by waltercruz** [comment]
AFAIK... a display inline:block solves this.

**Comment by tysongach** [comment]
`hide-text` has gone through [lots of refinements](https://github.com/thoughtbot/bourbon/commits/master/app/assets/stylesheets/addons/_hide-text.scss), so these issues are highly dependent on the version of Bourbon you are using.

Certain elements will indeed need to be made block-level for this to work.

**Comment by gosukiwi** [comment]
I see. Tried adding `display: inline-block` and it works. Thanks for the support :smile:

**Comment by joshuaogle** [comment]
There was a PR to update the docs, but I was late in getting it merged. [Hope it helps in the future](http://bourbon.io/docs/#hide-text)
