### ISSUE TITLE
Have a transition-transform mixin

### ISSUE THREAD

**Issue by grandecomplex** [thoughtbot/bourbon#415]
Hi there,

I have a mixin I use in projects that I find very useful. I'm happy to pull request the following:

@mixin transition-transform($time, $ease, $more) {
  -webkit-transition: -webkit-transform $time $ease, $more;
  -moz-transition: -moz-transform $time $ease, $more;
  -ie-transition: -ie-transform $time $ease, $more;
  -o-transition: -o-transform $time $ease, $more;
  transition: transform $time $ease, $more;
}

Allows me to do transition transform and with other stuff.

**Comment by merqurio** [comment]
I tried @plapier's solution, using bourbons mixins but the result is not the one i would expect..
```scss
@include transition(transform 0.2s, background-color 0.5s);
```
compiles to:
```css
-webkit-transition: -webkit-transform, background-color;
-webkit-transition: background-color, -webkit-transform;
transition: background-color, -webkit-transform;
transition: transform, background-color;
transition: transform, background-color, -webkit-transform;
```
I was expecting:
```css
-webkit-transition: -webkit-transform 0.2s, background-color 0.5s;
-moz-transition: -moz-transform 0.2s, background-color 0.5s;
transition: transform 0.2s, background-color 0.5s;
```

Maybe I'm the one doing something wrong, note sure :v: 
I'm using `node-sass@3.4.2` and Bourbon `"version": "4.2.6"`

**Comment by tysongach** [comment]
@merqurio The `-moz-` prefix on `transition` hasn’t been needed since Firebox v16: http://caniuse.com/#feat=css-transitions

Support might be good enough all around, that no prefixes are needed; I would double check that first and remove this mixin all-together if prefixes are indeed not needed. `transform` also has pretty great support these days: http://caniuse.com/#feat=transforms2d

**Comment by merqurio** [comment]
ok, great :+1: , seen that the support is so abroud I think i'll just not use the mixin. Thanks @tysongach !!!
