### ISSUE TITLE
Do we want mixins for -webkit prefixes for break-before, break-after, break-inside ?

### ISSUE THREAD

**Issue by gkop** [thoughtbot/bourbon#441]
We already have the `@columns` mixin that is needed for these guys.

cf. http://caniuse.com/#feat=multicolumn

Here's an example which uses the mixins provided by Compass - http://codepen.io/cimmanon/pen/tcyHv

We could call them `@break-*` or `@column-break-*`

Just checking if there is a reason we don't have them here in Bourbon yet...

**Comment by xpepermint** [comment]
+1 for `break-inside: avoid`

**Comment by tysongach** [comment]
I’m going to close this as the [next major version of Bourbon](https://github.com/thoughtbot/bourbon/issues/702) will not include prefixing mixins.
