### ISSUE TITLE
Import mixins/functions individually

### ISSUE THREAD

**Issue by UltCombo** [thoughtbot/bourbon#460]
Hello,

I just started checking this awesome Sass library, but it seems to lack the possibility to import mixins/functions on demand.

Bourbon is deemed as more lightweight than Compass, however being forced to import the whole library just to use a single mixin is a no go for performance -- Bourbon adds around 33% to my build time.

Compass allows importing specific modules, I'd like to see something similar in Bourbon.

For example, I'd expect importing `bourbon/css3/linear-gradient` would make the `linear-gradient` mixin available, but importing it this way does not work as it lacks dependency functions (`_linear-positions-parser`).

<hr>

## Implementation notes

Importing all dependencies in each mixin would re-define the functions, resulting in an even greater performance penalty when importing the whole library, and I'm not sure if it would cause any side effects.

Using the [`import-once`](https://github.com/Compass/compass/blob/master/import-once/README.md) gem would remove the re-importing overhead, but could also generate different output for the user code. I'm not sure if there's a better way to handle the dependency system until this [Sass issue](https://github.com/sass/sass/issues/139) is resolved.

Thoughts?

**Comment by aeberlin** [comment]
This would be great, because these new deprecations are going to drive me insane and force me away from bourbon in the long run.

**Comment by tysongach** [comment]
I’m going to close this because Sass 4 is expected to introduce a native module system and will be much more robust than what we can do on our own.

The system is still being designed, but you can read more about it here: https://github.com/sass/proposal.module-system
