### ISSUE TITLE
linear-gradient cannot include `transparent`

### ISSUE THREAD

**Issue by pathawks** [thoughtbot/bourbon#498]
I am trying to fade from white to transparent, but because bourbon sets the background color to white, the whole background is white.

````sass
@include linear-gradient(white 0px, transparent 100px);
````

This produces the following CSS:

````css
background-color:#fff;
background-image:-webkit-linear-gradient(#fff 0px,transparent 100px);
background-image:linear-gradient(#fff 0px,transparent 100px);
````

The fallback `background-color` prevents any part of the background from being transparent.

bourbon does check to see if the fallback color is transparent, but it only checks the *first* color step.

````sass
  // Set $G1 as the default fallback color
  $fallback-color: nth($G1, 1);

  // If $fallback is a color use that color as the fallback color
  @if (type-of($fallback) == color) or ($fallback == "transparent") {
    $fallback-color: $fallback;
  }
````

**Comment by alanguir** [comment]
You can avoid the $fallback variable by specifying values backwards and using a directional keyword. This lets "transparent" becomes the fallback by virtue of being the first value given:
```
// No gradient, just white
@include linear-gradient(white 0px, transparent 100px);

// Gradient w/ transparency on right, white on left
@include linear-gradient(to left, transparent , white);
```

**Comment by tysongach** [comment]
Don’s comment above should resolve this original issue of fading from `white` to `transparent`:

```scss
@include linear-gradient(white 0px, transparent 100px, $fallback: transparent);
```

Here’s a CodePen: http://codepen.io/tysongach/pen/bdEwvV

It’s also worth noting that unless you need IE9 support, vendor prefixing is [no longer needed](http://caniuse.com/#feat=css-gradients), and you can go with regular ’ol CSS:

```css
background: linear-gradient(180deg, white, transparent);
```
