### ISSUE TITLE
Update "Who is using it?" section of landing page

### ISSUE THREAD

**Issue by kylefiedler** [thoughtbot/bourbon#502]
Update with:
- http://mailboxapp.com
- http://carousel.com
- http://playbook.cio.gov/

**Comment by ZLevine** [comment]
If you're looking for another "diverse" example site, we built a large-scale how-to site using Bourbon :) howchoo.com

We use a bunch of neat technologies on the site (and wrote guides for many of them along the way!) A few notable ones:

Bourbon Neat
Django
Redis
Postgres
Backbone
jQuery

**Comment by tysongach** [comment]
Closing for now…we can add this over on the new website repo later if we feel it's still actionable: https://github.com/thoughtbot/bourbon.io/issues
