### ISSUE TITLE
what value to use for 3.2.3 position mixin to ignore? 

### ISSUE THREAD

**Issue by benpptung** [thoughtbot/bourbon#508]
I am using node-sass, so I can only choose 3.2.3.

I've noticed that mixin `@include position(0px null null 100px)` doesn’t work.

It will raise the error:

"position:21: error: argument `$number` of `unitless($number)` must be a number"

In addition, I’ve tried `null`, `false`. It will raise error. If I try `0`, it will put `0` into the CSS like `top: 0`;

I am wondering what value I can use to make position() to ignore the value like the current doc? The current doc is: `@include position(relative, 0px null null 100px);`

**Comment by tysongach** [comment]
[Bourbon gem v3.2.4](https://rubygems.org/gems/bourbon/versions/3.2.4) is up.
