### ISSUE TITLE
linear-gradient requires position when first color stop has a defined stop point

### ISSUE THREAD

**Issue by jessepearson** [thoughtbot/bourbon#514]
When inputting the below code, you receive the given output that contains "to ," within it, breaking the layout on some browsers. 

code:

```scss
@include background-image( linear-gradient( #6c9f57 0px, #6c9f57 21px, #61914e 22px, #61914e 100% ) );
```

output:

```scss
background-image: -webkit-linear-gradient(#6c9f57 0px, #6c9f57 21px, #61914e 22px, #61914e 100%);
background-image: linear-gradient(to   , #6c9f57 21px, #61914e 22px, #61914e 100%); } }
```

However, if you include a position (direction), the output is as expected.

code:

```scss
@include background-image( linear-gradient( to bottom, #6c9f57 0px, #6c9f57 21px, #61914e 22px, #61914e 100% ) );
```

output:

```scss
background-image: -webkit-linear-gradient( top , #6c9f57 0px, #6c9f57 21px, #61914e 22px, #61914e 100%);
background-image: linear-gradient(to bottom, #6c9f57 0px, #6c9f57 21px, #61914e 22px, #61914e 100%); } }
```

**Comment by tysongach** [comment]
@jessepearson Still an open issue? Are you able to use the `linear-gradient` mixin to solve your needs?

**Comment by jessepearson** [comment]
Not that I know of, but I believe it may have been a documentation discrepancy that caused user error. I also have moved away from using the bourbon mixins and now use a autoprefixer for projects.
