### ISSUE TITLE
mixin for `box-shadow` is missing

### ISSUE THREAD

**Issue by thany** [thoughtbot/bourbon#518]
As the title says. Needs vendor prefixes `-webkit-` and `-moz-` for older browsers.

**Comment by dmitryvmin** [comment]
Nothing wrong with using Bourbon and Compass together. :)

**Comment by thany** [comment]
Yes there is, because there is not way to confidently tell which mixin it uses when one exist bothing Compass and in Bourbon.

So what other mixin are going to be removed? And how much of my code is going to stop working when that happens?.. Like I said, there is *no overhead* in keeping old mixins around. If you absolutely must, just let it output the unprefixed properties only. So it won't break existing code.

**Comment by silky** [comment]
agreed @thany 

yes, this issue is coming back 6 years later!

:(
