### ISSUE TITLE
Improve Flexbox documentation

### ISSUE THREAD

**Issue by designermonkey** [thoughtbot/bourbon#524]
Is there any chance that we could have better documentation for the myriad of flex mixins available?

The docs are usually quite good in showing examples of use and output, but the flex docs really let the side down with a link to 'View all flexbox mixins'.

**Comment by tysongach** [comment]
I’m going to close this as the [next major version of Bourbon](https://github.com/thoughtbot/bourbon/issues/702) will remove these flexbox mixins.
