### ISSUE TITLE
Mixing missing (background-size)

### ISSUE THREAD

**Issue by 0xbaigorria** [thoughtbot/bourbon#536]
Hi! I know it's not extremely necessary now a days, but I think it doesn't bother to have it for a couple more years.

I don't know how to add it to the repo so that everyone can have the mixing, but I think you should add the `background-size` mixin.

```
@mixin background-size($all) {
    -webkit-background-size: $all;
    -moz-background-size: $all;
    background-size: $all;
}
```

Thanks!

**Comment by zrisher** [comment]
Having this issue around as a reason for why it isn't available was pretty helpful. It might be nice to just have a small section of the docks on "methods you might be looking for but aren't included for a reason."
