### ISSUE TITLE
File to import not found or unreadable: bourbon

### ISSUE THREAD

**Issue by neo-art** [thoughtbot/bourbon#537]
Hi,

Trying to import bourbon/neat/bitters to Hugo static site generator (https://github.com/spf13/hugo)
but for some reason I am getting **File to import not found or unreadable: bourbon**
Maybe someone can advise what's wrong here (paths, directory architecture etc.?)

Thank you in advance.

``` html
sass src/stylesheets/all.css.scss static/css/all.css
Error: File to import not found or unreadable: bourbon.
       Load path: /home/user/PROJECTS/project-hugo
        on line 3 of src/stylesheets/all.css.scss

bundle show bourbon
/usr/lib/ruby/gems/2.1.0/gems/bourbon-4.0.2
```

**Gemfile**:

``` html
source 'https://rubygems.org'

gem 'sass'
gem 'bitters'
gem 'bourbon'
gem 'neat'
```

My directory architecture:

``` html
PROJECT
- archetypes
- content
- layouts
- public
- src
 -- stylesheets
  --- base
  all.css.scss
- static
 -- css
 all.css
config.yaml
Gemfile
```

**Update**: All.css.scss content

``` css
  @charset "utf-8";

  @import "bourbon";
  @import "bitters/bitters";   /* Bitters needs to be imported before Neat */
  @import "neat";
```

**Comment by andela-sdamian** [comment]
@neo-art next time can you be more kind to share what worked for you. This can also help people having the same problem. Saying what works for you without sharing is not Open Source. Thanks.
