### ISSUE TITLE
Documentation translation

### ISSUE THREAD

**Issue by jamadam** [thoughtbot/bourbon#597]
Hi.

Do you have any plan to accept contribution in documentation translation?
If any, I might be able to work on Japanese version.

Or, if permitted, I would translate the source, build with jekyll and put it on
somewhere public as an unofficial documentaion. Is it acceptable?

Here shows how translation will look like.

https://github.com/jamadam/bourbon/commit/e73f706645dcf2f22fd33b5531c15bc1b6d8140b

**Comment by tysongach** [comment]
At this time, we have no translation system in place. We are currently porting the documentation to a new system and will look into translations in the future.

For now, feel free to fork the docs and translate yourself.

**Comment by jamadam** [comment]
Thanks!
