### ISSUE TITLE
Bourbon CSS error using Scout compiler on Windows

### ISSUE THREAD

**Issue by emage** [thoughtbot/bourbon#605]
I am just starting to get into Sass.  I recently installed Ruby ( from http://rubyinstaller.org/ ) and Bourbon on my window machine and using Scout (from http://mhs.github.io/scout-app/) to compile.  Everything is going well until i import the bourbon files using at the top of my main.css:

@import "bourbon/bourbon";

I am not sure if its the Scout Compile output error or Bourbon.

Compile Error:

Common error is the Invalid CSS:

>>> Change detected at 16:48:33 to: main.scss
error main.scss (Line 22 of _font-source-declaration.scss: Invalid CSS after " eot": expected ")", was ": $font-url +...")
overwrite main.css 
>>> Change detected at 16:50:46 to: bourbon/_bourbon.scss
error main.scss (Line 21 of _linear-angle-parser.scss: Invalid CSS after " webkit-image": expected ")", was ": -webkit- + $p...")
overwrite main.css 
>>> Change detected at 16:51:01 to: main.scss
error main.scss (Line 21 of _linear-angle-parser.scss: Invalid CSS after " webkit-image": expected ")", was ": -webkit- + $p...")
identical main.css 

I went into the bourbon.scss to remove the said error imported file, it just goes to the next import file and output the same error.

My versions:
 bourbon version: 4.1.0
ruby installer version 2.2.3
sass versiion 3.4.9

Any thought or suggestion?

Thanks

**Comment by elomatreb** [comment]
Scout seems to be [using Sass 3.2.1](https://github.com/mhs/scout-app/blob/master/Gemfile#L7), which is not compatible with Bourbon 4. 

You could downgrade your Bourbon to 3.x (See [this section](https://github.com/thoughtbot/bourbon#installing-older-versions-of-bourbon) in the README) or use the command-line interface of sass.

**Comment by tysongach** [comment]
Per the comment above, please downgrade Bourbon to 3.2.3, because Scout appears to be using Sass 3.2.1, which Bourbon 4.1.0 is not compatible with.

**Comment by emage** [comment]
@elomatreb  and @tysongach  Thanks! The above method works for me.  Will this have an affect on the collaboration project if other developer are on MAC and using CodeKit with Bourbon  that may be of latest version?

Thanks

**Comment by tysongach** [comment]
@emage It depends, but if you and the other developer are using different methods for compiling, it does make it more difficult to maintain.

**Comment by emage** [comment]
@tysongach  thanks for all the help and suggestion.  Will give Codekit a try and decide on either that or Scout.  Thanks again!
