### ISSUE TITLE
Visual Studio 2015 Bower only gets _bourbon.scss

### ISSUE THREAD

**Issue by bengale** [thoughtbot/bourbon#607]
I'm having an issue with using Bower from within Visual Studio 2015. When "bower bourbon#~4.1.0" is run from grunt it only gets the "bourbon.scss" file and not all of the required files. 

This is the first package that I've found this issue with grunt, bower and visual studio.

**Comment by tysongach** [comment]
v4.1.0 changes where Bower looks for Bourbon’s files (we are no longer duplicating the library into a `dist` directory), as [noted in the release](https://github.com/thoughtbot/bourbon/releases/tag/v4.1.0).

Try updating the path and see if that solves the issue.

**Comment by bengale** [comment]
Ah sorry about that, I've got it now. Thanks.
