### ISSUE TITLE
Be consistent with font families quoting

### ISSUE THREAD

**Issue by HugoGiraudel** [thoughtbot/bourbon#609]
[Here](https://github.com/thoughtbot/bourbon/blob/master/app/assets/stylesheets/addons/_font-family.scss): 

```scss
$georgia: Georgia, Cambria, "Times New Roman", Times, serif;
$helvetica: "Helvetica Neue", Helvetica, Roboto, Arial, sans-serif;
$lucida-grande: "Lucida Grande", Tahoma, Verdana, Arial, sans-serif;
$monospace: "Bitstream Vera Sans Mono", Consolas, Courier, monospace;
$verdana: Verdana, Geneva, sans-serif;
```

It should be either:

```scss
$georgia: "Georgia", "Cambria", "Times New Roman", "Times", serif;
$helvetica: "Helvetica Neue", "Helvetica", "Roboto", "Arial", sans-serif;
$lucida-grande: "Lucida Grande", "Tahoma", "Verdana", "Arial", sans-serif;
$monospace: "Bitstream Vera Sans Mono", "Consolas", "Courier", monospace;
$verdana: "Verdana", "Geneva", sans-serif;
```

Or:

```scss
$georgia: Georgia, Cambria, Times New Roman, Times, serif;
$helvetica: Helvetica Neue, Helvetica, Roboto, Arial, sans-serif;
$lucida-grande: Lucida Grande, Tahoma, Verdana, Arial, sans-serif;
$monospace: Bitstream Vera Sans Mono, Consolas, Courier, monospace;
$verdana: Verdana, Geneva, sans-serif;
```

Needless to say I prefer the former. I understand why you did it the way you did it, but it makes no sense since CSS doesn't require font names to be quoted, even if they contain spaces. Better be consistent.

**Comment by joshuaogle** [comment]
CSS2 used to require font names to be in quotes if they contained a space. I believe that got changed in 2.1, and lots of people (myself included) kept doing it out of habit. It is still required for font names with some symbols like slashes, which I haven't actually seen in the wild.

I agree that we should be consistent, but are you saying you prefer the one with all of the names in quotes? That seems unnecessary.

**Comment by HugoGiraudel** [comment]
> I agree that we should be consistent, but are you saying you prefer the one with all of the names in quotes? That seems unnecessary.

It looks both clean and consistent. Plus most languages, including JavaScript (which is close enough to CSS in some ways), require strings to be quoted.

**Comment by tysongach** [comment]
Consistency is definitely good. I think I prefer the quoting them all, rather than none. Along with what Hugo said above, this also usually helps syntax highlighting. I’ll put up a PR and we can continue any discussion there…
