### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by stepladder** [thoughtbot/bourbon#613]
I'm using Koala and getting these errors below whenever I try to compile the Bourbon sass.

Thanks in advance.

Custom helpers..

[31m[0m[31m    error[0m sass/main.scss (Line 22 of sass/../bourbon/helpers/_font-source-declaration.scss: Invalid CSS after "    eot": expected ")", was ":   $font-url +...")

[31m[0m[31m    error[0m sass/main.scss (Line 21 of sass/../bourbon/helpers/_linear-angle-parser.scss: Invalid CSS after "      webkit-image": expected ")", was ": -webkit- + $p...")

[31m[0m[31m    error[0m sass/main.scss (Line 23 of sass/../bourbon/helpers/_linear-gradient-parser.scss: Invalid CSS after "      webkit-image": expected ")", was ": -webkit- + $i...")

[31m[0m[31m    error[0m sass/main.scss (Line 19 of sass/../bourbon/helpers/_linear-side-corner-parser.scss: Invalid CSS after "      webkit-image": expected ")", was ": -webkit- + $p...")

It goes on..

Custom functions

[31m[0m[31m    error[0m sass/main.scss (Line 11 of sass/../bourbon/css3/_keyframes.scss: Invalid CSS after "...r-webkit: true ": expected "}", was "!global;")

CSS3 mixins

[31m[0m[31m    error[0m sass/main.scss (Line 11 of sass/../bourbon/css3/_keyframes.scss: Invalid CSS after "...r-webkit: true ": expected "}", was "!global;")

Addons and other mixins

[31m[0m[31m    error[0m sass/main.scss (Line 13 of sass/../bourbon/addons/_position.scss: Invalid CSS after "    top": expected ")", was ":    nth($coord...")

Soon to be deprecated mixins

[31m[0m[31m    error[0m sass/main.scss (Line 43 of sass/../neat/functions/_private.scss: Invalid CSS after "...olumns !default": expected "}", was " !global;")

**Comment by tysongach** [comment]
It’s very hard for us to support the myriad of compilations apps, but usually these are dependency errors, e.g. using an out-of-date version of Sass with the latest Bourbon.

What versions of Bourbon and Sass are using? Are you using Compass? LibSass?

**Comment by stepladder** [comment]
Koala was out of date, updated and it works now.

Thanks!
