### ISSUE TITLE
Remove `-moz-` prefix in `columns.scss`

### ISSUE THREAD

**Issue by ysfjwd** [thoughtbot/bourbon#614]
stylesheet with `-moz-column-count` doesn't work Firefox now takes `column-(property)` natively without the `-moz-` prefix

**Comment by tysongach** [comment]
Do you have a reference for this? [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/column-count) and [Can I Use](http://caniuse.com/#feat=multicolumn) still mention use with prefixes.

**Comment by ysfjwd** [comment]
no, i don't have a reference from MDN but when i follow [this tutorial](http://cssdeck.com/labs/css-only-pinterest-style-columns-layout), it doesn't work with -moz-column-* on firefox, and works flawlessly when i remove the moz prefix.

**Comment by tysongach** [comment]
The spec (non-prefixed) version of the `column-count` property is output now with Bourbon. Going to close this now until further documentation and Firefox moves up a few versions.
