### ISSUE TITLE
Background Image Linear Gradient Issue

### ISSUE THREAD

**Issue by kirillminiaev** [thoughtbot/bourbon#620]
Hi Bourbon team,

I am attempting to use your `background-image` mixin and am having some difficulty. My `@include` is as follows:

```sass
@include background-image(linear-gradient(left, rgba(0,0,0,0.4) 0%, rgba(0,0,0,0) 100%));
```
_–This results in no CSS compiled whatsoever for the background image._

If on the other hand I only use:

```sass
@include linear-gradient(left, rgba(0,0,0,0.4) 0%, rgba(0,0,0,0) 100%);
```
_–This works, but I get a fallback `background-color` which is visible under my transparent gradient_

Ideally I would like to have a background linear gradient without a fallback color.

_Any thoughts on what I might be doing wrong or what a possible workaround/solution might be?_

**Comment by joshuaogle** [comment]
Hi @kirillminiaev,
Your first example works for me both locally and in Sassmeister/Codepen, but you shouldn't need to use the `background-image` mixin nesting like that.

You can tell the `linear-gradient` mixin to use a different fallback like this:
```
@include linear-gradient(left, rgba(0,0,0,0.4) 0%, rgba(0,0,0,0) 100%, $fallback: transparent);
```

**Comment by kirillminiaev** [comment]
Hi @joshuaogle,

Maybe it's because I am using gulp-ruby-sass for my SASS compiling? I'm not sure, but for w/e reason the `background-image` option still doesn't work.

However, your `linear-gradient` solution with `$fallback` was perfect. Everything is solved on my end, so I will mark the issue closed unless you see any other reason to keep it open.
