### ISSUE TITLE
Suggestion: global $font-file-formats setting

### ISSUE THREAD

**Issue by chrisnicola** [thoughtbot/bourbon#622]
https://github.com/thoughtbot/bourbon/blob/4e15ab1639f605f97b1ee6c66c24ebbed1ca2ca8/app/assets/stylesheets/css3/_font-face.scss

I just noticed my application attempting to download a bunch of `woff2` files which we don't have and noticed the `$file-formats` settings. I've changed it but there are about a dozen lines where I have to include this list.

I'm wondering if the default list shouldn't be a setting that can be overridden? Would be happy to PR if this is sensible.

**Comment by tysongach** [comment]
This is very dependent on the font being used and what file-formats it was delivered with. I’m not sure a default could really be decided on…

You can specify the formats per `@include font-face`, as you know. May I ask why you would have this in “dozens” of places? Do you have that many fonts to include?

**Comment by chrisnicola** [comment]
Different font weights, italics, bold, so yes, it doesn't take that many really.

**Comment by tysongach** [comment]
We’ve added a `$global-font-file-formats` variable setting in v5.0. No release date yet, but we’re working hard to get it out soon. Thanks!

**Comment by chrisnicola** [comment]
:beers:
