### ISSUE TITLE
Libsass Error on Compile

### ISSUE THREAD

**Issue by rctneil** [thoughtbot/bourbon#628]
Hey,

I'm getting the following error at compile time:

    Warning: /vagrant/rails/public/assets/bower-components/bourbon/app/assets/stylesheets/css3/selection:4: error reading values after @if

I am using Bourbon 3.2.3 and Grunt-Sass 0.17.0 from within Grunt.

Any ideas on how to solve this?

**Comment by tysongach** [comment]
The `selection` mixin doesn’t exist in Bourbon 3.2.3; it’s new as of 4.1.0. Are you sure your project is actually using 3.2.3?

**Comment by rctneil** [comment]
Sorry, my Bower had got confused. All working now. Is Bourbon 4 being updated for LibSass?

**Comment by tysongach** [comment]
Yeah, we’re slowly working on it. It’s really helping a lot that LibSass is pushing development and feature parity with Ruby Sass now.

**Comment by rctneil** [comment]
Brilliant to hear. Only just started using Bourbon after removing Compass as Bourbon is sooo much simpler.

**Comment by tysongach** [comment]
Nice! That’s great to hear; thanks for the kind words.

**Comment by iwoodruff** [comment]
I'm using bourbon 4.1.1, compiling with grunt sass and am getting the same error. 

"/bower_components/bourbon/app/assets/stylesheets/css3/selection:4: error reading values after @if"

any thoughts?

**Comment by tysongach** [comment]
@iwoodruff LibSass compatibility will be [fixed](https://github.com/thoughtbot/bourbon/pull/616) in v4.2.

**Comment by iwoodruff** [comment]
thanks for the feedback.

**Comment by ivanoats** [comment]
For anyone still ending up here, you should be able to now `bourbon update` and resolve this error.
