### ISSUE TITLE
named vs. unnamed parameters in mixins

### ISSUE THREAD

**Issue by jjb** [thoughtbot/bourbon#629]
this is either an inconsistency in the docs, and error in the docs, or something i'm ignorant about. Apologies if it's the latter.

here's the font-face mixin:

https://github.com/thoughtbot/bourbon/blob/master/app/assets/stylesheets/css3/_font-face.scss

in the docs, some of the parameters are given directly, with ordering seemingly to imply what they are, but some have an explicit key. I don't see a pattern for which do and don't have keys.

http://bourbon.io/docs/#font-face

1. is this some sort of syntactic convenience provided by SASS where it intelligently guesses your intent?
2. how do I go about specifying a list of file formats in my invocation? (this might be a SASS question, if so I apologize)

**Comment by tysongach** [comment]
We just refactored the `font-face` mixin in 4.1 and still need to update the docs; will do very soon! Sorry for the confusion.

**Comment by jjb** [comment]
good to hear

in the time-being could you show me an invocation with multiple formats?

i can then contribute a docs PR

**Comment by jjb** [comment]
thanks for the docs, closing this
