### ISSUE TITLE
Codebase Unification?

### ISSUE THREAD

**Issue by bdkjones** [thoughtbot/bourbon#642]
Hi guys,

Didn't see an open issue on this, so are there any plans to unify Bourbon so that there's just one library for Libsass or Ruby Sass? What specifically is holding up that unification? It would greatly simplify things and eliminate a lot of user confusion if we could get to a single library.

**Comment by tbremer** [comment]
This is a bit like asking JS and jQuery to be unified... (Yes, I understand...). One needs SASS for Bourbon, but not the other way around.

I don't know what's more simple than `gem install sass bourbon`

**Comment by bdkjones** [comment]
Huh? I'm afraid I don't follow. I mean unifying the 3.x and 4.x versions so that there's only one Bourbon that's used with either the Libsass or Ruby compilers. I'm afraid I don't follow the analogy you gave... I'm not asking that Bourbon stop using Sass, so....

**Comment by tbremer** [comment]
My fault! I thought you were asking for bourbon and sass to be unified. 

So, gonna act embarrass and walk away now. I owe you a :beer: if we ever meet.

**Comment by bdkjones** [comment]
No worries; I've done that plenty of times myself.

**Comment by tysongach** [comment]
@bdkjones Hey Bryan! We’re working right now to make v4.x LibSass compatible. Only a few more bugs to fix until we get there…

**Comment by tysongach** [comment]
A beta of `4.2.0` is up and should be fully compatible with LibSass `3.1`.

**Comment by tysongach** [comment]
@bdkjones Bourbon 4.2.0 is out and is compatible with LibSass 3.1.

**Comment by bdkjones** [comment]
Sweet! And this version is also compatible with Ruby Sass?

**Comment by tysongach** [comment]
Yes! Ruby Sass 3.4.
