### ISSUE TITLE
@clearfix don't worked is ie8

### ISSUE THREAD

**Issue by Killerblade** [thoughtbot/bourbon#648]
Why ? "&::after" all well aware that it's not the stuff of ie8

**Comment by joshuaogle** [comment]
IE8 does have partial support for ::after, and this method is supposed to work on IE8. Having said that, Bourbon [only officially supports IE9+](https://github.com/thoughtbot/bourbon#browser-support). If your project needs IE8, you can overwrite your own clearfix mixin with one of the other methods.

**Comment by Killerblade** [comment]
ok, thanks

**Comment by bjo3rnf** [comment]
@Killerblade I just came across that myself. Simply add ``clear: both;``:

```
@mixin clearfix() {
  &:after {
    content: "";
    display: table;
    clear: both;
  }
}
```

Works for me in IE8.
