### ISSUE TITLE
Sass doesn't compile! error reading values after @if [because "&"]

### ISSUE THREAD

**Issue by php11i5** [thoughtbot/bourbon#649]
Help me, please

**Comment by tbremer** [comment]
Do you know where the error is coming from? Better yet, have a code example?

**Comment by php11i5** [comment]
![error](https://cloud.githubusercontent.com/assets/8140713/5876480/b1604ad8-a341-11e4-8dbf-ad62c202e812.PNG)
here

**Comment by php11i5** [comment]
what do you say?

**Comment by elomatreb** [comment]
The ability to use the current selector (`&`) in SassScript (if, etc.) is a relatively new feature. What exactly are you using to compile this?

**Comment by php11i5** [comment]
it's
![dfasd](https://cloud.githubusercontent.com/assets/8140713/5876892/3ab2c2ae-a345-11e4-9c60-258ebed5df44.PNG)

**Comment by elomatreb** [comment]
I'm sorry, I wasn't clear enough. I meant: What App/tool/command are you using to compile your Sass? For example something like default `sass` command-line utility or CodeKit?

**Comment by php11i5** [comment]
clear...
it's
![fgafk ajsd](https://cloud.githubusercontent.com/assets/8140713/5877008/47536fee-a346-11e4-9103-bd643c656974.PNG)

**Comment by elomatreb** [comment]
It seems that plugin uses libsass, which does not always support everything the default Ruby sass compiler does.

Please install Ruby and ruby-sass (`gem install sass`) and try compiling your styles with it.

**Comment by tysongach** [comment]
This is a bug with Ruby Sass _and_ LibSass. A [fix](https://github.com/thoughtbot/bourbon/commit/400c3c1d7be38eda120748919ee2c253db34ff01) has already been merged into `master` and will be released in v4.2.0 soon.

Cross-referencing issues #615 & #628.

**Comment by elomatreb** [comment]
That's what I get for not following issues for a while. Thank you.

**Comment by tysongach** [comment]
@elomatreb No worries! Thanks for always chiming and helping out.

**Comment by tysongach** [comment]
@php11i5 For now, if you’re not using LibSass, you can try upgrading to (Ruby) Sass 3.4+ (I have no idea if Brackets Sass supports this) and it (should) fix your compiling. I have not tested this, though.

**Comment by kashike** [comment]
@tysongach I believe this is still an issue with master. [This](https://gist.github.com/kashike/c5f338861814e522295e) is all that is generated (using SassC and ruby sass (3.4.11)), with bourbon neat and bitters.

**Comment by shvelo** [comment]
I'm facing the same error, using LibSass. Should I switch to master?
