### ISSUE TITLE
flexbox flex mixin with 3 arguments

### ISSUE THREAD

**Issue by krychu** [thoughtbot/bourbon#653]
I'm trying to use flex mixin with 3 arguments:
@include flex( 0, 0, 300px );

but get this error message:
(Line 24: Mixin flex takes 1 argument but 3 were passed.)

Is this not supported by bourbon? Thanks

**Comment by tysongach** [comment]
It is supported! Just remove the commas:

```scss
@include flex(0 0 300px);
```

**Comment by krychu** [comment]
Thanks! ;)
