### ISSUE TITLE
font-face mixin always outputs all font formats

### ISSUE THREAD

**Issue by vivianspencer** [thoughtbot/bourbon#658]
When using the font-face mixin with the $font-formats variable, the formats specified in the variable are not respected. Instead all of the formats are always output.

See my gist as a reference: https://gist.github.com/vivianspencer/c2ad9b790bb744c9dce4

I believe the issue lies with the "contains" function used here: https://github.com/thoughtbot/bourbon/blob/master/app/assets/stylesheets/helpers/_font-source-declaration.scss#L31.

I believe instead this should be the "index" function:

```sass
...
);

  @each $key, $values in $formats-map {
    @if index($file-formats, $key) {
      $file-path: nth($values, 1);
      $font-format: nth($values, 2);
...
```

**Comment by tysongach** [comment]
Hey @vivianspencer!

Thanks for all the background information, but your Gist/Sassmeister is a bit incomplete: the `contains` function is part of Bourbon, but you didn’t include it in your Sass alongside the font mixins and functions. When I added Bourbon’s `contains` function to Sassmeister, my output is correct.

Here’s [my output](https://gist.github.com/tysongach/e7ea39035c917a6a8a89).

Also, please note that your PR is against your own fork and not against the Bourbon repo.

**Comment by vivianspencer** [comment]
You're right, my mistake, I'll do some more digging, just keeps outputting
all the fonts in my setup. The @if statement keeps returning true for me.

**Comment by tysongach** [comment]
I’m going to close this for now until we can get a more clear understand of the issue at hand.
