### ISSUE TITLE
Bower is not getting the last updated files

### ISSUE THREAD

**Issue by klangwiedergabe** [thoughtbot/bourbon#664]
I have a problem installing bourbon with bower.
The _selection.scss file on stylesheets/css3 is causing a compilation error. So I have to replace it manually for the last updated version of this file.

Which is the stable version I should install with bower?
(I'm currently just yoloing installing the version that bower gives me with: bower install bourbon --save).

thanks!

**Comment by tysongach** [comment]
We have not yet released 4.2, which has a fix for the `_selection.scss` bug in it. I believe you can tell Bower to pull Bourbon from an exact Git commit SHA—as opposed to a version number—which will allow you to get the latest work on `master`.

**Comment by klangwiedergabe** [comment]
thanks!
