### ISSUE TITLE
Version Documentation

### ISSUE THREAD

**Issue by johncionci** [thoughtbot/bourbon#670]
Im installing Bourbon through command line in a non-rails codebase and Im wondering how I tell what version that I have installed, it seems that Bourbon Neat has a file header in the _neat.scss file that describes the version that is in use, is there a comparable header in the Bourbon structure?

**Comment by tysongach** [comment]
Bourbon does the same in its main manifest file ([`_bourbon.scss`](https://github.com/thoughtbot/bourbon/blob/master/app/assets/stylesheets/_bourbon.scss)). We’ve been doing that since about v4.1.0.

**Comment by johncionci** [comment]
Thank you. I had apparently had an older gem installed. Appreciate the reply.
