### ISSUE TITLE
Running bourbon install does nothing and installs nothing

### ISSUE THREAD

**Issue by Jordan4jc** [thoughtbot/bourbon#672]
Any reason I can't install bourbon, and I see no output what so ever, not even errors?

I've uninstalled it, reinstalled it, quit all terminal windows and tried again, and restarted the computer and tried again.

**Comment by tysongach** [comment]
Can you provide more information?

Are you using the CLI? What version of the gem are you using? Where are you trying to install it?

**Comment by Jordan4jc** [comment]
Yes I'm using the CLI, it says I have version `4.1.1` installed and I have created a lib folder in my sass folder for my website project and I am cd'd into it, trying to run the command.

Neat and Bitters work just fine.

**Comment by Jordan4jc** [comment]
Actually I just ran bourbon --version and I see 0.0.0

**Comment by tysongach** [comment]
It’s hard to say, but sounds like an issue with your dev environment, which makes it hard for us to debug.

I would maybe try uninstalling all versions of the Bourbon gem  (`gem uninstall bourbon`) and then reinstalling.

**Comment by Jordan4jc** [comment]
I just nuked all my gems, and removed rvm, so I am currently at a totally vanilla development environment as far as I can tell.

I reinstalled bourbon, and running bourbon install still does not install anything or give me any output.

If I run bourbon --version I get 0.0.0 and bourbon -v says invalid command.

Is there something that needs to be added to my path or anything to get bourbon to work that is not doing it on it's own.

Is there a place I can check for installation files to see if bourbon files are even being added to my system?

**Comment by elomatreb** [comment]
I would recommend you install rvm again, since a regular setup requires system-wide installation of gems, which introduces the problem of permissions (I assume you are using a unix-based OS (OSX, Any Linux, etc)).

To find out where your gems are installed, use `gem environment`. If you find that folder, please look at the permissions of the files (for example by executing `ls -la` in that folder) and check if the owner matches your username or group in the read bit.

**Comment by Jordan4jc** [comment]
I was having a lot of problems trying to find a comprehensive guide on getting rvm properly installed and running, so I switch to rbenv, much quicker install, and I am now able to install bourbon, get a version back from the `-v` command and I was able to CD into my project directory and get bourbon installed with the `install` command.

Thanks for the help, looks like it was just something with my default system ruby environment.
