### ISSUE TITLE
"file to import not found or unreadable"

### ISSUE THREAD

**Issue by php11i5** [thoughtbot/bourbon#673]
Help me, please!

**Comment by php11i5** [comment]
does'nt work:
@import 'bourbon/bourbon';

**Comment by joshuaogle** [comment]
@php11i5 This is using something like Bower or NPM, right? Not Rails?

It sounds like you either haven't installed the module correctly or don't have it in your load path. Some more info on your setup would be helpful.

**Comment by php11i5** [comment]
yes, using npm, bower, gem, also brackets with extension for Sass/SCSS
What can you say?

**Comment by php11i5** [comment]
Which module?

**Comment by tysongach** [comment]
Can you share your codebase? It’s hard for us to debug and have context without seeing that or getting more information.

- So are you using the Bourbon gem? Or using it via Bower? npm? Each setup can be slightly different.
- What does your main Sass manifest file look like?

**Comment by php11i5** [comment]
I solved the problem

Thx to all!

**Comment by cheunghy** [comment]
Use `@import 'bourbon';` instead of `@import 'bourbon/bourbon';` fixes for me

**Comment by ryentzer** [comment]
I'm trying to use bourbon for a non-rails app and I cannot get @import 'bourbon/bourbon' to work. If I create a test directory containing a `_sample.scss` file, I'm able to import it without any trouble. I'm on OS  10.10.5 with the latest bourbon installed.

**Comment by tysongach** [comment]
@ryentzer Hi! How are you compiling your Sass and what does your directory structure look like?

**Comment by ryentzer** [comment]
To compile I'm running `sass --watch css:css`.

My file structure is:

```
website/scss/styles.scss
website/scss/bourbon/
webste/scss/test/_test.scss
```

`styles.scss` contains:

```
@import "bourbon/bourbon";
@import "test/test";
```

The `test/_test.scss` file contents are rendered. The `bourbon/_bourbon.scss` file contents are not.

**Comment by tysongach** [comment]
@ryentzer That all looks fine. Are you _using_ any of Bourbon’s features anywhere? Just importing Bourbon will not produce any output…not until you use a mixin or function or something.

**Comment by ryentzer** [comment]
Now I just feel stupid. I was importing, but not using it yet. I thought just importing the partials would show up in my css file. Thank you for your help, and sorry for the trouble.

**Comment by tysongach** [comment]
@ryentzer :smile: No worries! Not the first time.

We sorta take pride in that Bourbon outputs nothing until _you_ choose to use something. No forced bloat! :wink:

**Comment by nicovanzyl** [comment]
The main reason I love Bourbon so much! :)

**Comment by ryentzer** [comment]
That is really cool. I'm coming from a "large" framework where everything gets dumped in whether you use it or not. I must have missed this in the docs. :+1:
