### ISSUE TITLE
[Question] auto-generating browsers prefix

### ISSUE THREAD

**Issue by flashios09** [thoughtbot/bourbon#682]
hi,
Sorry for my bad english :(
I like very much **BOURBON** and i start using it(with **libsass**) as an alternative to compass. BOURBON is really fast <3

I'm using the **4.2.0 version** and i have a question, when i include for example the **border-top-radius mixin** and i look at the generated CSS i don't have the other **prefixed rules**(for firefox, chrome, opera and IE).
I didn't change the settings on the **_prefixer.scss** file:

	/// Global variables to enable or disable vendor prefixes

	$prefix-for-webkit:    true !default;
	$prefix-for-mozilla:   true !default;
	$prefix-for-microsoft: true !default;
	$prefix-for-opera:     true !default;
	$prefix-for-spec:      true !default;

What i have to do ?
Thanks

**Comment by elomatreb** [comment]
[According to Caniuse](http://caniuse.com/#feat=border-radius), there are no recent versions of any browser that require prefixing. They either support it completely or they don't use it all (Opera Mini).

You can simply use border-radius as a regular property, no mixin required.

**Comment by tysongach** [comment]
`border-radius` no longer requires prefixing in the [browser’s that Bourbon supports](https://github.com/thoughtbot/bourbon#browser-support). This mixin is simply a shorthand helper to apply radius to two corners.
