### ISSUE TITLE
Spaces in font-family name breaks SVG fonts

### ISSUE THREAD

**Issue by jordanlev** [thoughtbot/bourbon#686]
This is probably more of an issue with the docs than the code itself, but the example for [Font Face](http://bourbon.io/docs/#font-face) uses 'Source Sans Pro' for a font family name. Since this has spaces in it, the SVG font will not get loaded because the `font-source-declaration` code is using that name as an `id` selector (see https://github.com/thoughtbot/bourbon/blob/86d2147511265db9cdb35b497e195b8c4649ee98/app/assets/stylesheets/helpers/_font-source-declaration.scss#L26).

Maybe SVG selectors work differently than CSS selectors? If so, then please ignore this issue. Otherwise, I think the docs should be updated to not have spaces in the name (e.g. `@include font-face("SourceSansPro", "/fonts/source-sans-pro/source-sans-pro-regular");`).

Furthermore, if you want to be extra helpful you might have the docs explain to people that they should examine the actual SVG font file to determine what the actual ID is of the `<font>` element and make sure they are using *that* for the font-family name.

**Comment by tysongach** [comment]
Thanks for the heads up! All fixed.
