### ISSUE TITLE
Undefined variable error for "$all-text-inputs-active"

### ISSUE THREAD

**Issue by rachelcope** [thoughtbot/bourbon#694]
When I use the `$all-text-inputs-active` variable, I get the following error: `Undefined variable:  "$all-text-inputs-active"`.

The `$all-text-inputs`, `$all-text-inputs-focus` `$all-text-inputs-hover` work fine.

**Comment by joshuaogle** [comment]
Still trying to narrow this one down, but here is a Sassmeister setup that shows the problem: http://sassmeister.com/gist/8d5bf9322a8708f5eca7

Note that it's just the `active` variable that is broken.

So far it only seems to happen on projects using `node-bourbon`, which is using version `4.2.0`, and Ruby projects don't seem to have the issue.

**Comment by joshuaogle** [comment]
I was also able to reproduce locally. Updating to `node-bourbon` version `4.2.1-beta1` (where they switch to wrapping thoughtbot's Bourbon npm package) fixes the issue for me.

**Comment by tysongach** [comment]
@rachelcope Does @joshuaogle’s findings above coordinate with your issue? Are you using `node-bourbon`?

**Comment by tysongach** [comment]
@rachelcope Is still an active issue?

I have yet to be successful in re-creating this, both in Ruby Sass and LibSass
