### ISSUE TITLE
Issues with server side files

### ISSUE THREAD

**Issue by silverdragon686** [thoughtbot/bourbon#696]
I'm currently using Bourbon, Neat and Bitters, compiled in one styles.scss file. Everything works great when the base file type is HTML (such as index.html). However, when I change the file type to .php or .asp, I get Invalid Syntax errors. Particularly !global and #{} instances.

I've commented out the lines spit back in the syntax errors in the mean time, but I'm wondering if it doesn't effect the integrity of the rest of the code. Bitters still works although I've had to supplement with long-hand rules, but I've got direction-context reversal in Neat (RTL) despite everything being set LTR.

Not sure where I can address this issue...

**Comment by tysongach** [comment]
@silverdragon686 Can you provide more details on your development environment? How are you compiling your Sass?

**Comment by silverdragon686** [comment]
Right now I've installed the gems in Ruby, but I'm swapping between Scout and Koala to compile. I'm running Win7 OS.

**Comment by tysongach** [comment]
What versions of Bourbon, Bitters and Neat are you using?

It’s very hard for us to debug GUI applications that are used for compiling Sass, especially when _two_ are being used. It’s likely an issue with that, since no other bugs similar to yours have been reported when using standard compilation methods. Have you reported this to either Koala or Scout?

It appears that Scout app hasn’t seen [active development since 2012](https://github.com/mhs/scout-app).

**Comment by silverdragon686** [comment]
Sass 3.4.12
Bourbon 4.2.1
Neat 1.7.2
Bitters 1.0.0

My primary is Koala, but I'm not a fan of their error notifications. Hence why I also use Scout, since I can see exactly where the errors are occurring and what's causing them.

I just find it strange that an .html file will have 0 errors, but as soon as I "save as" that file as .php or .asp file types, I suddenly get a whole slew of errors. NOTHING is changed in the code - not the HTML/CSS/SASS/Javascript and the file paths are all the same. I don't see how two separate compilers, even if one is outdated, would make a difference.

Are there examples of people developing with .php or .asp file types without such errors?

**Comment by tysongach** [comment]
Why are you swapping HTML-based files for ASP or PHP?

If the errors happen when you’re doing that swapping with no change to your Sass, then this sounds like an issue with your development environment and not Bourbon. We do have people using Bourbon within PHP environments, for example [this WordPress theme](https://github.com/onishiweb/roots-on-the-rocks), but most of them are using things like Grunt to compile.

I would file a bug with Koala and/or Scout to see if they can help.
