### ISSUE TITLE
Undefined mixin Media error

### ISSUE THREAD

**Issue by ramtml** [thoughtbot/bourbon#699]
Hi,
 i m using windows. when i tried to compile after putting the scss styles for the navigation it showing the error undefined element 'media '. I have removed the navigation style and put the styles for type. Then it is showing the error $base-font-color is undefined. Why it is happening like this?

**Comment by tysongach** [comment]
Can you share your code? Can you describe your dev environment? Are you using Bitters and Neat or Refills? `$base-font-color` is a variable defined in Bitters, not Bourbon.

**Comment by tysongach** [comment]
I’m closing this issue until more detailed information is provided.
