### ISSUE TITLE
Question: Why not drop vendor prefixes in favor of using Autoprefixer?

### ISSUE THREAD

**Issue by mattmcmanus** [thoughtbot/bourbon#701]
I searched the past issues and didn't see anything about this so I figured i'd post it as a question. It seems like removing all of the vendor prefix code would be a big win. It would be a lot less code and would stabilize some of the churn on removing prefixes that no longer need to be there. [Autoprefixer](https://github.com/postcss/autoprefixer) already handles all that nicely, is easy to target browsers and integrates nicely into all the major build tools. 

Has the been any internal discussion about this already?

**Comment by tysongach** [comment]
@mattmcmanus Yes! There have been discussions on this and Bourbon 5.0 will be exactly this. You can follow along on the [`bourbon-v5.0.0`](https://github.com/thoughtbot/bourbon/tree/bourbon-v5.0.0) branch.

**Comment by mattmcmanus** [comment]
![Thanks!](http://media.giphy.com/media/a3IWyhkEC0p32/giphy.gif)

Is there a list of things in store for 5.0 besides the two issues in the milestone. I'd love to help if I'm able

**Comment by tysongach** [comment]
@mattmcmanus Along with removing prefixes and a few general code improvements, we are also porting all documentation over [SassDoc](http://sassdoc.com). It’s a bit of a laborious process, but we have made a lot of headway. Feel free to add any documentation to features that are missing them in the 5.0 branch.

We’re also writing feature tests and hope that Bourbon will be fully tested in 5.0.

Once we release an alpha (hoping to soon), any testing then will be very helpful!

**Comment by mattmcmanus** [comment]
Awesome. Looking forward. I'm about to start a large project and I'm excited to be able to really lean into bourbon and the fam.
