### ISSUE TITLE
[Announcement] An Update on Bourbon v5.0

### ISSUE THREAD

**Issue by tysongach** [thoughtbot/bourbon#702]
We’re working hard on the next major version of Bourbon (v5.0) and we’d like to update you with our goals and progress. You can also follow along on with the [v5.0](https://github.com/thoughtbot/bourbon/tree/bourbon-v5.0.0) branch.

First, we’ve decided to remove browser prefixing features from Bourbon. Our main reasons for doing so are:
- It’s no longer best practice for pre-processors like Sass to handle prefixing. Instead, a post-processor is better suited for this task and allows you to write much cleaner Sass (no more `@include`’s for prefixes!).
- [Autoprefixer](https://github.com/postcss/autoprefixer) is a robust, well-maintained tool to post-process prefixes.
- There’s no easy way for us to decide what browser versions Bourbon should support.
- Autoprefixer ties into the [Can I use](http://caniuse.com) database and allows you to [specify the exact browser support](https://github.com/postcss/autoprefixer#browsers) you need, per project. This is quite powerful, yet painless.

Along with that, we are porting our documentation over to [SassDoc](http://sassdoc.com), so that it’s more comprehensive, consistent and easier to contribute to. And we’re also writing feature tests for Bourbon, so that we can make sure the code is always stable.

We hope everyone is as excited for the future of Bourbon as we are!

– The Bourbon Team

**Comment by samuelbran** [comment]
I respect your decisions on this prefixes thing guys, you're making an awesome job Bourbon. Though I have to say that one of the main reasons I started to use Bourbon was because I was tired to write prefixes by hand and the includes, well, made my life a lot easier. I mean is cool to follow up with the latest techniques and tools but is also cool to have as much as you can in just one tool.

- Sam

**Comment by hotmeteor** [comment]
@samuelbran It definitely takes the onus off of Bourbon and other similar tools to keep up-to-date with the myriad of browser prefixes. I know from time spent on the flexbox portion alone it was a huge task.

If you're not already using Autoprefixer I suggest giving it a whirl. It's really fantastic.

**Comment by franks921** [comment]
:+1: 

Although my reasoning for initially using Bourbon was for the browser prefixes, I do agree and support the decision to remove them. It is time to move forward.

@samuelbran It will be no difficult task to extract those mixins to use in your project while upgrading, but if you are going to spend the time doing that you might aswell use Autoprefixer :)

**Comment by samuelbran** [comment]
@hotmeteor I really admire the guys behind Bourbon, they are amazing and I respect them a ton. I will give Autoprefixer a try for sure! cc @frank921

**Comment by andrelima** [comment]
Glad to hear Autoprefixer is the new recommended method for handling prefixes. :+1:

**Comment by FrontEndStudio** [comment]
What about libsass support?

**Comment by colorful-tones** [comment]
+1 for dropping browser prefixes, and +1 for SassDoc. Thanks for awesome work!

**Comment by tysongach** [comment]
Thanks all!

@FrontEndStudio We already support LibSass (as of [4.2](https://github.com/thoughtbot/bourbon/releases))!

**Comment by indrekpaas** [comment]
The `prefixer` mixin itself could still be included in version 5. It's really handy to use it on non-spec properties like `appearance` and the like, where Autoprefixer falls intentionally short.

**Comment by tysongach** [comment]
@indrekpaas Yes, we’ll be leaving the `prefixer` mixin in, as well as the `appearance` mixin since Autoprefixer doesn’t prefix that property.

**Comment by HugoGiraudel** [comment]
I am thrilled to know that Bourbon documentation is going to be fully powered by SassDoc. If you need help, be sure to ask. :)

**Comment by tysongach** [comment]
Bourbon v5.0.0.alpha.0 » https://github.com/thoughtbot/bourbon/releases/tag/v5.0.0.alpha.0

**Comment by mindeavor** [comment]
Since this an alpha release, is there anything in particular that is considered "unstable" we should look out for?

**Comment by tysongach** [comment]
@mindeavor A few of us at thoughtbot are using it in production on a few client projects with no hiccups, so I don’t think so! The link above outlines the big changes to conventions that you might have to re-align to.

**Comment by mindeavor** [comment]
I found something: bitters `v1.0.0` is not compatible; it uses some features that were changed / removed in bourbon 5

**Comment by mindeavor** [comment]
Documented the necessary changes here: https://github.com/thoughtbot/bitters/issues/194

**Comment by Lego2012** [comment]
@tysongach: How could Bourbon be used with PostCSS? There's a PostCSS plugin already for Neat. We're just testing PostCSS because we probably go away from Sass. But we use Bourbon quite a lot. Any suggestions?

**Comment by tysongach** [comment]
@Lego2012 Hi! I haven’t dived into it much, but I‘m not aware of an easy way to “port” the library over to PostCSS. It would be a re-write to make it work there. Honestly, it’s not a focus at this point in time, but it’s something we might look into in the future.

**Comment by Leagnus** [comment]
It seems that 'perspective' is depricated too

**Comment by magicsass** [comment]
Hey, when do you plan to release this 5th version and his documentation? 
Thx for the reply :)

**Comment by colorful-tones** [comment]
Will Bourbon (Neat, etc) be better supported through installing via Bower or NPM in future releases? Just curious if you recommend one or other.

**Comment by tysongach** [comment]
@magicsass We [released the alpha in August](https://github.com/thoughtbot/bourbon/releases/tag/v5.0.0.alpha.0) and have had zero issues reporting. The beta should be out within the next couple days. Past that, it’s documentation clean up, then launch.

**Comment by tysongach** [comment]
@colorful-tones Can you clarify what you mean by “better supported?” We’ve support Bower for quite awhile. We have also supported npm for quite some time, though the inclusion of proper load paths is [fairly new](https://github.com/thoughtbot/bourbon/commit/36c2d5576f1fe9dbdfd9543e15064c5a4a16343e). Please let us know if there is specific needs/issues around these tools!

**Comment by gregrickaby** [comment]
@tysongach I think what @colorful-tones is asking is:

Does ThoughtBot have an opinion on which package manager to use? NPM, Bower, etc... ? 

I know there's been a resurgence in the Bower community, but using NPM just feels less, icky. :smile:

**Comment by tysongach** [comment]
@gregrickaby I can’t speak for all of thoughtbot, but my opinion is that it depends on the project. We do a lot of Rails work, as well as a lot of work with [Middleman](https://middlemanapp.com), so pulling Bourbon from RubyGems is quite common. Though, we use Gulp, too, so npm is great for that.

Bourbon is also set up for use with [eyeglass](https://github.com/sass-eyeglass/eyeglass). At the end of the day, we publish Bourbon to where it makes sense and where the community needs it to be. If there are ways we can make Bourbon easier to integrate into your project, we’re happy to discuss!

**Comment by tysongach** [comment]
[Bourbon `5.0.0.beta.1` has been released](https://github.com/thoughtbot/bourbon/releases/tag/v5.0.0.beta.1).

**Comment by jcano** [comment]
Is there anywhere we can find the docs for 5.0? There many changes with the previous version and docs/tutorials I found are outdated.

Although I'm just learning Bourbon, I would like to use v5 not only because latest Bitters already asks for it but to avoid porting in a couple of months a new project I'm working on.

**Comment by tysongach** [comment]
@jcano We’re working on the docs now, but don’t yet have anything published. Best bet for now is the review our change log: https://github.com/thoughtbot/bourbon/blob/master/CHANGELOG.md

If you have any specific questions, don’t hesitate to ask!

**Comment by jcano** [comment]
I think I will just use the latest v4 for now. Everything I find on tutorials and guides has been removed (retina-image) or has different parameters (size).

The bleeding edge is not really a good place to learn ;)

**Comment by mpukit** [comment]
+1 autoprefixer! Is there a tentative date as to when the docs for v5 will be accessible, even in a beta format? Or changelog is it for a while?

**Comment by tysongach** [comment]
@mpukit I hope to make progress on this tomorrow and get some rough docs up.

**Comment by tysongach** [comment]
You can now view 5.0 documentation here: http://bourbon.netlify.com/docs/5.0.0

The site is a work-in-progress and we’ll be deploying to that temporary domain while we develop it. Please let us know if you have feedback!

cc: @mpukit

**Comment by mpukit** [comment]
Awesome. Thanks!

**Comment by celik88** [comment]
8/21 marks 1 year since alpha 0! Hopefully we can have version 5 out of beta and released soon. Thanks for all the hard work guys!

**Comment by JoshSmith** [comment]
Any updates on this?

**Comment by tysongach** [comment]
@JoshSmith We just released 4.3 yesterday which introduces all of the deprecation warnings for 5.0 removals. That now being out, puts us super close to a final 5.0 release.

**Comment by JoshSmith** [comment]
Thanks @tysongach. Came here because I'm working my way through a couple deprecation warnings. Looks like the others are all probably internal to Bourbon. Will keep an eye on this so I know when to bump and verify.

**Comment by peterpeterparker** [comment]
@tysongach just reinstalled (rm/install) 4.2.7 and got the deprecation warnings for 5.0 too, normal?

Furthermore, may I ask, I've to say I'm a pretty dumb css guy, that's one of the reasons why I use bourbon too. Will you have time/did you plan to provide some documentation examples on how to replace the methods you gonna remove, like linear-gradient?  ;)

**Comment by tysongach** [comment]
> just reinstalled (rm/install) 4.2.7 and got the deprecation warnings for 5.0 too, normal?

@peterpeterparker It’s possible, yes. What are the warnings? There are some features that were deprecated before 4.3 (e.g. the `box-sizing` mixin), so if you’re using those with 4.2.7, they will throw warnings. You can silence those [by setting `$output-bourbon-deprecation-warnings` to `false`][warnings] before importing Bourbon.

[warnings]: http://bourbon.io/docs/#output-bourbon-deprecation-warnings

> Will you have time/did you plan to provide some documentation examples on how to replace the methods you gonna remove, like linear-gradient?

In many cases, the path forward is to go back to using plain CSS. For example, [CSS gradients are now very well supported across browsers][gradient support], so there is no need to use a mixin for that anymore. All the mixin did was prefix the property for the different browser vendors.

That being said, it’s totally fine to stick with 4.2.7 if you need these mixins. 5.0 has a few new features (e.g. `contrast-switch` function and `hide-visually` mixin), but nothing that forces you to upgrade.

[gradient support]: http://caniuse.com/#feat=css-gradients

**Comment by JoshSmith** [comment]
@tysongach it looked like I was getting warnings internal to Bourbon on 4.2.7. Is that possible?

**Comment by tysongach** [comment]
@JoshSmith What are the warnings? Does this https://github.com/thoughtbot/bourbon/pull/1002 relate to this?

**Comment by peterpeterparker** [comment]
@tysongach thx you a lot for your nice and detailed answer!

With 4.2.7, I've got warnings about: linear-gradient, placeholder and transform.

For the moment I'm not gonna silence these, even it's a good tips you gave us. I gonna stick for a while to 4.2.7 but at some point I hope I will have time to upgrade too and let's see if I could improve my dumb css skills and find the way to replace these above listed useful mixin ;)

**Comment by yangkennyk** [comment]
Is there a post or something detailing the changes for bourbon 5.0 and neat 2.0? 

it seems like a ton of functions are being stripped out. are you trying to strip down to the essentials?

for example neat 2.0 no longer has the media query function.

**Comment by tysongach** [comment]
@yangkennyk For Neat, would you mind posting specific questions or issues over on [that repo](https://github.com/thoughtbot/neat)? The old `media` mixin has been replaced with `grid-media`.

A v5 upgrading guide is forthcoming, but for now you can see our [change log](https://github.com/thoughtbot/bourbon/blob/master/CHANGELOG.md) which details every change.

**Comment by sqnkov** [comment]
@tysongach as @yangkennyk said, this looks like a usability genocide. 90% of the mixins I am currently using from v4 are non-existant in v5, this is really confusing.

**Comment by tysongach** [comment]
@sqnkov If you have specific questions or problems, please feel free to file a new issue and we’ll do our best to help out. We know the _quantity_ of removals for v5.0 is large, but almost all of them tie back to prefixing features being removed.

We maintain a rich [change log](https://github.com/thoughtbot/bourbon/blob/master/CHANGELOG.md) which documents all of these changes and we also released v4.3 which (only) adds deprecation warnings for everything removed in v5.0, so that you can see specifically within your project which features you need to take action on. Furthermore, when the new website goes live for v5.0, there will be an upgrading guide.

Finally, it’s also not a requirement to upgrade to v5.0. If you have a project on v4.x, it is a stable release and valid one to stay on. Starting new projects with v5.0 is a fine route to take.

**Comment by sqnkov** [comment]
@tysongach  , thanks for the explanatory response. 

Prefixing is my biggest concern here, simply beacuse all the ```@include```s like per say - the flexbox mixins were the best thing. Using Autoprefixer from now on would be a pain, but I guess that is the natural way of things right now.

Thanks again.

**Comment by yangkennyk** [comment]
I'm just trying to understand the reasoning for nixing like 90% of the functions.

I feel like I'm missing some big developer news that we shouldn't use those things anymore or something.

**Comment by hotmeteor** [comment]
@yangkennyk Google "post-processors"

**Comment by yangkennyk** [comment]
@hotmeteor ah that makes sense. is there a css post processing stack/combo that thoughtbot recommends?

**Comment by sqnkov** [comment]
@hotmeteor , while there is nothing wrong with that argument , I am referring to the development stage, the pre-production builds which vary in size and require prefixing as well.

**Comment by gregrickaby** [comment]
@yangkennyk @sqnkov 

WebDevStudios loves Bourbon/Neat, and we too were shocked to see so many things removed; but when you look closer (at what actually was removed), it makes total sense that Thoughtbot killed off all the prefixing mixins. 

If you're not familiar with PostCSS and Autoprefixer, then you should look into using Gulp to deal with compiling Sass and then PostCSS to handle auto prefixing, minification, combining media queries, etc.... 

With Gulp, these tasks happen both automatically - and in a matter of milliseconds. Because of this, we don't have to "remember to use Bourbon's mixins" while writing our Sass. Quite honestly, thanks to PostCSS, we don't give browser prefixing a second thought! 

Here is our Gulpfile: https://github.com/WebDevStudios/wd_s/blob/master/Gulpfile.js#L76

And I'd be happy to chat further if you want help!

**Comment by tysongach** [comment]
> I'm just trying to understand the reasoning for nixing like 90% of the functions.

@yangkennyk @sqnkov A few thoughts on this:

1. Many of Bourbon’s prefixing mixins were created when the CSS3 spec was still changing and prefixing features like `border-radius` and `transform` were simply the only way to use them. Fast forward to now, most of these features have been standardized and shipped in browsers unprefixed. I’ve not actually correlated the two, but if you overlay the prefixing mixins from Bourbon with data from [Can I Use](http://caniuse.com/), I imagine you simply don’t need prefixing for nearly all of the features if you support modern browsers and IE 10 and up.

1. By implementing prefixes in Sass (at least the way did), Bourbon had to have an opinion as to what browsers it supported. Since prefixed features—by nature—are experimental features, it was always a battle chasing all of the different implementations and changes whenever a new browser version was released. For reference, take a look at how we had to implement the old `flexbox` mixin to cover the evolving spec when it was being designed: https://github.com/thoughtbot/bourbon/blob/v4-stable/app/assets/stylesheets/css3/_flex-box.scss (327 lines! 👻 ).
 
1. Expanding on what @gregrickaby mentioned above, prefixing isn’t really a _design decision_ made by developers when implementing styles. Rather, it is dictated by what browsers you need to support: it’s black and white. I’m of the opinion that this is _prime_ for automation and we as developers shouldn’t have to think about prefixes constantly when building styles. Let’s focus on implementing our design and not whether “Component A” has the correct prefixes to meet our browser support requirements. [Autoprefixer allows you configure specifically what browsers you need to support](https://github.com/postcss/autoprefixer#browsers) in a project and it leverages open data from Can I Use to add prefixes to meet your needs. It will even _remove_ unnecessary prefixes, if they aren’t need to meet your requirements. That’s _fantastic_ and something we just couldn’t pull off in Bourbon.

1. Browser makers have moved away from prefixes altogether for experimental features in favor of runtime flags, including [Blink](https://www.chromium.org/blink) and [WebKit](https://webkit.org/blog/6131/updating-our-prefixing-policy/).

> is there a css post processing stack/combo that thoughtbot recommends?

We are a consultancy and find ourselves working with lots of different tools and in lots of different environments. That said, we do use Ruby a lot and integrate Autoprefixer into our Ruby on Rails and Middleman projects.

This surfaces another benefit of Autoprefixer, which is that it has a strong community and lots of integrations: https://github.com/postcss/autoprefixer#usage. It’s usually fairly straightforward to “drop-in.”

> while there is nothing wrong with that argument , I am referring to the development stage, the pre-production builds which vary in size and require prefixing as well.

@sqnkov I’m not sure I understand. Can you expand on this?

**Comment by sqnkov** [comment]
@tysongach , I am currently building an Angular 2 SPA , which transpiles(and pre-processing) everything using the angular-cli webpack build and a simple Gulp I made for the scss files that I use, however, prefixes are somtething that I need to test during the development stage, meaning that I don't solely depend on post-autoprefixing and I need to see what happens in various browsers.

As I take a second look, my most obvious irritation with those deprecations is the flexbox model mixins. But I managed to implement my own yesterday, so I think everything is cool now.

It's just the mental trip that hits you when you see all of the functions in the Docs being scribbled-out with a strike-trough...

**Comment by tysongach** [comment]
@sqnkov As with Sass, Autoprefixer can process your CSS while in development. If you’re using Gulp to compile your Sass, it should be straightforward to add Autoprefixer to the chain.

I also wanted to note that Bourbon 5 still has our `prefixer` and `value-prefixer` mixins, which were used to build most of the prefixing features.

**Comment by feitla** [comment]
@tysongach I see that v5.0.0 still has beta appended to the name. Is there an idea of when a stable version will be released?

**Comment by shorty2240** [comment]
Bourbon's warnings now tell you:

> WARNING: The box-sizing mixin is deprecated and will be removed in the next major version release. **This property can now be used un-prefixed.**

However, if I was to just read this warning and take out the prefixes (without researching it, landing here, and adding an autoprefixer to my process) I would lose the functionality I had previously right?

**Comment by tysongach** [comment]
@shorty2240 The warning is meant to indicate that the `box-sizing` property no longer needs prefixes (unless you need <= IE7). So you can write plain CSS, like this:

```diff
- @include box-sizing(border-box);
+ box-sizing: border-box;
```

Ref: [`box-sizing` on Can I Use…](http://caniuse.com/#feat=css3-boxsizing)

**Comment by shorty2240** [comment]
@tysongach I see, I removed my comment then as I jumped to conclusion that my case was about all prefixes as discussed here and not specific to box-sizing, thanks

**Comment by tysongach** [comment]
@shorty2240 In the future, please refrain from deleting comments, as it breaks the linear history of conversation and is now confusing to people reading through. Others can learn from these comments! 😄

**Comment by inrgb** [comment]
Can someone explain why retina-image() has been deprecated and what we're to do now to re-create this functionality? Many thanks.

**Comment by sqnkov** [comment]
@inrgb , simply stick to ver 4.* and you are good to go. Many of the deprecations seem to be due to the dynamic nature of prefixes and stuff alike, which can't be maintained all the time.

**Comment by kgcreative** [comment]
@tysongach what's pending before a stable v5 release? Anything I can do to help? I've been using v5.0.0.beta.7 on a new pre-production instance and we're close to launch. So far it's been stable and rather awesome

**Comment by bdkjones** [comment]
#1027

**Comment by mittalyashu** [comment]
Now does it means? Now should we start using Autoprefixer instead of Bourbon?

Mostly the full list is stricken. Which one should I use or not, quite confused?

**Comment by Toddses** [comment]
It's up to you whether or not to proceed with Bourbon. But the general consensus is your Sass build process should include autoprefixer, so Bourbon is dropping most, if not all, of the strictly prefixing mixins. However Bourbon still has many useful mixins, and I'm sure it will grow from here.

**Comment by mittalyashu** [comment]
Any expected future date, when the Bourbon v5.0 will be released.

**Comment by mkempe** [comment]
A question in the round and what @inrgb already mentioned: How do you handle Retina Images with the upcoming Bourbon v5.0?

PS: Many thanks for Bourbon!

**Comment by baburdick** [comment]
Also curious about Retina images with Bourbon v5+.

**Comment by tysongach** [comment]
@mkempe @baburdick We’ve deprecated the [`hidpi`](http://bourbon.io/docs/#hidpi-media-query) mixin, along with the other prefixing features. You can simply use CSS’s `min/max-resolution` query (Autoprefixer will backfill `device-pixel-ratio` for browsers that still support that, which is non-standard):

```css
.element {
  @media only screen and (min-resolution: 150dpi) {
    color: green;
  }
}

```

- [CodePen example](https://codepen.io/tysongach/pen/PJPEJO?editors=1100)
- [Can I Use](http://caniuse.com/#feat=css-media-resolution)

**Comment by baburdick** [comment]
Thanks @tysongach. We've upgraded our web app to use v5.0.0.beta.8 in a branch. Ready to send this into production once v5 drops. What remains on that front? Anything we can do?

**Comment by baburdick** [comment]
Checking in again, @tysongach, to see if there is anything we can do to help wrap this up.

**Comment by tysongach** [comment]
Bourbon v5.0.0 is out: https://github.com/thoughtbot/bourbon/releases/tag/v5.0.0

Thanks for the patience!

**Comment by RAFA3L** [comment]
Thanks!!!
