### ISSUE TITLE
Bourbon refill accordion/tab link ploblem

### ISSUE THREAD

**Issue by fabriziotappero** [thoughtbot/bourbon#705]
Hi,
I've implemented a simple accordion/tab taken from here
http://refills.bourbon.io/

Here is some code:
https://github.com/fabriziotappero/freerangefactory.org/blob/gh-pages/shop.html
all css here
https://github.com/fabriziotappero/freerangefactory.org/blob/gh-pages/css/main.sass
Here a working site
http://fabriziotappero.github.io/freerangefactory.org/shop.html

Any link inside a second tab leads to an empty screen.... the href is correctly parsed ny the jekyll markdown engine. I really dont know what is going on... maybe the refill JS?
Any help is greatly appreciated.

Cheers
Fabrizio

**Comment by tysongach** [comment]
Hi, please post this issue in the Refills repo: https://github.com/thoughtbot/refills
