### ISSUE TITLE
linear-gradient not rendering correctly 

### ISSUE THREAD

**Issue by dimanyc** [thoughtbot/bourbon#712]
Hi, 

Trying to use a  combination of `linear-gradient` and `background-image ` asset, as shown in docs. But the image asset keeps overlaying the gradient lines.

SCSS:

    @include background-image(url("foo.jpg"), linear-gradient(white 0, yellow 50%, transparent 50%));

CSS renders:

    background-image: url("foo.jpg"), -webkit-linear-gradient( white 0, yellow 50%, transparent 50%);
    background-image: url("foo.jpg"), linear-gradient( white 0, yellow 50%, transparent 50%);

**Comment by elomatreb** [comment]
I think that's how it's supposed to work. If you want the gradient to be on top, try switching the image and the gradient.

**Comment by dimanyc** [comment]
@elomatreb  thanks!
