### ISSUE TITLE
Keyframe Mixin Not Compiling Animation Name.

### ISSUE THREAD

**Issue by shekinahsmith** [thoughtbot/bourbon#714]
I wrote this : 
 
     @include keyframes(chatNow) {
	  0% { opacity: 0 }

	100% { opacity: 1 }
    }

And after compiling with no issues got this in my css file : 
    @-webkit-keyframes $name {
        0% {
            opacity: 0; 
        }
        100% {
            opacity: 1; 
        } 
    }

Instead of compiling the the name of the keyframe it's outputing '$name'. I even tried putting in the example that is in the bourbon documentation to see how it compiled and still the same result. I'm getting '$name' instead of the actual name of the keyframe.

**Comment by tysongach** [comment]
Hi! I can’t seem to reproduce this…here’s my test: http://sassmeister.com/gist/6f94fbdb91cf946efc16

What are you using to compile your Sass? What’s your environment look like?

**Comment by shekinahsmith** [comment]
@tysongach I just quit out of Codekit, which is what I using to compile and restarted it and still nothing. I checked my codekit is up to date and so is bourbon. As far as my settings in Codekit go, I'm compressing my css files and also, creating a source map. I had another developer on my team try this out and he is also having the same issue.

**Comment by shekinahsmith** [comment]
@tysongach we figured it out. We had an old mixin file that created for use on the site and it was being imported after we imported bourbon and it was overriding the mixins from bourbon. Thanks for responding so quickly tho.

**Comment by tysongach** [comment]
Ah ha! I’m glad you got it sorted out!

:tada:
