### ISSUE TITLE
Background-image and linear-gradient (with fallback) throwing error.

### ISSUE THREAD

**Issue by jhonnymoreira** [thoughtbot/bourbon#720]
Hi!
I'm using a simple mixin to generate my gradients based in two colors only with the `linear-gradient` function to help me.
I was trying to use the `linear-gradient` inside the `background-image` function with the `linear-gradient`'s `$fallback` argument filled, but it was giving me an error.

The mixin was:
```scss
@mixin gradient-background($primary, $secondary) {
  @include background-image(linear-gradient(to bottom, $primary, $secondary, $fallback: $primary));
}
```

And the error:
`Function linear_gradient doesn't support keyword arguments`

Is it normal to get this error when using this combination or should I use only the `linear-gradient()` in this case with the `$fallback` filled?

Thanks, guys.

**Comment by HugoGiraudel** [comment]
Use the `linear-gradient` mixin:

```scss
@mixin gradient-background($primary, $secondary) {
  @include linear-gradient(to bottom, $primary, $secondary, $fallback: $primary);
}
```

**Comment by jhonnymoreira** [comment]
@HugoGiraudel, thank you. It was one of the solutions that I found and started using in the project. By the way, do you know why this kind of error happens when you use `background-image`and `linear-gradient`?

**Comment by HugoGiraudel** [comment]
Because the linear-gradient does not have a `$fallback` parameter.
