### ISSUE TITLE
Omega doesn't work as expected 

### ISSUE THREAD

**Issue by shadeed** [thoughtbot/bourbon#725]
I'm using Omega to add a margin between the items in different views (Mobile, tablet and desktop). The issue is that the media queries override the styles between them. So the media query for 992px width take some styles from a previous one 768px.

For example in the tablet view (768px+) I want to show 3 items per row but it look like:
X X
X
X
X X 
X X 

And in the desktop view (992px+)  I want to show 4 items per row but it look like:
X X
X
X
X X 
X X 

We can use !important to force the styles in different view but I don't want to use it. Is there a solution for this?

![screen shot 2015-05-05 at 11 35 03 am](https://cloud.githubusercontent.com/assets/8038659/7469300/8460b044-f31a-11e4-8309-c59c4a8454e2.png)

**Comment by tysongach** [comment]
Hi @shadeed, can you please post this issue over in the [Neat repo](https://github.com/thoughtbot/neat)?
