### ISSUE TITLE
Magento convert Compass to Bourbon

### ISSUE THREAD

**Issue by theskillwithin** [thoughtbot/bourbon#730]
Hello,

Magento 1.9 comes with a compass install which uses ruby and is slow (esp with magento's huge scss files). 

Do you know of a way I can convert the compass inside Magento to bourbon instead.

**Comment by tysongach** [comment]
Hey!

I don’t know of an automated way, unfortunately. But some of the mixins between Bourbon and Compass are quite similar in syntax and function, so it may not take too much effort.

Also: no need to post the same question to GitHub, Twitter and Gitter. We’ll see it in any one of those places. :smiley:
