### ISSUE TITLE
Bourbon site description on google

### ISSUE THREAD

**Issue by zrosenbauer** [thoughtbot/bourbon#735]
Bourbon site in google search was showing css in description instead of text.
![screen shot 2015-05-18 at 2 39 55 pm](https://cloud.githubusercontent.com/assets/3486461/7690508/c83c04e4-fd79-11e4-95df-4746861ec4d0.png)

**Comment by zrosenbauer** [comment]
Here is a full screen screenshot
![screen shot 2015-05-18 at 4 28 39 pm](https://cloud.githubusercontent.com/assets/3486461/7690641/03012810-fd7b-11e4-865c-2d4fa2073cdf.png)

**Comment by tysongach** [comment]
Well shoot, that’s a bummer! Thanks for the heads up.

I think Google changed their ways recently and no longer only look at `meta name="description"`. Will investigate!

**Comment by ramtml** [comment]
Hi Tysongach,
mark your pages with Rich snippets. 

https://developers.google.com/structured-data/rich-snippets/
http://schema.org/

**Comment by tysongach** [comment]
Using Google Search Console (previously known as Webmasters Tools), it looks like our description was simply too short.

---

![screen shot 2015-05-22 at 3 36 20 pm](https://cloud.githubusercontent.com/assets/903327/7778361/720562c4-0098-11e5-8844-dd0fbffa7c4f.png)

---

I tweaked it and make it a bit lengthier and more descriptive. Hopefully this resolves the issue.

Thanks for reporting!
