### ISSUE TITLE
Start testing on sassc / sassc-rails

### ISSUE THREAD

**Issue by elia** [thoughtbot/bourbon#736]
Using bourbon with it gave me:

```
Error: file to import not found or unreadable: bourbon, neat
```

I know it's probably on their side but I still thing would be valuable to have it in the travis matrix, even in allowed failures. Just to give useful feedback from a major library.

**Comment by tysongach** [comment]
Bourbon should work fine with LibSass; an error like that doesn’t usually indicate a compatibility issue. If you’re still having issues, please provide some more information in regards to your environment and we can try to help out.

We have begun adding tests to Bourbon but we’re focused on Ruby Sass for the moment. Testing on both is something we’re looking into.

**Comment by elia** [comment]
Will see if I can put together a vanilla rails app demonstrating the issue

**Comment by elia** [comment]
Ok, just to make things clear I'm not finding the time to do that, but look forward to see it supported, keep up the good work! :frog:
