### ISSUE TITLE
Hide-text text-indent firefox problem

### ISSUE THREAD

**Issue by furiousm** [thoughtbot/bourbon#737]
We have a problem with de hide-text mixin, text-indext: 101% is not enough.
To fix the problem i've changed text-indent to 110%...

Only if firefox

![image](https://cloud.githubusercontent.com/assets/939113/7768241/691d8eee-0079-11e5-9c9d-1d411ac0434d.png)

**Comment by tysongach** [comment]
Can you please provide some context or paste the code you’re using `hide-text` with? Also, what version of Bourbon are you using?

**Comment by tysongach** [comment]
Closing due to lack of response.
