### ISSUE TITLE
Compiled Bourbon CSS

### ISSUE THREAD

**Issue by vs4vijay** [thoughtbot/bourbon#739]
Is there anyway to get compiled bourbon css only?. I don't wanna compile scss on my own. Just like bootstrap there should be precompiled `bourbon.css`, isn't it?

**Comment by tysongach** [comment]
Hi @vs4vijay!

Bourbon is actually quite a bit different from Bootstrap, the biggest being that Bourbon out-of-the-box has zero CSS to compile. There is no output when you first include Bourbon, rather it now provides you with a series of tools (mixins, functions, etc.) to use within your project.

Hope that helps.
