### ISSUE TITLE
Syntax errors when compiling using grunt-contrib-sass

### ISSUE THREAD

**Issue by itsderick** [thoughtbot/bourbon#740]
```Syntax error: Invalid CSS after "    eot": expected ")", was ":   "#{$file-pa..."
        on line 22 of node_modules/node-bourbon/node_modules/bourbon/app/assets/stylesheets/helpers/_font-source-declaration.scss
        from line 28 of node_modules/node-bourbon/node_modules/bourbon/app/assets/stylesheets/_bourbon.scss
        from line 1 of src/scss/styles.scss```

Is this a bug? I'm pretty sure it was compiling just fine a day ago.

**Comment by itsderick** [comment]
Update: I changed from ```grunt-contrib-sass``` to ```grunt-sass``` and everything seems to compile fine now so I guess it's a problem with grunt-contrib-sass?

**Comment by tysongach** [comment]
Hard to say. It looks like grunt-contrib-sass uses Ruby Sass, so it would depend on what version you have installed. grunt-sass uses LibSass, so it’s a different ballgame. Let us know if the issue persists.

**Comment by evanjmg** [comment]
I got the same issue. It worked once in one of my projects and not in another
