### ISSUE TITLE
Size mixin breaking with single argument

### ISSUE THREAD

**Issue by jeffdill2** [thoughtbot/bourbon#742]
When only passing a single argument to the `size()` mixin, such as:

    & img {
      @include size(100%);
    }

the following error is thrown:

    Mixin size is missing argument $height.

Interestingly enough, if I copy the mixin code and throw it in my own CSS file, changing nothing but the name of the mixin (just to differentiate it), it works. So, when I put this mixin in my file:

    @mixin jeff-size($value) {
      $width: nth($value, 1);
      $height: $width;

      @if length($value) > 1 {
        $height: nth($value, 2);
      }

      @if is-size($height) {
        height: $height;
      } @else {
        @warn "`#{$height}` is not a valid length for the `$height` parameter in the `size` mixin.";
      }

      @if is-size($width) {
        width: $width;
      } @else {
        @warn "`#{$width}` is not a valid length for the `$width` parameter in the `size` mixin.";
      }
    }

then doing this works just fine :confused: :

    & img {
      @include jeff-size(100%);
    }

**Comment by tysongach** [comment]
Well that’s weird!

Can you provide more context on your environments (Sass version, any frameworks used, etc.)?

**Comment by jeffdill2** [comment]
It is very weird :confounded: 

Framework is Rails 3.2.18.

Bourbon gem version is 3.2.3. I actually tried updating this to 4.2.3 and it still didn't work, so I reverted back.

Sass gem version is 3.2.1.

If there's any other info you can think of that would be helpful, please let me know. Thanks!

**Comment by tysongach** [comment]
Thanks for the info!

Bourbon `3.2.3` is fairly old at this point. I’m unable to reproduce the issue using that version, but this does feel like a version/dependency issue.

The `size` mixin you posted above is from Bourbon `4.2.3`, which is quite a bit different from what it was in version `3.2.3`. I can’t remember for sure, but maybe it doesn’t work with just a single value.

Have you tried passing two arguments, and does it work?

```
@include size(100%, 100%);
```

When you upgraded to Bourbon `4.2.3`, did you also update to the latest version of Sass (it would need `3.4`+)? Such a large version bump would also require many other updates to features that were changed or removed, so watch out for those.

**Comment by jeffdill2** [comment]
Yeah, it works when I pass two arguments - so it's really not a big deal if
I can't get the single argument working.

And yes, I also upgraded Sass when I upgraded Bourbon (and Haml, because of
dependency issues, just FYI). For some reason it still didn't work. But I'm
sure it's got to be something on my end, since nobody else has brought it
up as an issue. So I'll keep messing with it to see if I can figure out the
issue. :-)

Thanks!

**Comment by joshuaogle** [comment]
@jeffdill2 is it possible there is a different `size` mixin coming from somewhere else? Bootstrap has one that does only take two arguments and would throw an error like that.

**Comment by jeffdill2** [comment]
Oh wow, good call! Yep, that's exactly what it was. I just changed the import order to bring in Bourbon *after* Bootstrap and it works perfectly now. :relieved:

Thanks @joshuaogle! And @tysongach , thanks for humoring me with my brain-fart. :smiley: 

Closing this issue now.

**Comment by tysongach** [comment]
Ha, good call @joshuaogle!

**Comment by Killerblade** [comment]
I agree with thanks for the help
