### ISSUE TITLE
Bourbon 5.0 flex-gutter() removed

### ISSUE THREAD

**Issue by qburns** [thoughtbot/bourbon#743]
I've been looking at the 5.0 branch to see which features are being deprecated to prepare myself in advance. I've noticed the flex-gutter() feature is being removed. I've been using it to generate the same padding as my gutter.

What would be considered best practice for this now?

**Comment by tysongach** [comment]
We actually deprecated that in [`4.1`](https://github.com/thoughtbot/bourbon/releases/tag/v4.1.0), but it just throws a warning for now until it’s fully removed in 5.0. We suggest using [Neat](https://github.com/thoughtbot/neat), instead.

**Comment by qburns** [comment]
Ah, I wasn't aware the function had been moved into Neat. I'm using that, just was going through the deprecation list trying to ensure I'm ready for 5.0. 

Thanks!
