### ISSUE TITLE
@charset should only output once

### ISSUE THREAD

**Issue by kaaaahhhhnnnn** [thoughtbot/bourbon#745]
```scss
@charset "utf-8";
@charset "utf-8";
```

should only show up once.

**Comment by tysongach** [comment]
Can you provide more detail than this? Where are you seeing this? How are you compiling your Sass?

**Comment by kaaaahhhhnnnn** [comment]
I'm importing bourbon which, for whatever reason, has `@charset "utf-8";` at the top of a bunch of files.  It doesn't directly export anything else, so the result is:

```scss
@charset "utf-8";@charset "utf-8";@charset "utf-8";@charset "utf-8";
@charset "utf-8";@charset "utf-8";@charset "utf-8";@charset "utf-8";
<the rest of my css>`
```

**Comment by elomatreb** [comment]
What are you using to compile your Sass? This does not happen with any tool I'm using, but it could be a implementation-specific bug (libsass likes those).

**Comment by kaaaahhhhnnnn** [comment]
yikes, sorry... meant to post this to the pyscss project ;)
