### ISSUE TITLE
Circle mixin

### ISSUE THREAD

**Issue by audetpascale** [thoughtbot/bourbon#746]
Hi,

Is it possible to do a circle mixin such as

```sass
@mixin circle($width) {
  border-radius: $width/2;
  height: $width;
  width: $width;
}
```

Is it not an heavy thing, and kind of related to the triangle mixin... But maybe there is a good reason not have that mixin.

Thanks for the info.

**Comment by treki** [comment]
This more of a SASS question.. try this..
@mixin circle($width, $color) {
  width: $width;
  height: $width;
  background: $color;
  -webkit-border-radius: $width/2;
     -moz-border-radius: $width/2;
          border-radius: $width/2;
}
 
.circle {
  @include circle(200px, #999);
}

**Comment by isochronous** [comment]
Why is it a SASS question?  He's asking if they can add that mixin to the library, not how to create the mixin.

**Comment by jpdevries** [comment]
+1 for adding it

ps: it's Sass not SASS
http://sassnotsass.com

**Comment by tysongach** [comment]
Bourbon’s `size()` mixin helps here. I don’t think a `circle()` mixin is necessary, as the code is already very straightforward:

```scss
.circle {
  @include size(100px);
  border-radius: 50%;
}
```

**Comment by audetpascale** [comment]
@treki : As @isochronous said, this is about to add the mixin, not how to do.

@tysongach : Well, yes, the `size` mixin helps. However, this is still a static class and could be done with a sub-optimal way, instead of a optimal mixin.

**Comment by tysongach** [comment]
@audetpascale It was just an example…obviously you could take what I posted above and create a mixin instead:

```scss
@mixin circle($width) {
  @include size($width);
  border-radius: 50%;
}
```

This is similar to your approach, but a bit DRY’er and with less logic for the `border-radius` value. It’s quite simple already, hence my hesitation to add it to the library. Ultimately, it all depends on context and project needs. So if you find a `circle()` mixin to be valuable for your project, I’d encourage you to just add it along with any other custom mixins you have. Bourbon is just the beginning; it doesn’t have to be exclusive.

**Comment by audetpascale** [comment]
Your call, I was just asking. However, less logic means less performance also.

**Comment by tysongach** [comment]
Sorry, I may have not been clear enough! I was specifically talking about having less Sass logic for the `border-radius` value. You had `width / 2`, which requires Sass to mathematically compute that, whereas a value of `50%` accomplishes the same with zero computation. This would be _more_ performant because it’s just plain CSS. Any way, this really doesn’t have much to do with a mixin or no mixin.
