### ISSUE TITLE
Documentation broken link: Border Radius

### ISSUE THREAD

**Issue by abea** [thoughtbot/bourbon#749]
Hey there. The 'view source' link next to [Border Radius](http://bourbon.io/docs/#border-radius) is broken right now. Currently linking to https://github.com/thoughtbot/bourbon/blob/master/app/assets/stylesheets/css3/_border-radius.scss.

It should go here, maybe: https://github.com/thoughtbot/bourbon/blob/master/app/assets/stylesheets/addons/_border-radius.scss

Border-style and border-width 'view source' links are similarly broken. I'm guessing: 
https://github.com/thoughtbot/bourbon/blob/master/app/assets/stylesheets/addons/_border-width.scss
https://github.com/thoughtbot/bourbon/blob/master/app/assets/stylesheets/addons/_border-style.scss

**Comment by tysongach** [comment]
Fixed. Thanks for the heads up!
