### ISSUE TITLE
Transition over filter?

### ISSUE THREAD

**Issue by rahul-rkt** [thoughtbot/bourbon#750]
The following code works perfectly in Firefox and Safari, but not in Chrome or Chrome Canary.

```sass
.logo
    +background-image(url(#{$logo}))
    background-size: contain
    position: absolute
    display: block
    +size($logo-dimension)
    top: 0px
    left: -($logo-dimension/2)
    +filter(grayscale(100%))
    +transition-on(filter)

.logo:hover
    +filter(grayscale(0%))
```

Does Chrome not support transitions over filter?

Because something like this works as intended in all of the aforementioned browsers:
```sass
.text
    position: absolute
    display: block
    font-size: 32px
    color: $color-white
    +transition-on(color)

.text:hover
    color: $color-red
```

**Comment by elomatreb** [comment]
You have to prefix the property in the transition declaration for webkit, sadly.

```sass
transition-property: filter -webkit-filter
```

**Comment by rahul-rkt** [comment]
Thanks, that worked. But cannot this be added in Bourbon?

**Comment by joshuaogle** [comment]
Since [we're switching to Autoprefixer](https://github.com/thoughtbot/bourbon/issues/702) to handle things like that, it won't be added to Bourbon.

I've used something like @elomatreb's solution that still ends up being easy:
```
@include transition(filter 250ms ease-in-out, -webkit-filter 250ms ease-in-out);
```
