### ISSUE TITLE
Multiple values with transition-delay

### ISSUE THREAD

**Issue by DevanB** [thoughtbot/bourbon#751]
Hello, I'm curious if you can use multiple values with `transition-delay`. The documentation doesn't show multiple values and my testing hasn't yielded successful results.

I have been successful with pure CSS but unsuccessful using the mixin like below.

`+transition-delay(0.3s, 0s)` nor `+transition-delay(0.3s 0s)`

**Comment by tysongach** [comment]
Hi!

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/transition-duration), the CSS syntax does allow multiple values that are comma separated…so we’re shooting for this output:

```css
transition-duration: 0.3s, 0s;
```

My quick test shows that Bourbon’s mixin does output multiple values correctly: 

_Sass_

```scss
div {
  @include transition-delay(0.3s, 0s);
}
```

_CSS output_

```css
div {
  -webkit-transition-delay: 0.3s, 0s;
  -moz-transition-delay: 0.3s, 0s;
  transition-delay: 0.3s, 0s;
}
```

Is this different than what you’re seeing? If so, what version of Sass are you using and how are you compiling it? What is your output?

Also, it might be worth noting that prefixing CSS transitions is hardly needed any more. Per [Can I Use](http://caniuse.com/#feat=css-transitions), Android Browser 4.3 and before is about the only thing that needs them. All of the other major browser version supports transitions with no prefixing. If you _do_ need prefixes to support a particular browser, I’d recommend using Autoprefixer.

**Comment by tysongach** [comment]
Closing due to lack of response.

**Comment by nagman** [comment]
Digging this topic out.

Actually, in September 2017, MDN says that you can use comma separated values for transition-delay, but I can't make it work in any browser.

On [this article](https://tympanus.net/codrops/css_reference/transition-delay/), there is a demo (the third one) but it doesn't work. So apparently it is officially supported but not concretely supported.

Alas...

**Comment by nagman** [comment]
Woopsies! My bad. You CAN actually use multiples values for transition-delay.
My test was wrong :/
As well as the article example, apparently.
