### ISSUE TITLE
bourbon 5.0

### ISSUE THREAD

**Issue by mmjaeger** [thoughtbot/bourbon#762]
Hello
First was wondering what the timeframe is for 5.0 - second, can 5.0 be used with the current versions of Neat, Bitters and Refills?

Thanks

**Comment by tysongach** [comment]
No timeframe as of now, but it’s coming along and the dev branch can be found here: https://github.com/thoughtbot/bourbon/tree/bourbon-v5.0.0

Neat may no longer have a Bourbon dependency at all in future versions and Bitters will get a very small update to work with Bourbon 5. Refills will need a bit more work to be compatible.
