### ISSUE TITLE
flex grid

### ISSUE THREAD

**Issue by mmjaeger** [thoughtbot/bourbon#771]
hello
I'm a little confused when it comes to flex grid - it's stated that this is going to be deprecated and moved over to Neat - is it going to stay for good but in Neat or is it moved over to Neat and then deprecated anyway?

**Comment by tysongach** [comment]
Duplicate of #770

@mmjaeger Let’s keep the conversation in one thread. I’ll reply in #770.

**Comment by mmjaeger** [comment]
sorry about that - didn't see the conversation so I thought it didn't get submitted
