### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by abea** [thoughtbot/bourbon#772]
The "View Source" link on Directional Property is currently broken, [linking here](https://github.com/thoughtbot/bourbon/blob/master/app/assets/stylesheets/addons/_directional-values.scss). I think I should be going to [this file](https://github.com/thoughtbot/bourbon/blob/master/app/assets/stylesheets/helpers/_directional-values.scss).

**Comment by tysongach** [comment]
Thanks for the heads up!
