### ISSUE TITLE
Eyeglass Module?

### ISSUE THREAD

**Issue by chriseppstein** [thoughtbot/bourbon#774]
Eyeglass is a Sass module manager for node-sass built on top of NPM. With a few small changes, this project can be as simple to install as `npm install --save bourbon`. Eyeglass users can then immediately import the sass files with no further configuration.

Are you interested? If so, I will send a small PR that makes the required changes.

**Comment by tysongach** [comment]
@chriseppstein Hi Chris! Thanks so much for reaching out; this sounds super neat and we’d love for Bourbon to be a part of Eyeglass!

We do already have an [existing npm package](https://www.npmjs.com/package/bourbon). What affect would this have on that? And the addition of Eyeglass-compatibility would help make imports much easier?

Please feel free to open a PR; it’s _super_ welcome!

**Comment by chriseppstein** [comment]
@tysongach It's just a few changes to your existing package.json and a new javascript file. Once you release with the changes, the existing bourbon npm module would be easier to install for eyeglass users and all the existing users would be unaffected.

I'll send a PR with the changes and updated documentation.

**Comment by tysongach** [comment]
eyeglass support added in 492cf56fe060d0a6380738a8be59c7361196897a
