### ISSUE TITLE
Change default scale for `modular-scale` function

### ISSUE THREAD

**Issue by whmii** [thoughtbot/bourbon#776]
Currently the default scale for the `modular-scale` function is Perfect Fourth (1.333). This is a pretty drastic scale and seems unlikely as a default typographic system. 
See http://modularscale.com/?1&em&1.25

I think it would make sense to switch the default value to something that can be more easily controlled out of the box. While it in not a large adjustment, I think Major Third (1.25) would be a better default. 
See http://modularscale.com/?1&em&1.25

<img width="883" alt="screen shot 2015-09-10 at 10 04 19 pm" src="https://cloud.githubusercontent.com/assets/2489247/9805543/ef6260de-5807-11e5-99b1-d707942256c6.png">

**Comment by tysongach** [comment]
Yeah, good call.

I’ve always found myself changing this to be less drastic, usually to either `$major-second` or `$major-third`. PR opened!

**Comment by tysongach** [comment]
Merged for `5.0`

**Comment by whmii** [comment]
muchas grasses
