### ISSUE TITLE
Prefix path to addons with bourbon

### ISSUE THREAD

**Issue by akshayrawat** [thoughtbot/bourbon#78]
Shouldn't

```scss
@import "addons/hide-text;
```

be

```scss
@import "bourbon/addons/hide-text;
```

Just like how the Compass framework allows importing its partials.

```scss
@import "compass/utilities/general/clearfix";
```

This will help me find where a mixin is coming from when I look at the import statement.

What do you think?

**Comment by tysongach** [comment]
We’ve restructured the Bourbon directories for [v5.0](https://github.com/thoughtbot/bourbon/tree/bourbon-v5.0.0) so that all of Bourbon’s partials are inside a `bourbon` directory.

**Comment by metaskills** [comment]
Thanks!!!

![bourbon](https://cloud.githubusercontent.com/assets/2381/8890972/1c79f982-32e3-11e5-8195-86eff3dd3a42.jpg)
