### ISSUE TITLE
"Error: Cannot find module '.'" when importing Bourbon using Eyeglass and Grunt

### ISSUE THREAD

**Issue by kohlmannj** [thoughtbot/bourbon#786]
Using http://eyeglass.rocks for Sass import path resolution is awesome, except when your build system chokes on things. I'm using Bourbon with Eyeglass and a Grunt-based Sass compilation setup, and I'm getting the following error when trying to run my `sass` Grunt task:

    >> Error: Cannot find module '.'
    >>     at Function.Module._resolveFilename (module.js:336:15)
    >>     at Function.Module._load (module.js:278:25)
    >>     at Module.require (module.js:365:17)
    >>     at require (module.js:384:17)
    >>     at Object.<anonymous> (/Users/kohlmannj/Sites/Projects/project-name-scrubbed/node_modules/bourbon/eyeglass-exports.js:1:77)
    >>     at Module._compile (module.js:460:26)
    >>     at Object.Module._extensions..js (module.js:478:10)
    >>     at Module.load (module.js:355:32)
    >>     at Function.Module._load (module.js:310:12)
    >>     at Module.require (module.js:365:17)

What's worse: this works perfectly on my personal machine, but fails as shown on my work machine. I've done a fresh `npm install` on the former and it still works; still broken on the latter. Completely stumped.

Sorry to just dump it in here, but I have spent multiple hours trying to figure out what's going on, to no avail. (Paging @chriseppstein and @eoneill, who was nice enough to reply to my Eyeglass issue posting.)

Edit: I know this is related to [eyeglass-exports.js:1](https://github.com/thoughtbot/bourbon/blob/master/eyeglass-exports.js#L1), but I haven't done enough Node development to understand why `require()` can't find this very module.

**Comment by eoneill** [comment]
Can you check which versions of `node` you're running (`node --version`)?

Can you also try editing `eyeglass-exports.js` and changing `require(".")` to one of... `require("./")`, `require("./index")`, `require(__dirname)`

**Comment by tysongach** [comment]
There’s an open PR, which will most likely resolve this. Apologies for taking time to release this patch; hope to today!

**Comment by eoneill** [comment]
Awesome! #782 for reference

**Comment by tysongach** [comment]
#782 has been merged with a fix.
