### ISSUE TITLE
border-radius mixin

### ISSUE THREAD

**Issue by hrgdavor** [thoughtbot/bourbon#787]
first thing I did after downloading bourbon was adding this to `addons/_border-radius.scss`

```scss
@mixin border-radius($radii) {
    @include border-top-radius($radii);
    @include border-bottom-radius($radii);
}
```
Is there a reason this variant is not included ?

**Comment by Toddses** [comment]
Since you're applying the border radius to all four corners, seems like it would be much easier with just doing the old fashioned way..

```css
.classname {
    border-radius: 5px;
}
```

**Comment by joshuaogle** [comment]
Hi @hrgdavor!
@Toddses is right, if you want all 4 corners, you can just use the regular css `border-radius` property, which [is really well supported](http://caniuse.com/#search=border-radius) these days.

The border-radius mixins are for when you want just two corners rounded and the other side straight (like in the case of a button bar). So you can use a single line and be a little clearer about what you are doing.

Hope that helps!

**Comment by hrgdavor** [comment]
Nice :) thanks for the clarification.
