### ISSUE TITLE
background-image with linear gradient not outputting with chosen

### ISSUE THREAD

**Issue by raldred** [thoughtbot/bourbon#788]
I'm using with bourbon with Rails along with the [chosen-rails](https://github.com/tsechingho/chosen-rails) gem, there seems to be some incompatibility, bourbon's background-image mixin doesn't work when chosen is present.

Anyone experienced this? 
Do you think this a bourbon or chosen-rails issue?

Edit: chosen relies on some compass mixins, i'm guessing that's where the problem lies.

**Comment by joshuaogle** [comment]
Hi @raldred,

It looks like chosen-rails is using Compass, which is probably what is causing the trouble. Compass uses some mixins with the same name as Bourbon and it's probably not a good idea to use both.

Of course I favor using Bourbon, so you might try giving one of the other gems a try, or as a last resort just adding Chosen into `vendor/assets/` (I know, I don't like having to do that either).

**Comment by tysongach** [comment]
@raldred Any update?

**Comment by raldred** [comment]
Heya yeh sorry, you're correct this the fault of chosen-rails.
I'm current in the process of patching to remove the Compass requirement, it's not necessary anyway because it should be built from the chosen source. Happy to close as nothing to do with bourbon really. :+1:
