### ISSUE TITLE
There is no -ms or -o for transform-style

### ISSUE THREAD

**Issue by himedlooff** [thoughtbot/bourbon#789]
It should be removed from the following function: https://github.com/thoughtbot/bourbon/blob/master/app/assets/stylesheets/css3/_transform.scss#L13-L15

MDN showing the prefixes: https://developer.mozilla.org/en-US/docs/Web/CSS/transform-style

**Comment by tysongach** [comment]
Hi!

According to [Can I Use](http://caniuse.com/#feat=transforms2d), IE9 uses the `-ms-` prefix for `transform` and Opera 11.5 uses the `-o-`, which is probably why they wound up in there.

That being said, Bourbon 5.0 will [no longer have prefixing features](https://github.com/thoughtbot/bourbon/issues/702).
