### ISSUE TITLE
transitions mixin doesn't seem to work as per documentation

### ISSUE THREAD

**Issue by doginthehat** [thoughtbot/bourbon#79]
The Bourbon docs on transition shows this example:

```
@include transition (all 2.0s ease-in-out);
```

That doesn't seem to work for me.

This css declaration:

```
test {
    @include transition(opacity 2.0s linear);
}
```

gets compiled to:

```
test { 
    -webkit-transition-property: opacity, 2s, linear; 
    -moz-transition-property: opacity, 2s, linear; 
    -ms-transition-property: opacity, 2s, linear; 
    -o-transition-property: opacity, 2s, linear; 
    transition-property: opacity, 2s, linear; 
    -webkit-transition-duration: 0.15s; 
    -moz-transition-duration: 0.15s; 
    -ms-transition-duration: 0.15s; 
    -o-transition-duration: 0.15s; 
    transition-duration: 0.15s; 
    -webkit-transition-timing-function: ease-out; 
    -moz-transition-timing-function: ease-out; 
    -ms-transition-timing-function: ease-out; 
    -o-transition-timing-function: ease-out; 
    transition-timing-function: ease-out; 
    -webkit-transition-delay: 0; 
    -moz-transition-delay: 0; 
    -ms-transition-delay: 0; 
    -o-transition-delay: 0; 
    transition-delay: 0; 
}
```

timing and delay is correct, but property and durations aren't.

If i use commas:

```
test2 {
    @include transition(opacity, 2.0s, linear);
}
```

Then the output is correct:

```
test2 { 
    -webkit-transition-property: opacity; 
    -moz-transition-property: opacity; 
    -ms-transition-property: opacity; 
    -o-transition-property: opacity; 
    transition-property: opacity; 
    -webkit-transition-duration: 2s; 
    -moz-transition-duration: 2s; 
    -ms-transition-duration: 2s; 
    -o-transition-duration: 2s; 
    transition-duration: 2s; 
    -webkit-transition-timing-function: linear; 
    -moz-transition-timing-function: linear; 
    -ms-transition-timing-function: linear; 
    -o-transition-timing-function: linear; 
    transition-timing-function: linear; 
    -webkit-transition-delay: 0; 
    -moz-transition-delay: 0; 
    -ms-transition-delay: 0; 
    -o-transition-delay: 0; 
    transition-delay: 0; 
}
```

However, as per docs commas should separate multiple transitions - 2nd example in the docs - not sure how this would work..

Environment:
- I'm running sass with `sass -r ./bourbon/lib/bourbon.rb style.scss style.css`
- `ruby --version` is `ruby 1.9.2p290 (2011-07-09 revision 32553) [x86_64-darwin11.2.0]` (using rbenv)
- `gem --version` is `1.8.10`
- `gem list --local bourbon` is `bourbon (1.4.0, 1.3.5)`
- `gem list --local sass` is `sass (3.1.12)`

**Comment by Maciekp** [comment]
Why it does not include -o-transition and -ms-transitions properties? In my case, bourbon is generating only -webkit, -o and transiton properties only

**Comment by tysongach** [comment]
@Maciekp Per [Can I Use data](http://caniuse.com/#feat=css-transitions), `-ms-` prefixes were never needed (it went straight to spec implementation in IE 10) and Opera had the `-o-` prefix _only_ in version 11.5, which is super out of date now.

Also, I’d recommend using [Autoprefixer](https://github.com/postcss/autoprefixer) for your prefixing needs. It has tons of benefits over using Bourbon for prefixing, so much so, that Bourbon v5.0 will [no longer have prefixes](https://github.com/thoughtbot/bourbon/issues/702).
