### ISSUE TITLE
Tried an example listed on the website, doesn't compile correctly

### ISSUE THREAD

**Issue by GloriousUnicorn** [thoughtbot/bourbon#790]
```
section {
  @include linear-gradient(to top, red, orange);
}
```
Using Prepros I get this:
```
section {
  background-color: red;
  background-image: -webkit-linear-gradient(bottom, red, orange);
  background-image: linear-gradient(to top,red, orange, , , , , , , , );
}
```
Is there something wrong in what I do or is it actually a bug?

**Comment by tysongach** [comment]
I’m not to familiar with Prepros, but if it uses LibSass then we’ve seen this bug before. You can find a discussion and fix here: https://github.com/thoughtbot/bourbon/issues/767

**Comment by GloriousUnicorn** [comment]
Oh, accordingly using Compass in Prepros compilers settings rather than Libsass I won't get errors, understood.

**Comment by tysongach** [comment]
@GloriousUnicorn Did that resolve your issue? Can this be closed?

**Comment by GloriousUnicorn** [comment]
Yes thank you.
