### ISSUE TITLE
`retina-image` should apply background size even in normal resolution

### ISSUE THREAD

**Issue by vojto** [thoughtbot/bourbon#792]
https://github.com/thoughtbot/bourbon/blob/8e7e36e01c47194d83951fb6315c5b26a008f2b7/app/assets/stylesheets/addons/_retina-image.scss

If I want browser to resize image even in normal resolution, I currently have to write this:

```sass
@include retina-image(foo, 50px 50px);
background-size: 50px 50px;
```

`retina-image` should do this automatically as to DRY code above:

```sass
@include retina-image(foo, 50px 50px);
```

**Comment by smth** [comment]
I was lead to think the same when using `cover` as the size.

**Comment by tysongach** [comment]
@vojto Hello! Sorry for the delay. Couple things:

- Can you share code for your use-case?
- For the element you are applying this background image to, are you also declaring `width` and `height`?
- To @smth’s point: typically applying `background-size: cover` accomplishes the same goal without having to declare exact length values. Does this match your use-case?

We actually (as of now) have removed the `retina-image` mixin in v5.0 (currently in beta). I think the huge uptick in SVG usage, newer CSS features such as `object-fit` and `cover`/`contain`, etc. have rendered this mixin less valuable.

**Comment by tysongach** [comment]
I’m going to close this, but please let us know if what I posted above doesn’t work or if I’m misunderstand the original issue/question. Thanks!
