### ISSUE TITLE
Installing w Rails 

### ISSUE THREAD

**Issue by jessieay** [thoughtbot/bourbon#795]
Just followed the instructions and added the gem, bundled, then added `@import` statement to my `application.scss` file and ...I just don't know how to proceed.

Syntastic is telling me "File to import not found or unreadable: bourbon." - was I supposed to actually install the files in the assets dir? I can get it to work with `bourbon install ` and requiring `bourbon/bourbon` but those are not the instructions for Rails.

**Comment by tysongach** [comment]
@jessieay Interesting! Does `bourbon` show in your `Gemfile.lock`? If so, what version are we using?

Also, do we have any Sprockets directives in our `application.scss`?

**Comment by jessieay** [comment]
Here is my WIP commit https://github.com/18F/dolores-landingham-bot/compare/jy-style-fun?

**Comment by jessieay** [comment]
appear to be using `bourbon (4.2.5)`

**Comment by jessieay** [comment]
Also, the app might be kind of a pain to set up for you locally bc of auth etc so let me know if you want more details from my dev environment! :100:

**Comment by jessieay** [comment]
Sooooo it seems like the grid settings are working. Perhaps this is a syntastic issue rather than a Bourbon issue...

**Comment by tysongach** [comment]
@jessieay You’re setup and imports all look good. In fact, this is pretty vanilla and is a good move, going away from flat files in the source, to using the gems…

This is a stretch, but have you tried a `rake tmp:clear` after making all these changes?

Are you able to pull this branch down and compile on another person’s machine?

**Comment by tysongach** [comment]
Oh! Wait a minute…I think someone just recently mentioned that Syntastic doesn’t like Bourbon’s import for some reason…

**Comment by tysongach** [comment]
@jessieay This may be of relevance: https://github.com/scrooloose/syntastic/issues/90

**Comment by jessieay** [comment]
ahh yes, definitely a syntastic issue. Thanks for the quick turnaround and help, AS ALWAYS

:rainbow: :+1:

**Comment by tysongach** [comment]
@jessieay Of course!
