### ISSUE TITLE
Sass finding error when I import Bourbon/Bitters/Neat for Jekyll

### ISSUE THREAD

**Issue by loganegbert** [thoughtbot/bourbon#798]
Trying to get Bourbon up and running with a Jekyll site.

All of the files are in the _sass directory (default for Jekyll imports). The main.scss file is in a scss directory, the subsequent css file will be output to a css folder.

I put the following into that main scss file:
>
@import "bourbon/bourbon";
@import "neat/neat";
@import "base/base";

When I run sass -w scss:sss I get:

> error scss/main.scss (Line 5: Invalid CSS after "...ourbon/bourbon"": expected "{", was ";")

Any thoughts on what might be going wrong here? 

I've made a non-jekyll project folder and sass runs without error.

**Comment by tysongach** [comment]
@loganegbert What version of Jekyll are you using?

**Comment by loganegbert** [comment]
@tysongach v3.0.0

**Comment by loganegbert** [comment]
Sass v3.4.19 FWIW

**Comment by loganegbert** [comment]
@tysongach according to the folks at Jekyll, the YAML frontmatter is what's causing Sass to have issues. But that still means that Jekyll's Sass converter is not importing Bourbon for some reason.

**Comment by tysongach** [comment]
@loganegbert Are you still having issues?

I just had a chance to do some testing. I’m finding Jekyll’s docs to be quite vague and confusing around this.

Per the docs (http://jekyllrb.com/docs/plugins), I tried adding `gems: [bourbon]` to my `_config.yml` (and then running `gem install bourbon` from the command line), but it was not working properly.

However, I _did_ get Bourbon importing correctly if I created a `Gemfile` and added:

```
group :jekyll_plugins do
  gem "bourbon"
end
```

It yelled at me to also add three:

```group :jekyll_plugins do
  gem "bourbon"
  gem "kramdown"
  gem "rouge"
  gem "jekyll-watch"
end
```

…but then finally did load up and properly compile the Sass.

This doesn’t sound like a great solution, but it did work. I would reach out to the Jekyll community for more help or to ask for the best solution here.

**Comment by christiantype** [comment]
@tysongach ,  you lost me at:

```
However, I did get Bourbon importing correctly if I created a Gemfile and added:

group :jekyll_plugins do
  gem "bourbon"
end
```

**Comment by tysongach** [comment]
@christiantype That appears to be an importing error somewhere around where normalize is being added. Is your code available for me to look at? Or can you post your main Sass manifest file?

**Comment by christiantype** [comment]
@tysongach , my project: [link](https://github.com/christiantype/jekyll-bourbon-test)

I'm using an existing Jekyll theme created by somebody else, and I'm trying to incorporate Bourbon and Neat in order to make a few changes and match my existing site which uses Bourbon and Neat. 

Thanks for helping out. Let me know if you have any questions. 

As of right now, this is what I am getting in terminal:

```
Christians-MacBook-Pro:jekyll-bourbon-test christians$ jekyll serve
WARN: Unresolved specs during Gem::Specification.reset:
      rb-fsevent (>= 0.9.4, ~> 0.9)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
jekyll 3.3.0 | Error:  (/Users/christians/Documents/jekyll-bourbon-test/_config.yml): could not find expected ':' while scanning a simple key at line 70 column 1
Christians-MacBook-Pro:jekyll-bourbon-test christians$ 
```

**Comment by tysongach** [comment]
@christiantype It looks like you have Bourbon and Neat [included as static files within your `_assets` directory](https://github.com/christiantype/jekyll-bourbon-test/tree/master/_assets), which means you do not need to put them in your Gemfile or Jekyll config. You should choose to include statically, _or_ via the gem-based asset manager.

If you do want to use the gems instead, you need to define the `jekyll_plugins` block in your `Gemfile`, not `_config.yml`

```ruby
# Gemfile
group :jekyll_plugins do
  gem "bourbon"
  gem "neat"
end
```

**Comment by christiantype** [comment]
@tysongach, thank you so much! Everything is working fine now. 

So what is the difference between including static files or via a gem-based asset manager?

**Comment by tysongach** [comment]
> So what is the difference between including static files or via a gem-based asset manager?

@christiantype Asset managers make it easy to manage your project’s dependencies and are they version-aware, which makes it possible to change a version number in a config (like a `Gemfile` for gems) and upgrade to a new version of a library or plugin. When including assets statically in a project, upgrading would mean manually replacing a directory of files for a library with new ones. This leads to really large Git commits that are not project feature development, but just updating dependencies, so your history and pull requests get a bit muddy.

**Comment by christiantype** [comment]
Okay, I think I got it. So if I update the version number in the config, would it automatically update my local folder with new files? That's what always confuses me.

**Comment by tysongach** [comment]
> would it automatically update my local folder with new files

Sort of. With gems, we use [Bundler](http://bundler.io/), which gives you the `bundle` command. From the command line, you run `bundle update gem_name` (e.g. `bundle install bourbon` or `bundle update bourbon`) in your project’s directory. It will looks at your project Gemfile, and see if there is a new version of that gem to update to. It installs these gem files not in your project directory, but in a special place on your local computer. Any project that needs those gems can reference them. So the gem files are not stored or committed within the project, but _referenced_.

**Comment by christiantype** [comment]
@tysongach, if the gem files are not stored in the project directory, how can I make edits to them? For instance, what if I want to explore certain files within the gem and see the structure of, let's say a css file?

**Comment by tysongach** [comment]
@christiantype You should not edit gem files. Consider them third-party libraries in which you interact with them via their API. Editing them would cause upgrading to be a pain.

Let’s move this conversation elsewhere, as this is outside of this issue, and Bourbon itself.
