### ISSUE TITLE
Border-width mixin

### ISSUE THREAD

**Issue by addic** [thoughtbot/bourbon#799]
I have noticed that the bourbon `border-width` mixin is irrelevant to use anymore as instead of it one can use a css shorthand `border-width: top, right, bottom, left`. As a result, the output will have only one line of code instead of 1 to 4 lines:
```
border-width: 1em 20px 0 100%;
```
Instead of:
```
border-top-width: 1em;
border-right-width: 20px;
border-left-width: 100%;
```
The only difference i can see is if you do not want to set a value to 0, you would use the mixin with null in place of that direction - which might not be worth it.

Please correct me if i am wrong :).

**Comment by tysongach** [comment]
@addic Hi! Yes, you are totally right in that the one difference is we allow for the use of `null` values. This effectively “skips” a side on output. We do this so to not force “accidental resets”; more on that here: https://css-tricks.com/accidental-css-resets

It’s a nuanced feature, for sure, and is not _always_ needed.
