### ISSUE TITLE
Transition Mixin breaks with transform

### ISSUE THREAD

**Issue by ytripet** [thoughtbot/bourbon#800]
Transform inside a transistion mixin makes all transition riming set to 0

**Comment by laicosly** [comment]
How did you resolve this?  I'm having issues with transitioning transform, where the time/ease properties are not included in the .css output.

If I transition all, bourbon outputs:
```
// .scss syntax
@include transition(all 500ms $ease-in-out-expo);
// .css output
transition: all 500ms cubic-bezier(1, 0, 0, 1);
```

but if I transition transform bourbon doesn't include the time or ease
```
// .scss syntax
@include transition(transform 500ms $ease-in-out-expo);
// .css output
transition: transform;
```

**Comment by tropperstyle** [comment]
I am having this same issue. It used to work in previous versions but I recently updated dependencies and this bit me.

**Comment by tropperstyle** [comment]
For anyone else, after a little more digging: https://github.com/thoughtbot/bourbon/issues/794
