### ISSUE TITLE
Point package.json main to the same file as bower.json main

### ISSUE THREAD

**Issue by danielsiwiec** [thoughtbot/bourbon#802]
I believe those two values should be the same. The effect of the discrepancy I'm observing, is wiredep cannot wireup bourbon's npm package (package.json), while it works fine with bower (bower.json). There might be other effects.

Neat doesn't have this issue - both package.json and bower.json point correctly to the right sass file.

**Comment by danielsiwiec** [comment]
@tysongach Could you take a look at some point?

**Comment by tysongach** [comment]
Hi @danielsiwiec!

We point npm (via `package.json`) to `index.js` so we can resolve import paths. This was changed in https://github.com/thoughtbot/bourbon/commit/36c2d5576f1fe9dbdfd9543e15064c5a4a16343e. We are also going to do the same for Neat: https://github.com/thoughtbot/neat/pull/397

I haven’t used wiredep, but I believe we are aligning to the guidelines for both npm (https://docs.npmjs.com/misc/developers#the-package-json-file) and Bower (https://github.com/bower/spec/blob/master/json.md#main).

**Comment by FDiskas** [comment]
Some bundlers like `parcel` can't resolve`bourbon` when included in scss because of the `main` entry in `package.json` file. Please change the main entry point to same path as it is in `style` = `"core/_bourbon.scss",` :notes:
