### ISSUE TITLE
Defining $all-text-inputs-invalid ?

### ISSUE THREAD

**Issue by tesujimath** [thoughtbot/bourbon#804]
I'm just getting started with Bourbon, so there may be a better way to do this.  But it seems to me useful to define a new all-text-inputs-* variable for styling invalid input.  Along the lines of [Bourbon Text Inputs](http://bourbon.io/docs/#text-inputs), I have done this:

    $all-text-inputs-invalid: assign-inputs($text-inputs-list, invalid);

which enables me to write this:
    
    #{$all-text-inputs-invalid} {
        border: 1px solid #f00;
    }

I was surprised not to find something like this in Bourbon already.  Would it be a useful addition?

**Comment by joshuaogle** [comment]
That does seem like an oversight. Go for it!
