### ISSUE TITLE
unicode-range in @font-face mixin

### ISSUE THREAD

**Issue by johanneskrtek** [thoughtbot/bourbon#806]
i am missing the possibility to add the `unicode-range` descriptor in the @font-face mixin. are there plans to add this feature by any chance?

**Comment by joshuaogle** [comment]
I haven't heard of any plans for it yet, but that may be because it's [not widely supported](http://caniuse.com/#feat=font-unicode-range). It would be a good optional parameter. Would you want to submit a PR?

**Comment by johanneskrtek** [comment]
You are right, `unicode-range` is only supported partially by most of the browsers. But once Firefox and Opera Mini jump on the train it may become quite handy. Please have a look at the PR #808 – Travis CI seems to have got stuck somehow.

**Comment by HugoGiraudel** [comment]
I think simply adding `@content` in the mixin would allow authors to pass in any extra thing they want, including `unicode-range`. :)

**Comment by johanneskrtek** [comment]
I like the idea of passing a block for optional parameters!

**Comment by tysongach** [comment]
As of 235671948ef3a9c343c4391d250082a0373c8d83, you can now pass `@content` into the `font-face` mixin; which perfectly solves this issue:

```scss
@include font-face(
    "calibre",
    "fonts/calibre"
  ) {
  unicode-range: U+26;
}
```

**Comment by johanneskrtek** [comment]
Yeah, thanks!
