### ISSUE TITLE
bourbon 4.2.6, issues with sprockets-rails 3.0.0

### ISSUE THREAD

**Issue by railsmechanic** [thoughtbot/bourbon#814]
After updating to sprockets-rails 3.0.0 (update to Rails version 4.2.5) I'm receiving various
```Sass::SyntaxError - Undefined mixin``` errors.

Commenting out the affected mixins leads to other ```Sass::SyntaxError - Undefined mixin``` errors.
Locking sprockets-rails to version 2.3.3 fixes the issue.

**Comment by tysongach** [comment]
Hi @railsmechanic!

I finally had a chance to look into this a bit. I also had issues, but mine were related to importing and that Bourbon “could not be found”.

I don’t have a solution yet, but we’ll be looking into it…

**Comment by railsmechanic** [comment]
:+1:

**Comment by tysongach** [comment]
@railsmechanic What version of Bourbon are you using?

Also, is this code open-source anywhere that we can see it? If not, can you share with us a code sample that gives us an indication of the mixins that you’re using?

So far, we’re unable to re-create with the precise versions you mention above.

**Comment by railsmechanic** [comment]
@tysongach I fixed the issue. It was a naming conflict in one of my .scss files.
You can close this issue. 

Many thanks :+1:

**Comment by tysongach** [comment]
cc: @dgalarza
