### ISSUE TITLE
ERROR:  While executing gem

### ISSUE THREAD

**Issue by anartfulscience** [thoughtbot/bourbon#820]
Hello,

I'm trying to install bourbon and neat and I'm having some issues that I hope you could help with. I'm on the Mac, OS X El Capitan.

If I try and install `gem install bourbon`
I get the error 

```bash
ERROR:  While executing gem ... (Gem::FilePermissionError)
You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.
```

I have tried using `sudo` and get 

```bash
ERROR:  While executing gem ... (Errno::EPERM)
Operation not permitted - /usr/bin/bourbon
```

If I try and install via npm or bower and try and link to the scss file as below it's doesn't work either `../node_modules/bourbon/app/assets/stylesheets/bourbon`

Also if I try and install neat it gives me a bourbon-neat folder which looks like a production folder?

My directory setup is

```
node_modules/
dist/
src/scss/
```

Kind regards, Stephen

**Comment by tysongach** [comment]
@anartfulscience Are you able to install other gems or npm modules, or does this only happen when installing Bourbon? It appears to be issue with permissions on your specific machine. Trying to install something else could be a good gut check.

**Comment by tysongach** [comment]
Closing due to lack of response.
