### ISSUE TITLE
Where are the mixins for the npm install?

### ISSUE THREAD

**Issue by Smolations** [thoughtbot/bourbon#855]
I am trying to switch from using the github repo for this package to using the npm package. However, looking at the contents of the package, I can't seem to find the same `_bourbon.scss` file to import into my main sass file! Please tell me that the npm version of this mixin library actually _has_ mixins... 😥

**Comment by Smolations** [comment]
For reference, I am using bourbon v4.1.1 and node v4.2.4.

**Comment by Toddses** [comment]
Should be under `/node_modules/app/assets/stylesheets/_bourbon.scss`

**Comment by whmii** [comment]
Yep, that's it, you'll need to import all of bourbon since the mixins and functions are interdependent.

Use the path that @Toddses posted above. you can see it in the repo [here](https://github.com/thoughtbot/bourbon/blob/v4-stable/app/assets/stylesheets/_bourbon.scss)

**Comment by Smolations** [comment]
Yup, I _just_ got back here because I discovered that the module is getting munged due to my package manager, [jspm](http://jspm.io). I did a regular `npm install bourbon` and everything is present and accounted for.

Sorry for wasting your time, but thanks for the reply!  :+1:

**Comment by Smolations** [comment]
Ugh, I forgot to specify the version I'm using when doing the install. LOL it's right in the code snippet I posted too!

Anyway, when I did `npm install bourbon@4.1.1`, it installed the module with the following directory tree (i didn't list the contents of some directories because they definitely don't have the mixins in them):
```
bourbon/
  _site/
    docs/
    docset/
    images/
    js/
    stylesheets/
      docs/
        docs.scss
      home/
        vendor/
          pygments/
            default.scss
        home.scss
      vendor/
        pygments/
          default.css
      docs.css
      home.css
    CNAME
    favicon.ico
    index.html
  spec/
  .hound.yml
  .npmignore
  .scss-lint.yml
  LICENSE.md
  package.json
  README.md
  sache.json
```

This install should be entirely reproducible. Maybe it has to do with the `package.json` and the supported node/npm versions? I don't know...

**Comment by Smolations** [comment]
Aha! I guess I will just have to upgrade.  :unamused: 

[Release v4.2.1](https://github.com/thoughtbot/bourbon/releases/tag/v4.2.1)
