### ISSUE TITLE
is't working with the only .scss extention?

### ISSUE THREAD

**Issue by jairorudas** [thoughtbot/bourbon#856]
Hi, bourbon working else with the .sass extention or only .scss extention? 

Thank so much!

**Comment by joshuaogle** [comment]
Hi @jairorudas. Yes, you can import it into a `.sass` file and it will work fine. You can use the Sass syntax for all of the mixins and functions.

(If you've downloaded the source files for some reason those will need to stay the `.scss` filetype, but you probably haven't)

**Comment by jairorudas** [comment]
Thank very much @joshuaogle  for your help!!
