### ISSUE TITLE
File to import not found or unreadable: bourbon w/ npm scripts, node-sass`

### ISSUE THREAD

**Issue by drmanitoba** [thoughtbot/bourbon#862]
Hey there,

I've got my deps set up as so:

``` json
  "devDependencies": {
    "eyeglass": "^0.8.2",
    "node-sass": "^3.4.2",
    "onchange": "^2.0.0"
  },
  "dependencies": {
    "bourbon": "^4.2.6"
  }
```

and I'm trying to use npm scripts to build this, though raw CLI fails as well,

``` json
  "scripts": {
    "sass": "node-sass --output-style compressed -o assets/css/ assets/css/src",
  },
```

and so far inside `assets/css/src` is my `screen.scss` file:

``` css
@import "bourbon";

// ...
```

When I run `npm run sass`, I get the following error:

`````` bash
{
  "formatted": "Error: File to import not found or unreadable: bourbon\n       Parent style sheet: /Users/giantrobotbee/Sites/giantrobotbee/content/themes/grb_theme/assets/css/src/screen.scss\n        on line 1 of assets/css/src/screen.scss\n>> @import \"bourbon\";\n   ^\n",
  "message": "File to import not found or unreadable: bourbon\nParent style sheet: /Users/giantrobotbee/Sites/giantrobotbee/content/themes/grb_theme/assets/css/src/screen.scss",
  "column": 1,
  "line": 1,
  "file": "/Users/giantrobotbee/Sites/giantrobotbee/content/themes/grb_theme/assets/css/src/screen.scss",
  "status": 1
}```

I'm running node 4.3.1. Any help is greatly appreciated. I'm sure it's something dumb that I'm overlooking. Thanks!
``````

**Comment by tysongach** [comment]
@drmanitoba You likely need to add Bourbon to your node-sass `includePaths`. Have you read the [section in our readme regarding Node-based asset pipelines](https://github.com/thoughtbot/bourbon#installing-with-npm-and-using-a-node-based-asset-pipeline)?

**Comment by drmanitoba** [comment]
Hey @tysongach, I was going off the line in your docs

> If you’re using Eyeglass, skip to Step 3.

Which I took to mean "install Eyeglass, and that's it". Is this not so?

**Comment by drmanitoba** [comment]
FWIW, I've updated the npm script to be the following

```json
  "scripts": {
    "sass": "node-sass --import-path node_modules/bourbon/app/assets/stylesheets --output-style compressed -o assets/css/ assets/css/src",
}
```
but I'm still getting the same error when running `npm run sass`. I've tried running this same command from the CLI manually, and it produces the error as well.

**Comment by tysongach** [comment]
@drmanitoba Ah, I didn’t see that you have `eyeglass` in there. I honestly haven’t had much experience with that yet, it’s new for us.

Perhaps @chriseppstein has some insight?

**Comment by jonalport** [comment]
@drmanitoba: try --include-path

**Comment by kgcreative** [comment]
adding the path to your include paths in your plugin configuration did the trick for me
```
  plugins: {
    sass: {
      options: {
        mode: 'native'
        , includePaths: [
            'node_modules/bourbon/core'
        ]
      }
    }
  }
}
```

**Comment by tysongach** [comment]
Closing this as we don’t have a response to the last two suggestions, but if this is still an active issue, please feel free to re-open.
