### ISSUE TITLE
Using bourbon with npm-sass

### ISSUE THREAD

**Issue by jtq** [thoughtbot/bourbon#864]
This is an issue I've run into with 4.2.3 specifically, but I believe it exists right up to HEAD.  I'm not sure if this is specifically an issue with bourbon (or if it's best fixed elsewhere), but there appears to be a conflict between the npm-sass module and bourbon.

[npm-sass](https://www.npmjs.com/package/npm-sass) is used to @import CSS files from node modules, but it tries to load a referenced module's SCSS files from either a <module>/styles folder, or from the folder specified in the module's package.json "style" declaration.

Bourbon expects the user to add its SCSS path (`require.resolve("bourbon")` / `require("bourbon").includePaths` depending on bourbon version) to SASS's includePaths, but when npm-sass is being used to load SCSS it appears to take over module-name-to-path resolution.  This means that when you `@import 'bourbon'` npm-sass goes looking in node_modules/bourbon/styles because it doesn't know to follow the bourbon package.json's (arguably overloaded) "main" declaration to node_modules/bourbon/app/assets/stylesheets/bourbon.

This can be easily fixed by adding a "style" declaration to bourbon's package.json pointing to the appropriate SCSS file location (`app/assets/stylesheets/_bourbon.scss` previously, now apparently just "core/_bourbon.scss"), which allows bourbon to play nicely with npm-sass.

**Comment by gwigz** [comment]
:+1:

**Comment by idcmardelplata** [comment]
Buen día, no se si sirva pero a mi no me da problemas con esta configuración en el gulpfile.js
```javascript
gulp.task('sass', function(){
    return gulp.src('./scss/**/*.scss')
    .pipe(sass().on('err', sass.logError))
    .pipe(gulp.dest("./dist/css"))
```
 
y bourbon lo tengo instalado dentro de la carpeta scss de esta manera:
* base/
* layouts/
* modules/
* plugins/
   * bourbon/
   * neat/  
   * _plugins-dir.scss
* styles.scss

y no me genera ningún problema al ejecutar la tarea.

**Comment by MsUzoAgu** [comment]
@tysongach Hi! Has this been fixed in `5.0`?  Looking through changes/package.json and can't find fix for this.

**Comment by tysongach** [comment]
Related: https://github.com/thoughtbot/bourbon/pull/978

**Comment by tysongach** [comment]
@MsUzoAgu No, not currently.

**Comment by tysongach** [comment]
#978 was just merged which should make imported Bourbon when used alongside npm-sass a lot easier.
