### ISSUE TITLE
Mixin Retina display

### ISSUE THREAD

**Issue by jairorudas** [thoughtbot/bourbon#869]
Hi, I can't to compile my project, because the output of console is this.

```
error app/styles/bourbon/css3/_hidpi-media-query.scss (Line 3: Illegal nesting: Only properties may be nested beneath properties.
```

Help me plase. Thank!

**Comment by jairorudas** [comment]
I use gulp-ruby-sass for to compile.

**Comment by tysongach** [comment]
@jairorudas Hi! What version of Bourbon are you using? Is the code open-source where I can see it? If not, can you show us the Sass where you are using Bourbon’s `hidpi()` mixin?

**Comment by jairorudas** [comment]
@tysongach this is the code.

@mixin hidpi($ratio: 1.3) { 
  @media only screen and (-webkit-min-device-pixel-ratio: $ratio),
    only screen and (min--moz-device-pixel-ratio: $ratio),
    only screen and (-o-min-device-pixel-ratio: #{$ratio}/1),
    only screen and (min-resolution: round($ratio * 96dpi)),
    only screen and (min-resolution: $ratio * 1dppx) {
    @content;
  }
}

**Comment by tysongach** [comment]
@jairorudas That’s the Bourbon source, but are you _using_ that mixin somewhere in your project?

**Comment by jairorudas** [comment]
Yes, here:
```
.newplain
  box-shadow: 0 0 36px 0 $sh-lightgreen !important
  &:after
    border: 1px solid $br-lightgreen !important
  &:before
  content: ""
    @include retina-image("../images/plano-escolhido", 60% !important)
```

**Comment by tysongach** [comment]
@jairorudas Are you using Sass’s indented syntax, not SCSS?

**Comment by whmii** [comment]
@jairorudas your indenting is off. Should be 



```sass
.newplain
  box-shadow: 0 0 36px 0 $sh-lightgreen !important
  &:after
    border: 1px solid $br-lightgreen !important
  &:before
    content: "" 
    @include retina-image("../images/plano-escolhido", 60% !important)
```

**Comment by jairorudas** [comment]
@tysongach Yes, but the problem is above the `&:before` I saw now, and runing normaly. the error disappeared

**Comment by whmii** [comment]
cool :+1:

**Comment by jairorudas** [comment]
Thank a lot @whmii @tysongach

**Comment by tysongach** [comment]
@jairorudas If you’re using the indented syntax, you include mixins with a `+`, not `@include`. So…

```scss
@include retina-image("../images/plano-escolhido", 60% !important)
```

…should be:

```sass
+retina-image("../images/plano-escolhido", 60% !important)
```

Reference: http://sass-lang.com/documentation/file.INDENTED_SYNTAX.html#mixin_directives
