### ISSUE TITLE
Missing Mixins?

### ISSUE THREAD

**Issue by CallumJHays** [thoughtbot/bourbon#874]
Hi. Sorry if this is silly, as I'm new to using bourbon and web development in general.
My problem is that _sass doesn't seem to recognise the 'background-image' mixin_ after importing bourbon core. I am just trying to follow simple examples in your documentation. 

Looking through the files both on my local machine and on this git repo, I can't find anything with the name **_background-image.scss**, despite other issues referencing the existence of this file. 
I am using nodejs and have used npm to install bourbon, using node-sass's **includePaths** option to make sure bourbon is being properly imported. 
What am I doing wrong?

**Comment by smth** [comment]
Possibly related, I'm getting an `Undefined mixin 'transition'` error with a new install of Bourbon (5.0.0).

**Comment by tysongach** [comment]
@CallumJHays @smth Hello! v5.0 removes all prefixing mixins from Bourbon, including `background-image` and `transition`. Here’s [our announcement describing why we’re doing this](https://github.com/thoughtbot/bourbon/issues/702), as well as our [change log](https://github.com/thoughtbot/bourbon/blob/master/CHANGELOG.md) which gives a break-down of what has been removed.

You could lock your version down to v4.x, or remove these mixins for vanilla CSS ([CSS gradients are well-supported](http://caniuse.com/#feat=css-gradients), as well as [transitions](http://caniuse.com/#feat=css-transitions)).

**Comment by eliland** [comment]
Could it be a good idea to mention specifically which mixins are removed in the changelog? It's not completely obvious by the name alone which are prefixing mixins and which are not, so I see how that could cause confusion (as it did with me just today when I Ctrl+F'd the changelog to find out what happened to the transition mixin and came up with nothing).

**Comment by tysongach** [comment]
@eliland Yep! I’m actually doing that right now…

**Comment by tysongach** [comment]
I’ve listed out all of the removed prefixing mixins in the change log in https://github.com/thoughtbot/bourbon/commit/33d4b779947ead76cc127fee96d175bfa86fc52f. cc: @eliland

**Comment by tysongach** [comment]
Hi all. I wanted to note that we realized today we (I) accidentally published `5.0.0-beta.2` to npm as a stable release, instead of a pre-release. So we unpublished `5.0.0-beta.2` to go back to `4.2.6` as the stable release. But I also published `5.0.0-beta.4` as a pre-release, so if you _do_ in fact want the beta, you can pull that one. Sorry for all of the confusion!

I’m going to close this as I think I’ve answered the original question. But no one hesitate to ask us anything else!

**Comment by morgler** [comment]
This doesn't work with the current version 0.1.0 of refills. Refills depends on these mixins. Do you have a propsed solution how to fix this? Should I use autoprefixer-rails and then rewrite all snippets created by refill manually?

**Comment by tysongach** [comment]
@morgler Yes, the current version of Refills is not ready for Bourbon 5. There’s no quick solution at the moment; basically we just need to work on Refills and release a new version which doesn’t utilize mixins removed in v5.

**Comment by jm-kumaresh** [comment]
Does this issue solved..? I'm using refills for my projects which requires bourbon.

**Comment by AndrewMcSwain** [comment]
It'd be a good idea to update the docs on the bourbon site................................................................. #justsayin

**Comment by heswebs** [comment]
It is completely a disaster! all the examples in bourbon that requires mixins will cause problem. currently being requested to use bourbon for a project but sadly I cant even get the navigation to work. Is there any way to use the older version of bourbon where 100% works with the examples you given?
