### ISSUE TITLE
Are mix-ins like animation() going to be removed?

### ISSUE THREAD

**Issue by Nyoho** [thoughtbot/bourbon#875]
The commit 5caaa70 removed `animation()` etc. 
Will not 5.0.0 contain such mix-ins like animation()?

**Comment by elomatreb** [comment]
Bourbon 5.0 removes the prefixing mixins. The purpose of these was nothing but adding the once needed vendor prefixes (e.g `-webkit-, -moz, -o-`).

There are two good reasons for dropping these mixins:

1. There are much better prefixing toolkits available today (Check out [autoprefixer](https://github.com/postcss/autoprefixer))
2. Many of the properties bourbon offered prefixing for are well-supported without prefixes today. `animation`, to come back to your question, is either supported without prefixes by all major browser or not supported at all (Opera Mini). See [caniuse](http://caniuse.com/#feat=css-animation) for more info.

**Comment by tysongach** [comment]
@Nyoho This is correct. Thanks for the run down @elomatreb!

Let us know if you have any questions.

**Comment by Nyoho** [comment]
I understand! Thank you for your explanation including autoprefixer, caniuse (useful!).
