### ISSUE TITLE
missing pixels to ems  function in version 5 beta 4

### ISSUE THREAD

**Issue by tvmaly** [thoughtbot/bourbon#877]
I was attempting to try some of the example code on the refills.bourbon.io page, but after compiling my scss to css I noticed the function  em(860) does not get translated.  I tried to search through all the code to find _px-to-em.scss that would contain the em function but it is no where to be found in the latest 5.0 version

**Comment by tysongach** [comment]
Hi @tvmaly. The `em()` and `rem()` functions [have been removed](https://github.com/thoughtbot/bourbon/blob/master/CHANGELOG.md#removed-2) in v5. The discussion around them being removed can be found here: https://github.com/thoughtbot/bourbon/issues/691.

That said, the source for the `em()` function can be [found here](https://github.com/thoughtbot/bourbon/blob/v4-stable/app/assets/stylesheets/functions/_px-to-em.scss), and [here](https://github.com/thoughtbot/bourbon/blob/v4-stable/app/assets/stylesheets/functions/_px-to-rem.scss) is the source for the `rem()` function. 

I’ll take a look at Refills today to get these removed from there.

**Comment by tvmaly** [comment]
I am still trying to grok your entire system, but I do understand you are transitioning to a new version.  Is there a version of the site examples on http://refills.bourbon.io/  that work with the latest version of bourbon/neat/refills/bitters ?  

I am using examples are my starting point to learn.

**Comment by tysongach** [comment]
@tvmaly Unfortunately, not yet. The current Refills does use some of the features that have been removed in Bourbon 5. That being said, it mostly uses Bourbon’s old prefixing mixins and it fairly easy to swap out. So _for example_, remove the `@include`s of Bourbon mixins for standard CSS:

```diff
- @include display(flex);
- @include flex-wrap(wrap);
- @include justify-content(space-between);
+ display: flex;
+ flex-wrap: wrap;
+ justify-content: space-between;
```

Of course, you’ll want to use Autoprefixer or other means to prefix the values above depending on what browsers you intend to support.

I plan to soon update Refills to be compatible with Bourbon 5. Appreciate the patience! This is indeed a major shift for the whole suite.

**Comment by tvmaly** [comment]
@tysongach I will wait for your update.  I am excited to try out the new version.  The examples on refills are very helpful.  Having these types of examples as stand alone files in a subfolder on github would be even more useful for those new to bourbon like myself.

**Comment by tysongach** [comment]
@tvmaly Here’s my WIP branch for updating Refills to Bourbon 5: https://github.com/thoughtbot/refills/tree/tg-bourbon-5.

Great to hear you find them useful; we hope to streamline them a bit in the future, make them a bit more flexible and future-friendly.

I’m going to close this issue now, but don’t hesitate to reach out with any questions you have.
