### ISSUE TITLE
NPM / Gulp Error: File to import not found or unreadable: bourbon

### ISSUE THREAD

**Issue by fschroiff** [thoughtbot/bourbon#883]
Fresh install, this is in my package.json:
```
  "dependencies": {
    "bourbon": "^4.2.6",
    "bourbon-neat": "^1.7.2"
  },
```

This is in my gulpfile:
```
  bourbon       = require("bourbon").includePaths,
  neat          = require("bourbon-neat").includePaths;
```

This is in my style.scss
```
@import "bourbon";
@import "neat";
```

This is the error I get:

```
Error in plugin 'sass'
Message:
    sass/style.scss
Error: File to import not found or unreadable: bourbon
       Parent style sheet: stdin
        on line 10 of stdin
>> @import "bourbon";
   ^
```

What changed? I have several other projects where this exact setup works fine.

**Comment by tysongach** [comment]
Hi @fschroiff! What Sass package are you using?

**Comment by fschroiff** [comment]
Hi @tysongach, I am using gulp-sass 2.2.0 (which uses node-sass 3.4.2).

**Comment by idcmardelplata** [comment]
Buen día, no se si sirva pero a mi no me da problemas con esta configuración en el gulpfile.js
```javascript
gulp.task('sass', function(){
    return gulp.src('./scss/**/*.scss')
    .pipe(sass().on('err', sass.logError))
    .pipe(gulp.dest("./dist/css"))
```
 
y bourbon lo tengo instalado dentro de la carpeta scss de esta manera:
* base/
* layouts/
* modules/
* plugins/
   * bourbon/
   * neat/  
   * _plugins-dir.scss
* styles.scss

y no me genera ningún problema al ejecutar la tarea.

**Comment by simmerer** [comment]
Same issue cropped up  in Rails 5.0.0.rc2 today after running `bundle update`. Didn't have `bourbon` in my Gemfile, and adding it to my Gemfile didn't resolve it.

**Comment by whmii** [comment]
@fschroiff you may be missing the sass path declaration in your gulpfile. Check out [the Bitters contrib gulpfile](https://github.com/thoughtbot/bitters/blob/master/Gulpfile.js). It works so there may be something that your gulpfile needs.

**Comment by whmii** [comment]
@fschroiff any word on this? get things sorted out?

**Comment by michaelpumo** [comment]
@fschroiff @whmii 

I solved this by doing the following (reduced code for brevity):

```
const bourbon = require("bourbon");
const neat = require("bourbon-neat");

// ...your code before.
.pipe(_.sass({ 
  includePaths: [
    neat.includePaths, 
    bourbon.includePaths
  ]
})) 
// ...your code after.
```

Hope this helps someone out.
