### ISSUE TITLE
Publish beta on npm?

### ISSUE THREAD

**Issue by sergei-maertens** [thoughtbot/bourbon#887]
Hi,

Is it possible for the maintainer(s) to publish the v5.0 beta on npm? I'm working on a new project and currently only stable is on npm. This would easily allows us to stick to npm stack and use the latest and greatest Bourbon.

**Comment by gbouteiller** [comment]
+1, in fact, this will allow the use of Bitters without yelling for $font-stack-system ;). Thank you very much guys, for your work.

**Comment by sergei-maertens** [comment]
that's exactly why I submitted this issue :-)

**Comment by sergei-maertens** [comment]
Nevermind, I did not know you can also install from github directly with npm:
`npm install --save-dev git+ssh://git@github.com:thoughtbot/bourbon.git`

**Comment by tysongach** [comment]
@sergei-maertens @gbouteiller Hello! We do publish the beta to npm. You can install these pre-releases using `npm install --save-dev bourbon@5.0.0-beta.5`.

**Comment by sergei-maertens** [comment]
Thanks, still getting used to the node ecosystem.
