### ISSUE TITLE
Override $buttons-list

### ISSUE THREAD

**Issue by microcipcip** [thoughtbot/bourbon#890]
How do I override this variable in my project? I don't want to change the `library/buttons.scss` file 
```
$buttons-list: (
  ".btn", // my change
  "button",
  "[type='button']",
  "[type='reset']",
  "[type='submit']",
);
```

**Comment by tysongach** [comment]
Hi @microcipcip! We don’t offer a way to amend the list (on a per project basis or through a setting), beyond editing the source file which you mentioned you don’t want to do and we also don’t recommend. Couple reasons for this:

1. This actual _list_ is considered “private” (internal to Bourbon), but we surface the list publicly via the variables `$all-buttons`, `$all-buttons-hover`, etc..
2. Our intention with these variables is to list out _base HTML elements_, so adding a class-based selector doesn’t align with our goal. Throughout Bourbon we don’t specify any classes and we want you as an author to have full control over how you want to architect class names.

I’d suggest just listing our two selectors:

```scss
#{$all-buttons},
.btn {
  …
}
```

**Comment by microcipcip** [comment]
Thank you very much! This is exactly what I needed, and it makes completly sense.

**Comment by tysongach** [comment]
@sixtyfive Something like this should work fine, applying the `.button` class to the `a` element:

```scss
#{$all-buttons},
.button {
  …
}
```
