### ISSUE TITLE
import "bourbon"; suddenly stopped working, load path is incorrectly set

### ISSUE THREAD

**Issue by jcmorrow** [thoughtbot/bourbon#893]
Hey folks,

 Yesterday I had all of my feature specs start failing on

`import "bourbon";`

 In my load paths I have:

`/Users/josh/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bourbon-5.0.0.beta.3/core/Users/josh/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bourbon-5.0.0.beta.3/core`

instead of just

`/Users/josh/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bourbon-5.0.0.beta.3/core/`

This only happens in the test environment, the dev environment is still fine.

 I am fairly sure it has to do with https://github.com/thoughtbot/bourbon/commit/a462ed2ac92db0e40ea2a7716eb7f5628e3ea523 but I'm not 100%. I'm going to keep messing with it, let me know if there's anything helpful I can provide 😄 

Edit: If I add `ENV["SASS_PATH"] = ""` to my spec_helper.rb everything works, and then even after I remove that line again everything continues to work. In the name of science, I'm gonna try and break it again 😥 

Edit2: I can't figure out how to break it again, which is disconcerting.

**Comment by tysongach** [comment]
@jcmorrow Hey! We had a Sass path bug in `5.0.0.beta.3`, but resolved it in `5.0.0.beta.5`. If you upgrade from beta 3 to 5, it should fix the issue.

**Comment by jcmorrow** [comment]
Ah, shoot, I don't know how I missed that I wasn't on the right version. 😖  Thanks @tysongach!

**Comment by tysongach** [comment]
@jcmorrow No worries! Happy we got it sorted out.
