### ISSUE TITLE
wrong number of arguments (1 for 0) for `flex'

### ISSUE THREAD

**Issue by kesha-antonov** [thoughtbot/bourbon#897]
Hello guys!
Thank you for your great gem!

I've got weird error. All other mixins (including flexbox) working fine. And I clearly see this mixin in code of local folder of bourbon. Can you tell me what can go wrong?

<img width="933" alt="screen shot 2016-05-24 at 00 19 48" src="https://cloud.githubusercontent.com/assets/11584712/15484952/4be59a54-2145-11e6-81da-6d97352a06f2.png">

**Comment by joshuaogle** [comment]
I'm guessing you upgraded Bourbon to a new version. The flex mixin has been removed since [it is well supported](http://caniuse.com/#feat=flexbox) without needing a prefix now. You can change the places you had `@include flex;` to just the regular `display: flex;`

**Comment by kesha-antonov** [comment]
Hello @joshuaogle !
Sadly no. I am using 4.2.7

Maybe It can be related to sassc?

**Comment by kesha-antonov** [comment]
Oh. Actually if it is good supported when no need to solve this issue/problem :)
Thanks!

**Comment by joshuaogle** [comment]
Well in that case I'm not sure what the issue was, but glad that helps sidestep the issue. If you do need IE support further back, then Autoprefixer is the way to go.
