### ISSUE TITLE
Issue with font-family in sass/scss

### ISSUE THREAD

**Issue by iandstanley** [thoughtbot/bourbon#910]
- First time project with bourbon/neat
- Installed bourbon/neat/bitters as per instructions on website
- I am using Jekyll as a build compiler / web server (website target on github)

I have been trying to use the **font-family: $helvetica** in my sass and keep getting the same error

> Regenerating: 1 file(s) changed at 2016-07-06 16:08:29   Conversion error: Jekyll::Converters::Scss encountered an error while converting '/css/main.scss':
>                   Undefined variable: "$helvetica". on line 7
...error:
>             Error: Undefined variable: "$helvetica". on line 7
>            Error: Run jekyll build --trace for more information.

This goes back to the source code:
```
h1
  font-family: $helvetica
```

main.scss contains
```
@import "plugins/bourbon/bourbon";
@import "plugins/base/base";
@import "plugins/neat-settings.scss";
@import "plugins/neat/neat";
```

neat-settings.scss does not override any of the base settings and just contains visual grid settings
```
$visual-grid: true;
$visual-grid-color: #faa;
$visual-grid-index: front;
$visual-grid-opacity: 0.2 !default;
$visual-grid-breakpoints: () !default;
```

Running the latest beta of bourbon installed fresh last week and checked for updates before posting this
> $ bourbon -v
> Bourbon 5.0.0.beta.6

Neat appears to function properly. As does using Refils for the footer/header

Any ideas?

**Comment by tysongach** [comment]
@iandstanley `$helvetica` was renamed to `$font-stack-helvetica` in Bourbon 5.

**Comment by tysongach** [comment]
@iandstanley Are you still having issues?

**Comment by iandstanley** [comment]
Nope. 

Similar problem exists with the docs for each of the font stacks.

I was going to sort out a patch to the docs but after running bundle install from the cloned repo it took out my working copy of Jekyll preventing me from continuing with my current design work. Fixing that took me a day of repeatedly uninstalling and installing Ruby and Gems till I was sick of it.

I'll maybe look at creating a patch later between work when I have the time to create a virtual machine and a clean install to work from.

**Comment by tysongach** [comment]
@iandstanley Sorry to hear about your troubles. Couple notes:

- The current stable release is 4.2.7. In that version, `$helvetica` is the proper variable name.
- In v5.0.0 beta version, `$helvetica` was renamed to `$font-stack-helvetica`, so if you’re on the beta, you’ll want to call that new name.
- The website (bourbon.io) docs are current to 4.2.7 and not up-to-date with the 5.0.0 beta, so they do not yet reflect the name change. They will be updated once we release 5.0 as a stable version. If you plan on making a patch to the current website, please keep in mind that they are for 4.2.7, so `$helvetica` is the correct variable name.
- In the future, we'll have version documentation which should make this more clear.
- For reference…
  - Here’s the font stack variables in 4.2.7: https://github.com/thoughtbot/bourbon/blob/v4-stable/app/assets/stylesheets/addons/_font-stacks.scss
  - And here they are for 5.0.0 (currently in beta): https://github.com/thoughtbot/bourbon/blob/master/core/bourbon/library/_font-stacks.scss
