### ISSUE TITLE
SASS_PATH impot does not work if there are multiple libraries using the same method

### ISSUE THREAD

**Issue by whmii** [thoughtbot/bourbon#916]
https://github.com/thoughtbot/neat/issues/460

Neat 2.0 and cask both use a join to append their file paths to the `SASS_PATH` variable so that they are accessible within the stylesheets. Unfortunately, if there is more than one library using this same method, the join does not function correctly and they append the url directly to the previous entry instead of adding another item to the array resulting in something like:

```bash
File to import not found or unreadable: bourbon.
Load paths:
  /Users/whmii/workspace/gutenberg/app/assets/fonts
  /Users/whmii/workspace/gutenberg/app/assets/images
  /Users/whmii/workspace/gutenberg/app/assets/javascripts
  /Users/whmii/workspace/gutenberg/app/assets/stylesheets
  /Users/whmii/workspace/gutenberg/vendor/assets/javascripts
  /Users/whmii/workspace/gutenberg/vendor/assets/stylesheets
  /Users/whmii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/turbolinks-2.5.2/lib/assets/javascripts
  /Users/whmii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/jquery-rails-3.1.2/vendor/assets/javascripts
  /Users/whmii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/coffee-rails-4.1.0/lib/assets/javascripts
  /Users/whmii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bourbon-5.0.0.beta.5/core/Users/whmii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cask-0.3.2/core
  (in /Users/whmii/workspace/gutenberg/app/assets/stylesheets/application.css.scss:6)

```

**Comment by tysongach** [comment]
@whmii This is an issue with Neat 2.0.

History:

- We tried simplifying: https://github.com/thoughtbot/bourbon/commit/73b09f618bd3189bf5af6f639e3df07680ed4fc7
- It then broke the world: https://github.com/thoughtbot/bourbon/pull/879
- We then went back: https://github.com/thoughtbot/bourbon/commit/a462ed2ac92db0e40ea2a7716eb7f5628e3ea523

The current path in Neat 2.0 is one that is caught in the “broken” period of these changes.

**Comment by tysongach** [comment]
@whmii Here’s a fix for Neat: https://github.com/thoughtbot/neat/pull/461

Closing this in favor of that PR.
