### ISSUE TITLE
Deprecate placeholder mixin or move to "Add-ons"

### ISSUE THREAD

**Issue by elisechant** [thoughtbot/bourbon#917]
Deprecate placeholder mixin or move to "Add-ons" as it's not required in modern build environments, ie using autoprefixer as a post process.

**Comment by tysongach** [comment]
Hi @elisechant! The placeholder mixin has been removed in v5.0 (currently in beta). See https://github.com/thoughtbot/bourbon/issues/702 for more info.

**Comment by elisechant** [comment]
nice 👍
