### ISSUE TITLE
Incorrect case handling for some vendor prefixes like flexbox

### ISSUE THREAD

**Issue by elisechant** [thoughtbot/bourbon#918]
### Expected behavior
When I invoke the prefixer mixin, in the case of flex(), the resultant code does not correctly prefix flex syntax because the implementation is non-regular across browser permutations and is not as simple as literally _prefixing_ with "-webkit", "-moz" etc.

Additionally there are other "hacks" that tools like autoprefixer act to regulate. This is their list of non-regular vendor cases: https://github.com/postcss/autoprefixer/tree/master/lib/hacks

How can the prefixer mixin be improved to cater for these many edge cases or might the fit purpose of that mixin be indeed reviewed?

In many cases, people are using postcss tools to strip prefixed properties and recompose them using autoprefixer, ie https://github.com/postcss/autoprefixer/issues/536.

**Comment by elisechant** [comment]
can close, just reviewing v5 announcement where this is addressed: https://github.com/thoughtbot/bourbon/issues/702

**Comment by tysongach** [comment]
Hi @elisechant! Yep, we’ve removed all prefixing mixins in v5.0 (currently in beta).

**Comment by elisechant** [comment]
nice 👍
