### ISSUE TITLE
@import 'bourbon/bourbon' doesn't import.

### ISSUE THREAD

**Issue by quangv** [thoughtbot/bourbon#927]
### Expected behavior
bourbon is imported to `test.css`

### Actual behavior
`test.css` is 2 blank line. There was no error messages

test.css:
```


/*# sourceMappingURL=test.css.map */
```

### Steps to reproduce behavior
```
mkdir test
cd test
bourbon install
echo '@import "bourbon/bourbon";' > test.scss
sass test.scss test.css
```

### Bourbon version
Bourbon 4.2.7

### Environment info
Sass 3.4.22 (Selective Steve)

### Screenshots (if relevant)

When I create a `_test2.scss` and import it, that works...

**Comment by quangv** [comment]
https://github.com/thoughtbot/bourbon/issues/20 - doh

**Comment by tysongach** [comment]
@quangv Yes, Bourbon has zero output on install. Only when you _use_ a feature will you have output. We consider this a feature; very lightweight, and full author control! Glad you got it sorted. 😄
