### ISSUE TITLE
Gradients

### ISSUE THREAD

**Issue by davebowker** [thoughtbot/bourbon#928]
Apologies if this is in the wrong place, but I couldn't find any forum/slack/irc/etc to raise it.

I've read through the docs and see that you're no longer supporting pre-fixed mixins -- is this why bourbon 5 beta 6 has removed the linear and radial gradients?

On another note:
I tried to use bitters (latest version from bower) with bourbon 4.2.7 but it failed due to not having the $font-stack variable included which is why I had to upgrade to the b5.beta. Might throw others off if your stable bitters doesn't play well with the stable bourbon.

D

**Comment by tysongach** [comment]
Hi @davebowker!

Yes, we’ve removed the linear and radial gradient mixins in Bourbon 5 because they were simply prefixing values, which is no longer needed (or Autoprefixer can do it for you).
