### ISSUE TITLE
'No mixin named' error for all mixins

### ISSUE THREAD

**Issue by jm-kumaresh** [thoughtbot/bourbon#929]
### Expected behavior
Should compile the mixin successfully

### Actual behavior
Error: no mixin named placeholder

### Bourbon version
Bourbon 5.0.0.beta.6

### Environment info
Windows 10
Using [Tars](https://github.com/tars/tars) build system

### Screenshots (if relevant)
![image](https://cloud.githubusercontent.com/assets/2070512/17960221/5f659f90-6ac2-11e6-9125-3fbf8b1eb8e3.png)

**Comment by mykhrd** [comment]
the mixin files were gone when I tried installing v.5 via gulp. when i tried to get back the files from the assets folder here in git, deprecation error occurs.

**Comment by tysongach** [comment]
@jm-kumaresh Your comment in #874 leads me to believe you are using Refills? If so, I’d recommend not yet using Bourbon 5 (which is currently in beta).

The current release of Refills is not up to date with Bourbon 5 yet, though the `master` branch on GitHub is.

**Comment by jm-kumaresh** [comment]
@tysongach But I read refills requirements is Bourbon 5.0+. Will it run with the previous version (4.2.7) of Bourbon..?

**Comment by tysongach** [comment]
@jm-kumaresh Yes, it will run with 4.2.7. Sorry, the readme on GitHub is referring to the `master` branch. I'll make that more clear.

**Comment by tysongach** [comment]
@jm-kumaresh I’m struggling to cut a new release of the Refills gem which includes updates for Bourbon. But both the Refills website and the GitHub `master` branch _are_ up to date with Bourbon, so you can pull from there.

**Comment by rblakeb** [comment]
I am getting this problem as well when using Refills. I am using Bourbon 4.2.7 with Refills 0.2.0. The variables are working, just not the mixins.
