### ISSUE TITLE
Gem slows rails boot

### ISSUE THREAD

**Issue by losvedir** [thoughtbot/bourbon#932]
### Expected behavior

Conceptually, I'd expect bourbon would mostly be a few static sass files and shouldn't appreciably affect rails start up time (e.g. firing up `rails console`).
### Actual behavior

When I ran [bumbler](https://github.com/nevir/Bumbler), a gem which analyzes how the gems in a rails app's `Gemfile` affects boot time, I saw that the `bourbon` gem was one of my slowest gems, adding about `400ms` to boot. (For comparison, `rails` takes about `600ms` and the `neat` gem takes just `6ms`).
### Steps to reproduce behavior

```
$ gem install bumbler
$ bumbler -t 10
```
### Bourbon version

We're using the `4.2.3` version of the gem. I tried upgrading to `4.7` but it was even slower.
### Environment info

Rails 4.2.7.1. In addition to using bourbon ourselves, we also use activeadmin, which also depends on bourbon.
### Screenshots (if relevant)

<img width="453" alt="screen shot 2016-08-28 at 6 29 34 pm" src="https://cloud.githubusercontent.com/assets/384428/18037251/6f1f130c-6d4d-11e6-801c-9b1ae232a53b.png">

**Comment by tysongach** [comment]
Hey @losvedir! This is interesting; thanks for looking into it.

I haven’t had a chance to dive into what could be causing this, but out of curiosity have you tried v5.0.0.beta.6?

**Comment by tysongach** [comment]
I’ve run Bumbler on a handful of Rails apps that use Bourbon, and I’m not seeing anything near the ~400ms mark (more like 20ms).

I noticed Active Admin is listed above, as well, which has a dependency on Bourbon. Maybe that dependency is causing a slow boot?

Either way, I’m going to close this as I’ve been unable to track down any specific action items. Bourbon is indeed just some static Sass files.
