### ISSUE TITLE
Sass (libsass?) won't compile with custom settings

### ISSUE THREAD

**Issue by creuter** [thoughtbot/bourbon#933]
### Expected behavior

Adding 

```
$_bourbon-defaults: (
  "modular-scale-ratio": $double-octave,
);
```
should let Sass compile, and change the modular scale ratio.

### Actual behavior
`error: Compiling of web/static/css/app.scss failed. Undefined operation: "null gt null". ^G`

It compiles when removing the `_` from `$_bourbon-defaults:`, but that obviously doesn't update bourbon's settings.

### Steps to reproduce behavior
Add

```
$_bourbon-defaults: (
  "modular-scale-ratio": $double-octave,
);
```

after bourbon's been imported.

### Bourbon version
5.0.0-beta.6

### Environment info
Elixir/Phoenix, using brunch 2.7.4 with sass-brunch 2.6.3

**Comment by creuter** [comment]
Whoops. I needed to set `$bourbon`, not `$_bourbon-defaults`.

**Comment by tysongach** [comment]
The `$_bourbon-defaults` map is internal to the library. This is where we set default configuration options.

As a user, you can set a `$bourbon` map with your own overrides to the configuration and we’ll use those values instead. We merge the two maps, so if you only want to change one setting, you can do that.
