### ISSUE TITLE
Publish the v5 beta to NPM?

### ISSUE THREAD

**Issue by afm-sayem** [thoughtbot/bourbon#934]
Currently, the npm version is sitting at `4.2.7`. I suggest releasing the beta version under a tag so that people who are starting a new project can use the latest beta right away.

The files generated by bitters `v1.4` is incompatible with bourbon `4.x` which is forcing me to install an older version of bitters.

I'm getting  `Error: Undefined variable: "$font-stack-system".` on the files generated by bitters `v1.4.0` and `1.3.2`. I'm stuck with bitters `1.2`.

**Comment by Juanelorganelo** [comment]
Try with
```
npm install bourbon@5.0.0-beta.6
```

**Comment by tysongach** [comment]
We do publish the beta to npm. You can use the command above; thanks @Juanelorganelo!

**Comment by tysongach** [comment]
FWIW, you can also run `npm install bourbon@beta` to get the latest beta.
