### ISSUE TITLE
Font color linear gradient

### ISSUE THREAD

**Issue by peterpeterparker** [thoughtbot/bourbon#940]
Hi,

Am I missing something or doing something wrong, but I'm not able to set a font color as gradient.
I tried following

    .myTest {
            color: linear-gradient(to bottom, #feb79c, #ff65a9);
     }

Which is interpreted by Chrome as "Invalid property value"

Thx in advance for your help

**Comment by abea** [comment]
`color` can't be a gradient. CSS considers gradients to be like images. See: https://developer.mozilla.org/en-US/docs/Web/CSS/color

This is unrelated to Bourbon, but you can make text a gradient using the `-webkit-background-clip` or the `mix-blend-mode` properties. It looks like browser support might be decent for the former, though you'd want a fallback. None in IE for `mix-blend-mode`.

- mix-blend-mode: https://css-tricks.com/how-to-do-knockout-text/#article-header-id-4
- background-clip: http://creative-punch.net/2014/02/colorful-gradient-text-css3/

**Comment by peterpeterparker** [comment]
Thx for the nice detailed answer, understood.

I build an app for iOS and Android. Gonna try my luck with following piece of code using  -webkit-background-clip as you proposed, otherwise gonna have to use a svg or something like that.

        @include linear-gradient(to bottom, $fluster-peach1, $fluster-peach3);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;

best regards
