### ISSUE TITLE
Undefined mixin 'radial-gradient'.

### ISSUE THREAD

**Issue by zarianl** [thoughtbot/bourbon#943]
### Expected behavior
After installing both the Rails Gem and the regular gem, neither one seems to contain the radial gradient mixin.

**Comment by tysongach** [comment]
Hi @zarianl!

What version of Bourbon are you using? Can you share the code where you’re invoking the `radial-gradient` mixin?

**Comment by zarianl** [comment]
Bourbon 5.0.0.beta.6

.radial-bg{
          @include radial-gradient(rgba(43, 144, 217, 1), rgba(43, 144,
217, 0));
          height: 150px;
          width: 250px;
          position: absolute;
          display: inherit;
          z-index: -2;
          top: -30%;
          left: -30%;
        }

On September 29, 2016 at 7:18:18 AM, Tyson Gach (notifications@github.com)
wrote:

Hi @zarianl <https://github.com/zarianl>!

What version of Bourbon are you using? Can you share the code where you’re
invoking the radial-gradient mixin?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/thoughtbot/bourbon/issues/943#issuecomment-250463131>,
or mute the thread

**Comment by tysongach** [comment]
The `radial-gradient` mixin has been removed in Bourbon 5.

You can read more about this decision in [this Issue](https://github.com/thoughtbot/bourbon/issues/702), as well as view a full list of removals and other changes in our [Change Log](https://github.com/thoughtbot/bourbon/blob/master/CHANGELOG.md).

It’s also worth noting that CSS gradients has pretty strong support these days, so you might not need to prefix: http://caniuse.com/#feat=css-gradients.
