### ISSUE TITLE
Update `hide-visually` for better pronunciation

### ISSUE THREAD

**Issue by tysongach** [thoughtbot/bourbon#944]
Facebook recently discovered that the technique they were using to hide content visually (which is the same as what we use in the `hide-visually` mixin) was causing each letter to wrap to new lines and therefore be pronounced oddly.

Adding `white-space: nowrap;` resolved the issue, and we should update our mixin to do the same.

Reference: https://medium.com/@jessebeach/beware-smushed-off-screen-accessible-text-5952a4c2cbfe#.z5l8ex9ed

**Comment by bekapod** [comment]
@tysongach were you going to work on this or can I work on a PR (within the next few days)? 😄

**Comment by tysongach** [comment]
@bekapod Go for it! Thanks for hopping in.

**Comment by bekapod** [comment]
(I haven't forgotten about this, I plan to work on it this evening 😄 )
