### ISSUE TITLE
Bourbon mysteriously not found in Rails 5 app

### ISSUE THREAD

**Issue by mcmire** [thoughtbot/bourbon#945]
I just discovered something weird/interesting.

I have a Rails 5 app where I have Bourbon (5.0.0.beta.6) in the Gemfile, but not Neat. `application.scss` has `@import "bourbon"` at the top of it. When I attempt to load any page, Rails reports that it doesn't know how to find Bourbon. However, as soon as I add Neat to the Gemfile, then everything seems to work.

I noticed that a while back, the Rails engine was removed in favor of only modifying `ENV["SASS_PATH"]`. Are you sure this works in a Rails environment? (Then again, why adding Neat would magically work doesn't make any sense to me, but whatever.)

**Comment by mcmire** [comment]
On closer inspection, I don't think this has anything to do with Neat, but this might have something to do with using the `bourbon` gem in combination with the `bootstrap-sass` gem instead. I'm noticing that if `bootstrap-sass` is listed after `bourbon` in the Gemfile then everything seems to be okay, but as soon as you switch the order then Rails says it can't find Bourbon. I'll see if I can reproduce this in a fresh Rails app.

**Comment by frodsan** [comment]
I'm experiencing the same. The environment variable is set:

```
>> ENV["SASS_PATH"]
=> "/Users/frodsan/Code/app/.gs/gems/bourbon-5.0.0.beta.6/core:/Users/frodsan/Code/app/.gs/gems/neat-2.0.0.beta.1/core"
```

But it couldn't be find by sprockets:

```
Sprockets::FileNotFound: couldn't find file '/Users/frodsan/Code/app/.gs/gems/bourbon-5.0.0.beta.6/core/bourbon/library/_modular-scale.scss'
  /Users/frodsan/Code/app/app/assets/config
  /Users/frodsan/Code/app/app/assets/images
  /Users/frodsan/Code/app/app/assets/javascripts
  /Users/frodsan/Code/app/app/assets/stylesheets
  /Users/frodsan/Code/app/vendor/assets/javascripts
  /Users/frodsan/Code/app/vendor/assets/stylesheets
  /Users/frodsan/Code/app/.gs/gems/normalize-rails-4.1.1/vendor/assets/stylesheets
```

**Comment by mcmire** [comment]
Okay. For the record, I am using Sprockets 3.

**Comment by tysongach** [comment]
@mcmire Are you still having issues? Is this code available somewhere that I can see it?

**Comment by tysongach** [comment]
@mcmire Also, if you move down to Bourbon `4.2.7` in your Gemfile and bundle, does the “not found” error persist? Note that you may get a Sass error when doing this (since some 4.x features have been removed in 5.x), but if the “not found” error goes away, that is very interesting.

**Comment by teoljungberg** [comment]
@mcmire -

Tyson and I tried to reproduce this issue by creating a new Rails 5 app, which can be found here: https://github.com/teoljungberg/rails-5-bourbon-issue.

We sadly weren't successful.

Could you look in the our reproduction app and see if there's anything you did differently in yours?

**Comment by mcmire** [comment]
Hey @tysongach and @teoljungberg! It's a client project so unfortunately I can't share the code, but I did take a look at the Rails app you created and tried a few things with it. Surprisingly I wasn't able to reproduce this issue, either. I also tried to downgrade Bourbon in my app but I was still seeing the not found error. So... I guesss maybe the issue is with some other gem, I'm not sure. Anyway, it doesn't appear to be a Bourbon bug, but I'm curious what you think about it.

**Comment by tysongach** [comment]
> I also tried to downgrade Bourbon in my app but I was still seeing the not found error.

Interesting. I wanted to test this because in `5.0` we did adjust the `SASS_PATH` and I worried it was the root cause (although those have been shipped in quite a few betas with no other reported issues). But going to `4.x` maintains the same error…

I don’t have any new ideas on how to isolate and find the problem yet.

**Comment by mcmire** [comment]
Cool. Mind if I close this, then? If I figure it out then I'll report back.

**Comment by tysongach** [comment]
@mcmire Sounds good. Best of luck!

**Comment by StarWar** [comment]
I'm using rails 4.2.7 and it's not finding bourbon when using 5 beta 7 and when I downgraded bourbon to 4.2.7 it worked. But now bitters stopped working because of some variable not found.

**Comment by tysongach** [comment]
@starwar Please file a new issue, including all the details of your environment.
