### ISSUE TITLE
Transition mixin doesn't work in ember project

### ISSUE THREAD

**Issue by erichonkanen** [thoughtbot/bourbon#961]
Hello, previously I have used bourbon with success, in a newer project it seems to work except the `@include transition()` mixin which does not work and does not inject the styles into the element.

any ideas on how to diagnose this?

**Comment by tysongach** [comment]
Hi!

What version of Bourbon are you using? Note that the `transition` mixin has been removed in v5.0.

**Comment by Le-future** [comment]
Hello,

I'm now using the last version of Bourbon and if @include transition has been removed, what I have to use now?

Thanks!
