### ISSUE TITLE
Investigate moving away from SCSS-Lint

### ISSUE THREAD

**Issue by tysongach** [thoughtbot/bourbon#970]
scss-lint is [potentially being deprecated](https://github.com/brigade/scss-lint/commit/4ac76f9575464028447cbc4042d92eb1089d3899) and the team has indicated that the community might want to start using other tools.

[Sass Lint](https://github.com/sasstools/sass-lint) looks like it might be a good alternative, having a close feature parity.

**Comment by jmp1548** [comment]
I have some experience with Sass-lint and it work very well. Very similar to scss-lint. Are you looking to convert an old .sass-lint.yml.

**Comment by tysongach** [comment]
We already have an SCSS-Lint configuration, so a conversion from that might be wise: https://github.com/thoughtbot/bourbon/blob/master/.scss-lint.yml

**Comment by jmp1548** [comment]
@tysongach  I can look into converting it from .scss-lint to sass-lint.

**Comment by tysongach** [comment]
@jmp1548 Looks like there is a tool for this: http://sasstools.github.io/make-sass-lint-config/

**Comment by pmackay** [comment]
Might [Stylelint](https://github.com/stylelint/stylelint) be worth a look as well?

**Comment by jmp1548** [comment]
Hi @tysongach, my apologies for neglecting to update anything. That tool you mentioned works great, but it removes many linting rules, because sass-lint does not have them built in. I have been pretty busy so maybe Styelint might be worth a shot, if @pmackay wants to look into it.

**Comment by tysongach** [comment]
We use Hound (and want to keep using it), which is really why we use SCSS-Lint. There’s been [recent work to add Stylelint to Hound](https://github.com/houndci/hound/pull/1334), so that is possibly the best route we could take…
