### ISSUE TITLE
Unify installation guides between the readme and website

### ISSUE THREAD

**Issue by bichotll** [thoughtbot/bourbon#976]
### Expected behavior
See that it can be installed with bower/node. Not just ruby. (All this on the mainpage http://bourbon.io/).

### Actual behavior
Shows that it can be just installed with Ruby/Rails.

### Solution
Add a new line at end of it like 
"Bourbon can also be installed and used with bower/node and others.
Check out our github README for more information."

**Comment by tysongach** [comment]
Hi @bichotll! We actually have a new website in the works that will do a much better job at providing all of this information.

We’re focusing efforts on that new site, but feel free to put up a PR to add the line about GitHub. The current site can be found in this repo in the `gh-pages` branch.

**Comment by tysongach** [comment]
I’m going to close this because there is no action item left here, but rather it’s just a matter of time when we launch the new website which has the same install instructions.
