### ISSUE TITLE
File to import not found or unreadable: bourbon angular-cli

### ISSUE THREAD

**Issue by skarensmoll** [thoughtbot/bourbon#979]
I just installed bourbon with **npm install --save bourbon**
then I added the **@import "bourbon";** to my scss file  and I got the following error 

![image](https://cloud.githubusercontent.com/assets/7997951/20635757/a30ca79c-b32f-11e6-8a3b-44809587bd95.png)

when I use it like this ..works
 `@import '~bourbon/app/assets/stylesheets/_bourbon';`

thank you in advance!

**Comment by tysongach** [comment]
@skarensmoll Hello! npm does not automatically surface paths for Sass importing. If you are using node-sass you’ll need to add Bourbon to your `includePaths` option, like so `require("bourbon").includePaths`. Alternatively, you could use something like [eyeglass](http://eyeglass.rocks/).

**Comment by tysongach** [comment]
@skarensmoll Any update here?

**Comment by skarensmoll** [comment]
Hi, @tysongach  the only way it worked for me using angular-cli was including the files like this

`@import '~bourbon/app/assets/stylesheets/_bourbon';;
@import '~bourbon-neat/app/assets/stylesheets/_neat';`

Thank you!

**Comment by loganegbert** [comment]
@tysongach I've had the same experience trying to get Bourbon and Neat to work in an NPM environment with Gulp.

I've done everything you explain in the installation guide for that pipeline using includePaths, but ultimately like @skarensmoll I had to do:

`@import "./node_modules/bourbon-neat/core/neat";
@import "./node_modules/bourbon/app/assets/stylesheets/bourbon";
`
To get bourbon and neat to import properly without an error in gulp.

**Comment by tysongach** [comment]
I’m going to close this, as the original issue filed appears to be resolved.

Regarding Gulp, here’s our Gulpfile we use in Bitters, which pulls Bourbon in: https://github.com/thoughtbot/bitters/blob/master/Gulpfile.js#L1

**Comment by dnutels** [comment]
Hi. Resolved how?

I am not sure how your Bitters file works (perhaps OS?), but:

**on Windows 10, for this SCSS file:**

```
@charset "utf-8";

@import "bourbon";
@import "neat";
```

**with the following `node-sass` setup:**

```
const sass = require('node-sass');

const bourbone = require('bourbon').includePaths;
const neat = require('bourbon-neat').includePaths;

const paths = [].concat(bourbone).concat(neat);

sass.render({
    file: 'src/common/style/theme.scss',
    options: {
        includePaths: paths
    }
}, (err, result) => {
    if (!err) {
        console.log(result);
    } else {
        console.error(err);
    }
});
```

**produces:**

```
 Error: File to import not found or unreadable: bourbon
```

**while this works perfectly:**

```
@charset "utf-8";

@import "node_modules/bourbon/app/assets/stylesheets/bourbon";
@import "node_modules/bourbon-neat/core/neat";
```

**when adjusting the `node-sass` to be:**

```
const sass = require('node-sass');

sass.render({
    file: 'src/common/style/theme.scss'
}, (err, result) => {
    if (!err) {
        console.log(result);
    } else {
        console.error(err);
    }
});
```

**Comment by nanijnv1** [comment]
> I just installed bourbon with **npm install --save bourbon**
> then I added the **@import "bourbon";** to my scss file and I got the following error
> 
> ![image](https://cloud.githubusercontent.com/assets/7997951/20635757/a30ca79c-b32f-11e6-8a3b-44809587bd95.png)
> 
> when I use it like this ..works
> `@import '~bourbon/app/assets/stylesheets/_bourbon';`
> 
> thank you in advance!

@import "~bourbon/core/_bourbon";

try this
