### ISSUE TITLE
Allow different units in `modular-scale`

### ISSUE THREAD

**Issue by whmii** [thoughtbot/bourbon#985]
### Expected behavior
Allow a user to customize the units output by `modular-scale()`.

### Actual behavior
Currently it will only output values in `em`s

### Rationale
The `modular-scale()` function is quite handy for sizing typography, however it could be used as a universal scaling system for things like spacing as well. However the current function only allows for an output of `em`s which limits it's usefulness. This could be updated to allow the user to select `rem`s or other values.

The interface for this is a bit odd but here are some potential options.
1. `modular-scale(1rem)`
1. `modular-scale(1 rem)`
1. `modular-scale(1, rem)`
1. `$bourbon: (modular-scale-unit: rem);`

**Comment by bazaglia** [comment]
@whmii Current `modular-scale` behavior is not clear to me. I can't compile an existing project because of this line:

```
modular-scale(1rem, 2)
```

Error is:

```
 error bourbon/functions/_modular-scale.scss (Line 40: Incompatible units: 'rem' and ''.)
```

However, as it is an exiting project, I guess this worked at some previous bourbon release. If I downgrade to any point, will I get it working again?

**Comment by tysongach** [comment]
Yep, I think we should investigate this. I’m earmarking it for v6.0.

**Comment by tysongach** [comment]
I’m going to close this, as it’s been open for a long while now without any movement; I see that as an indication that it might be a nice-to-have feature, but it’s not pressing.
