### ISSUE TITLE
New feature: button-link() mixin?

### ISSUE THREAD

**Issue by anhari** [thoughtbot/bourbon#987]
What do you think of adding a mixin that allows you to style a link as a button (similar to bootstrap's `.btn` class)?

I was thinking that it could take an optional parameter for the color and use `$action-color` as a default.

**Comment by tysongach** [comment]
Hi @anhari! That is a great idea, but I’m not sure that Bourbon is the place for this. Bourbon doesn’t carry any visual style opinion, and it doesn’t have any classes within the library, either.

Bitters might be a better place for something like this, as it does already come packaged with some basic button styles.
