### ISSUE TITLE
Problem importing from vendor/assets/components in Rails app with Bower

### ISSUE THREAD

**Issue by thelucid** [thoughtbot/bourbon#988]
### Expected behavior
Bourbon is getting installed in vendor/assets/components as I am using Bower with a Rails app. For some reason the main `_bourbon.scss` file is nested in `vendor/components/assets/app/assets/stylesheets/_bourbon.scss` but when I import it from there it fails.

### Actual behavior
```scss
@import "bourbon/app/assets/stylesheets/bourbon";
```

Creates this error:

```
File to import not found or unreadable: bourbon-deprecated-upcoming.
```

### Steps to reproduce behavior
See above.

### Bourbon version
4.2.7

### Environment info
Rails 5.0.1

**Comment by tysongach** [comment]
Hi @thelucid! How are you configuring Rails to import assets within `vendor/assets/components`?

**Comment by tysongach** [comment]
@thelucid Any update on my question above?
