### ISSUE TITLE
Radial-gradient compiling strangely in scss

### ISSUE THREAD

**Issue by sdouma** [thoughtbot/bourbon#989]
So if I use this notation
`background: radial-gradient(at center bottom,red,yellow,green);`
it compiles as
`radial-gradient(at center bottom at center bottom, #ff0000, #ffff00, #008000)` .
I have heard about similar problems with linear-gradient but not sure what to do here.

**Comment by sdouma** [comment]
Ok the problem I had was that I left out the optional shape parameter so instead I did `background: radial-gradient(circle at center bottom,red,yellow,green);`

**Comment by tysongach** [comment]
@sdouma Hi! Is this still an active issue, or did you resolve it?

**Comment by sdouma** [comment]
Ya nevermind resolved more of a compass issue
