### ISSUE TITLE
Can I add bourbon v5 (beta) to my project with Bower?

### ISSUE THREAD

**Issue by Trost123** [thoughtbot/bourbon#991]
I'm using Autoprefixer, so a lot of mixins from bourbon v4 conflict with it. Bourbon v5 (beta) fixed this issue, is there any way to add it to my project using Bower?

**Comment by mistergraphx** [comment]
Add this to your bower.json

````js
"dependencies": {
        "bourbon5":"bourbon#v5.0.0.beta.7",
    }
```

**Comment by tysongach** [comment]
I’m going to close this issue, as it appears to be resolved. 

Couple things worth noting:
- Installing the beta from the command line is also possible: `bower install bourbon#v5.0.0.beta.7`
- Autoprefixer will also [_remove_ out-of-date prefixes](https://github.com/postcss/autoprefixer#outdated-prefixes), so there shouldn’t be a _conflict_ per se with using Bourbon 4.x with Autoprefixer, more that the work of prefixing would be happening in two places. I note this because sometimes a Bourbon upgrade is not a quick task, but that shouldn’t keep you from introducing Autoprefixer into your toolchain.

**Comment by Trost123** [comment]
Thanks, that did the trick!
-
Is there any way to specify the version in a way, that allows checking for updates?
(analogue of "neat": "^1.8.0")
No big deal if that's impossible, just curious.

**Comment by Trost123** [comment]
> there shouldn’t be a conflict per se with using Bourbon 4.x with Autoprefixer
I used "Background Image" mixin, and it resulted in two identical "background-image" rules appearing in my css. Not a deal-breaker but it buggered me.
Overall I prefer to move on to Bourbon5, because a big part of B4 documentation is simly wendor-prefix-mixins, which I don't really need to know.

**Comment by mistergraphx** [comment]
@Trost123  In my workflow i've a folder to store frameworks/libs and my projects load the stuff and tools from this place, so i can deal with multiple versions of bourbon, or others between my projects. Structure and gulp file is here, https://github.com/mistergraphx/Fragments_builder.

**Comment by Trost123** [comment]
@mistergraphx Thanks, but I think you misunderstood my second question there.
It's more of a bower-related question (maybe I should post it there?):
Let's pretend I do "bower install bourbon#v5.0.0.beta.7" and then bourbon#v5.0.0.beta.8 is released.
If I use "bower update" in my console - bourbon will not be updated.
[Screenshot of issue](http://prntscr.com/e0ixxw)
I think there must be something like "bower install bourbon#latest" but to install latest pre-release.

**Comment by mistergraphx** [comment]
I've understood but not really answered ;-).I gived you an example of switching between multiple versions during the pre-release period.
I'm not a "bower expert" but in the bower registry if your do `bower search bourbon` it's the version 4 witch is actually downloaded cause it's the stable branch/tag, as in the Ruby gem and It's just the maintainer of a package who choose to publish a new revision of the bower package, see : https://bower.io/docs/creating-packages/#register 

That's why we add the specific tag `#<tag|branch>`, as described in the bower install documentation <https://bower.io/docs/api/#install>.

You can try to download directly from the master branch using `bourbon#master`, but i'm not certain it's a good practise if your project is in production ;-)

**Comment by Trost123** [comment]
@mistergraphx 
I guess we'll just have to update manually until v5 is released as stable, but that's no big deal!
Thanks for the help. 👍

**Comment by tysongach** [comment]
@Trost123 I don’t use Bower a lot, so can’t speak from experience, but it appears that you can specify a _range_ of versions: `bourbon#>=5.0.0.beta.7 <5.1.0`. This should match any betas released _after_ beta 7, and also match the stable release of 5.0, including any patch releases (5.0.x).

I just found this neat tool from npm which helps you visualize these SemVer qualifiers: https://semver.npmjs.com/.

**Comment by Trost123** [comment]
@tysongach Thanks, that's exactly what I needed! And that tool sure is handy.
Also noticed a weird thing:
"npm info bourbon" returns all versions, up to 5.0.0-beta.7'
"bower info bourbon --verbose" returns versions up to 4.2.7
So the problem must be on bower's side, as NPM let's me do "bourbon#>=5.0.0.beta.7 <5.1.0" like you advised and bower doesn't.
I'll leave you alone go annoy the Bower team from now on. 😈

**Comment by tysongach** [comment]
Ah, I think there are minor discrepancies between Bower and npm and how they handle SemVer with pre-releases. Some accept a hyphen (`-`) to denote pre-releases, others only accept periods (`.`). I can't remember who accepts which formats. I keep meaning to sit down and write it all down for reference later…but just something to watch out for.

**Comment by Trost123** [comment]
@tysongach I don't think it's about that.
[See this screenshot](http://prntscr.com/e0png0): Bower actually thinks that 4.2.7 is latest version. Also note that there are older betas in the list (on the screenshot), like "3.2.0-beta.2", so the naming conventions are not the issue here.
Going to post it on Bower repository to figure it out.

**Comment by tysongach** [comment]
Interesting. Yeah, it would be nice to confirm whether Bower does or does not include pre-release versions when listing.

I _think_ Bower piggy-backs a lot of Git/GitHub tags, so it is possible we didn’t properly tag things right before, or now? It’s very opaque, but I’m intrigued to learn more!

**Comment by Trost123** [comment]
@tysongach I think I found the pattern. Look at all "beta" and "rc" versions that are in my screenshot.
Versions like "3.2.0.beta.1" are not recognized by Bower correctly, while v3.2.0-beta.1 (or 3.2.0-beta.1) are recognized.
Also if you go to https://semver.npmjs.com/ and enter "bourbon" into "pick a package" field and press enter, you'll see versions output in this format: "5.0.0-beta.5", "4.2.0-pre"

**Comment by tysongach** [comment]
So this goes back to [my comment above](https://github.com/thoughtbot/bourbon/issues/991#issuecomment-275471810) on whether a hyphen or period was used to denote the pre-release. Unfortunately, npm and Bower handle this nomenclature differently than RubyGems (which we also publish to).

The Semantic Versioning spec indicates that “A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version” (e.g. `1.0.0-alpha.1`). 

However—if I remember correctly—RubyGems throws an error and will not publish a pre-release denoted by a hyphen, only if it is a period.

There is [an open PR to Semantic Version](https://github.com/mojombo/semver/pull/316) that tries to clarify the correct method (hyphen) and I hope that RubyGems aligns with everyone else.

I found all of this out through trial and error once I took over maintaining Bourbon. I plan to sit down and map all of this out with learnings and note the conflicts. I may have mistakingly versioned things incorrectly, and between Git/GitHub, npm, Bower and RubyGems, we have confusion.

**Comment by tysongach** [comment]
Here is some documentation from RubyGems on them indicating use of a period to denote pre-releases: http://guides.rubygems.org/patterns/#prerelease-gems

I think the action here is that version number every _but_ RubyGems, needs to utilize the hyphen, in accordance to SemVer. RubyGems appears to be the violator of that spec, so we’ll have to use the period for them here: https://github.com/thoughtbot/bourbon/blob/master/lib/bourbon/version.rb#L2.

**Comment by tysongach** [comment]
Nah, I’m curious what they say and see if our assumptions are correct.

**Comment by Trost123** [comment]
I guess guys at Bower can fix (workaround) it, because NPM actually transforms "." into "-" before "beta"
As seen in "[npm info bourbon](npm info bourbon)"
So they could do the same.
