### ISSUE TITLE
Undefined mixin 'media'. i keep getting this error when i try to use the navigation from refill... I used suspenders to bootstrap rails app

### ISSUE THREAD

**Issue by claeusdev** [thoughtbot/bourbon#993]

**Comment by tysongach** [comment]
Hi @claeusdev!

The `media` mixin is a feature of [Neat](https://github.com/thoughtbot/neat) (v1.x), not Bourbon.

What version of Suspenders did you use to generate your Rails app? As of Suspenders v1.43.0, Neat 2.0 (beta) is being used, and the `media` mixin no longer exists.

Refills is currently in re-development to catch it up with the latest Bourbon and Neat betas, but the website and gem are not currently compatible with them.

**Comment by claeusdev** [comment]
Hi @tysongach I used suspenders version 1.44.0.. oh okay cool so i can write my own media queries or mixins then?

**Comment by tysongach** [comment]
@claeusdev Yes, or you can use Neat’s new `grid-media` mixin and pass in a custom grid map: http://neat.netlify.com/docs/latest/#grid-media

If you have any questions or issues with that, please file an issue over in Neat’s repo: https://github.com/thoughtbot/neat/issues

**Comment by alexanderadam** [comment]
I had the same issue when trying [code examples](http://refills.bourbon.io/#er-toc-id-13) from refills.
But for me it just looks like the examples aren't up to date and media is now called grid-media.

But I don't know exactly, it's just how it looks to me.

**Comment by tysongach** [comment]
@alexanderadam Current Refills is not compatible with the newly released Neat 2.0.

**Comment by alexanderadam** [comment]
@tysongach this explains a lot. Thank you for the insanely fast answer!

**Comment by dmiller72** [comment]
Is this still the case because I am having the same problem. The navigation background variable is giving me an error as well. LIke many others I have seen as I've Googled my problems I'm new to The Bourbon suite of goodies although not new to web development. My installs are all intact and a few of the refills actually worked (eg...cards).
