### ISSUE TITLE
No mixin named align-items

### ISSUE THREAD

**Issue by andyjessop** [thoughtbot/bourbon#995]
### Expected behavior
`align-items` mixin should be available? http://bourbon.io/docs/#flexbox

### Actual behavior
It looks like it's not there. Searching for `align-items` in `/bourbon` doesn't yield any results

### Bourbon version
5.0.0.beta.7

**Comment by tysongach** [comment]
@andyjessop The `align-items` mixin has been removed in 5.0, which is currently in beta. The website documentation reflects the current stable version, 4.2.7.

Our [change log](https://github.com/thoughtbot/bourbon/blob/master/CHANGELOG.md) lists all the changes, including removals, for 5.0.
