### ISSUE TITLE
Document our deprecation process

### ISSUE THREAD

**Issue by tysongach** [thoughtbot/bourbon#999]
- https://github.com/thoughtbot/bourbon/commit/fc9d1ee3e9a13cd57250a39b4bd084f9ee3fce12
- https://github.com/thoughtbot/bourbon/commit/094480bbd58b53787d0d58db5db93060ebe8eaa1
- Prefix all warnings and errors with `[Bourbon]`?

**Comment by nypinstripes** [comment]
@tysongach Hey man, thanks for getting the position ones, i'm still getting like hundreds of dep. warnings everytime i build, deploy & run test suites in all my apps, mostly theyre related to is-length & is-size for the size & animation mixins,  spent a decent amount of time trying to trace it through npm & bower, it's tripping up my flow a bit.

**Comment by tysongach** [comment]
@nypinstripes Can you open a new issue and post the warnings? I meant for this issue to capture documentation for us maintainers on how we, as a project, deprecate things. We definitely have room for improvement!

**Comment by kernel-io** [comment]
thought I'd post this here as a public service

https://gist.github.com/kernel-io/cd74140018ea50cbae3578b7d24ac030
